### PR TITLE
sflayout: allow building without native scripting

### LINKED ISSUE #2154: sflayout.c unconditionally calls arrayfree while arrayfree is only if  _NO_FFSCRIPT not defined.
arrayfree() is defined in scripting.c and guard protected by  _NO_FFSCRIPT macro

but sflayout.c unconditionally calls arrayfree without _NO_FFSCRIPT guard. thus result  link error when build without native-scripting support.

### PR DESCRIPTION
**Pull request by adrientetar**
Closes #2154.

r? @frank-trampe

### CODE REVIEW

**Comment by frank-trampe** [comment]
@adrientetar, it is not immediately clear why the call to SFDefaultScriptsLines is unnecessary when native scripting is disabled. Could you explain what you found?

**Comment by adrientetar** [comment]
It's not exactly clear to me either. The Array data type is declared in scripting.h and arrayfree() is unavailable when native scripting is absent so I figured that the function which allocates should be deactivated as well but I'm not sure I understand what's strictly scripting code and what's regular code in there&hellip;

**Comment by frank-trampe** [comment]
I think it more likely that the Array stuff was originally implemented in scripting.h because that is where it was first needed but was then used elsewhere. It probably needs to go into some set of files other than scripting.c and scripting.h. It is probably better for it to go into a new set of files. Or perhaps we could use utils.c, make utils.h, add utils.h to the appropriate build targets, and include it in scripting.h and sflayout.c.

**Comment by adrientetar** [comment]
So then maybe the solution is to take arrayfree() out of ifdefed code?

**Comment by frank-trampe** [comment]
Actually, that's probably fine. I was thinking that the includes for scripting.h would be enclosed in ifdefs in most places, but that seems not to be the case. There might be something cleverly hidden in the build system that drops scripting.c if the build is to happen without scripting, so be sure to test a scripting-free build after making the change.

**Comment by frank-trampe** [comment]
I'm replacing this with #2249.

**Pull request closed without merging**
