### PR TITLE
Coverity cid#1400477

### PR DESCRIPTION
**Pull request by serval2412**
Provide a general summary of your changes in the **Title** above.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### Motivation and Context
- [ ] Why is this change required? What problem does it solve?
- [ ] If it fixes an open issue, include the text `Closes #1` (where 1 would be the issue number) to your commit message.

### Types of changes
What types of changes does your code introduce? Check all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description
- [ ] Describe your changes in detail.

### Final checklist
Go over all the following points and check all the boxes that apply. 
If you're unsure about any of these, don't hesitate to ask. We're here to help! Various areas of the codebase have been worked on by different people in recent years, so if you are unfamiliar with the general area you're working in, please feel free to chat with people who have experience in that area. See the list [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#people-to-ask).
- [ ] My code follows the code style of this project found [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#coding-style).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md) guidelines.

Your pull request will be tested via Travis CI to automatically indicate that your changes do not prevent compilation. FontForge is a big program, so Travis can easily take over 20 minutes to confirm your changes are buildable. Please be patient. More details about using Travis can be found [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#using-travis-ci).  
  
If it reports back that there are problems, you can log into the Travis system and check the log report for your pull request to see what the problem was. If no error is shown, just re-run the Travis test for your pull-request (that failed) to see a fresh report since the last report may be for someone else that did a later pull request, or for mainline code. If you add new code to fix your issue/problem, then take note that you need to check the next pull request in the Travis system. Travis issue numbers are different from GitHub issue numbers.

### CODE REVIEW

**Comment by jtanx** [comment]
This is raising compiler warnings, and that's on *default* (basically none) compiler flags

```
othersubrs.c: In function ‘ReadOtherSubrsFile’:
othersubrs.c:532:22: warning: passing argument 1 of ‘free’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
                 free(co[i]);
                      ^~
In file included from ../lib/stdlib.h:36:0,
                 from ../inc/basics.h:37,
                 from fontforge.h:32,
                 from othersubrs.c:3:
/usr/include/stdlib.h:563:13: note: expected ‘void *’ but argument is of type ‘const char *’
 extern void free (void *__ptr) __THROW;
             ^~~~

```

**Comment by serval2412** [comment]
@jtanx : would it be ok for you if I use "free((void *) co[i]);"

**Comment by jtanx** [comment]
No. When something is marked as `const`, it's usually a good sign you shouldn't be freeing it.

From a quick look at `CopyLines`, I think you're double-freeing `lines`.

**Comment by skef** [comment]
@jtanx `CopyLines` does just copy the pointers in `lines`, but whenever it's used `l` is set back down to zero shortly after. So when the loop is finished `lines` has the residual lines read in, if any. 

> When something is marked as const, it's usually a good sign you shouldn't be freeing it.

It might just be a non-optimal use of `const` in this case. It might just have been set to match `othersubrs_copyright`.

**Comment by jtanx** [comment]
Right, it's effectively transferring ownership. Ugh, I hate the mixing of literals and dynamically allocated memory.

In that case, cast it to `(char*)` while freeing, similar to https://github.com/serval2412/fontforge/blob/28145ebdcbf628aaa4b1329339426ada035e28cb/fontforge/othersubrs.c#L477

**Pull request merged**
