### PR TITLE
Update prefs

### PR DESCRIPTION
**Pull request by davelab6**
Hack to fix https://github.com/fontforge/fontforge/issues/2401#issuecomment-118649636

### CODE REVIEW

**Comment by adrientetar** [comment]
I do not want to see this enabled by default, personally;

**Comment by davelab6** [comment]
It is already enabled by default, has been for a couple of years; this PR turns it off.

**Comment by adrientetar** [comment]
Sorry, I meant set to 0.

**Comment by frank-trampe** [comment]
Is this discussion over? I don't follow.

**Comment by davelab6** [comment]
This is a work around because the feature causes unprompted crashes on
windows. I doubt a fix will be soon. I'm happy to see it reenabled after
crashes are fixed :)

**Pull request merged**
