### PR TITLE
MacOS Big Sur App Icon

### LINKED ISSUE #4574: Update app icon for macOS Big Sur
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [ ] The FontForge version and the operating system you're using
- [ ] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [x] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

image

I would love for the Mac app to fit in Better with macOS big sur icons by switching the app icon from a circle to the macOS app shape (rounded rect).

### PR DESCRIPTION
**Pull request by JaydenIrwin**
Changed the macOS app icon (.icns) from a circle to the Big Sur app shape.

### Type of change
- **New feature**
- **Non-breaking change**

Closes #4574

### CODE REVIEW

**Comment by skef** [comment]
If you try this in your App does it work well?

**Comment by JaydenIrwin** [comment]
Not sure how. :(

**Comment by skef** [comment]
This may have changed in more recent versions of MacOS but within the past few years you could "right-click" (secondary-click) on an app in the Finder and choose "Show Package Contents" and then you could descend into the App folder. The icon is in a location analogous to where it is in our source tree.

**Comment by JaydenIrwin** [comment]
Looks great thanks!
Screen Shot 2021-03-28 at 15 30 56

**Review by skef — APPROVED** [review]
Don't see any reason not to approve this. I'll let it sit for a bit before merging in case anyone else has an opinion.

Thanks for this!

**Review by ctrlcctrlv — CHANGES_REQUESTED** [review]
Why did you change the appearance of the icon? Now it doesn't look the same as on the splash screen, or on different OS's.

If you want to change it to be rectangular that's fine, but you should keep the shape of the internal icon as is.

image

**Comment by skef** [comment]
Mac OS restyles their icons every few years and right now they're rounded rectangles. Apps often follow suit. You can see from the screenshot how the author has matched up the edges of the App icon with the other current icons.

The image is the same, I don't see any reason why the *border* has to be consistent between different OSes.

**Comment by skef** [comment]
Oh, yes, I guess I agree with this. The illustration itself should be the same. 

@JaydenIrwin would it be possible for you to use either `desktop/tango/scalable/org.fontforge.FontForge.svg` or the pngs in the WxH directories in `desktop/tango` as the source material for the inside? I guess I should have pointed you towards those in the first place.

**Comment by JaydenIrwin** [comment]
Yeah I can change it. I just used the previous Mac icon as the inner shape.

**Comment by skef** [comment]
Ha, sure enough! Here we are yelling about "changing the appearance" when the Mac icon was like that in the first place.

**Comment by JaydenIrwin** [comment]
Should be good now.

**Comment by skef** [comment]
Looks good!

**Comment by JaydenIrwin** [comment]
Screen Shot 2021-03-31 at 13 01 32

**Comment by JaydenIrwin** [comment]
Screen Shot 2021-03-31 at 13 07 58

**Pull request merged**
