### PR TITLE
Adding deactivated icons for radio buttons and check boxes.

### PR DESCRIPTION
**Pull request by jrbastien**
### Motivation and Context
- [X] Why is this change required? What problem does it solve?
Deactivated radio buttons and check boxes appear as active because they use the same icons as the activated one.  These icons correct this.

### Types of changes
What types of changes does your code introduce? Check all the boxes that apply:
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description
- [X] Describe your changes in detail.
- Deactivated icons have been created by applying transparency at 50%.
- I have also updated the French po to distinguish between "unselected" and "deactivated".

Before:
radioonimages

After:
radioonimages_after

Before:
generatefontoptions

After:
options_144

### Final checklist
- [X] My code follows the code style of this project found [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#coding-style).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING**](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md) guidelines.

### CODE REVIEW

**Comment by frank-trampe** [comment]
It seems logical to me. Let's wait a day for any comments from @davelab6 and @larsenwork.

**Comment by larsenwork** [comment]
Looks good 👍

**Comment by davelab6** [comment]
Love it, please merge ASAP

**Comment by jrbastien** [comment]
Thank you all.

**Pull request merged**
