### PR TITLE
fontforge, fix build for Haiku, kudos to Kasper

### PR DESCRIPTION
**Pull request by Begasus**
Provide a general summary of your changes in the **Title** above.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### Motivation and Context
- [x] Why is this change required? What problem does it solve? (The fix has been in a patch for a long time, it shouldn't brake the build for other OS's
- [ ] If it fixes an open issue, include the text `Closes #1` (where 1 would be the issue number) to your commit message.

### Types of changes
What types of changes does your code introduce? Check all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description
- [ ] Describe your changes in detail.

### Final checklist
Go over all the following points and check all the boxes that apply. 
If you're unsure about any of these, don't hesitate to ask. We're here to help! Various areas of the codebase have been worked on by different people in recent years, so if you are unfamiliar with the general area you're working in, please feel free to chat with people who have experience in that area. See the list [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#people-to-ask).
- [x] My code follows the code style of this project found [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#coding-style).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md) guidelines.

Your pull request will be tested via Travis CI to automatically indicate that your changes do not prevent compilation. FontForge is a big program, so Travis can easily take over 20 minutes to confirm your changes are buildable. Please be patient. More details about using Travis can be found [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#using-travis-ci).  
  
If it reports back that there are problems, you can log into the Travis system and check the log report for your pull request to see what the problem was. If no error is shown, just re-run the Travis test for your pull-request (that failed) to see a fresh report since the last report may be for someone else that did a later pull request, or for mainline code. If you add new code to fix your issue/problem, then take note that you need to check the next pull request in the Travis system. Travis issue numbers are different from GitHub issue numbers.

### CODE REVIEW

**Comment by frank-trampe** [comment]
This is all it takes? The Haiku ecosystem has come a long way.

**Comment by Begasus** [comment]
> This is all it takes? The Haiku ecosystem has come a long way.

This is the last patch we used to get it building for Haiku, seems it's still valid :)
https://github.com/haikuports/haikuports/blob/3a074deba809e03b21f6ead18697ec8a3bc11c07/media-gfx/fontforge/patches/fontforge-20170731.patchset

**Comment by JoesCat** [comment]
> This is all it takes? The Haiku ecosystem has come a long way.

I recall Haiku kept math in a different location, and therefore the math library check in configure.ac was also a nod in the direction of Haiku ....although untested. :-)
I agree - this is impressive - a one line patch.

**Comment by frank-trampe** [comment]
Well, let's give it a try. It can't do any harm.

**Comment by Begasus** [comment]
In the meantime I created 2 new PR's at haikuports for libuninameslist and libspiro (last one failed one 1 test), but with this I can bump a git checkout for the open PR for fontforge, thanks for merging! :+1:

**Pull request merged**
