### PR TITLE
null pointer fixes when working with bad font files

### PR DESCRIPTION
**Pull request by devzer01**
I encoutered multiple crashes when trying to work with an asian font that had many transformation tables, mostly due incorrect char references in tables etc. with these additional null checks i was able to prevent fontforge from crashing while i was working. 

### Motivation and Context
- [x] Why is this change required? What problem does it solve?
- [ ] If it fixes an open issue, include the text `Closes #1` (where 1 would be the issue number) to your commit message.

### Types of changes
What types of changes does your code introduce? Check all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description
- [x] Describe your changes in detail.

### Final checklist
Go over all the following points and check all the boxes that apply. 
If you're unsure about any of these, don't hesitate to ask. We're here to help! Various areas of the codebase have been worked on by different people in recent years, so if you are unfamiliar with the general area you're working in, please feel free to chat with people who have experience in that area. See the list [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#people-to-ask).
- [x] My code follows the code style of this project found [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#coding-style).
- [x] I have read the [**CONTRIBUTING**](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md) guidelines.

Your pull request will be tested via Travis CI to automatically indicate that your changes do not prevent compilation. FontForge is a big program, so Travis can easily take over 20 minutes to confirm your changes are buildable. Please be patient. More details about using Travis can be found [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#using-travis-ci).  
  
If it reports back that there are problems, you can log into the Travis system and check the log report for your pull request to see what the problem was. If no error is shown, just re-run the Travis test for your pull-request (that failed) to see a fresh report since the last report may be for someone else that did a later pull request, or for mainline code. If you add new code to fix your issue/problem, then take note that you need to check the next pull request in the Travis system. Travis issue numbers are different from GitHub issue numbers.

### CODE REVIEW

**Comment by jtanx** [comment]
These checks are a bit inconsistent, especially when comparing pointers (sometimes against `'\0'`, sometimes against `0x00`) - stylistically they should all be compared against `NULL`.

That aside (and not having looked too deeply at this), I'm not sure if these checks are masking some underlying cause (*why* are those fields null in the first place? esp. when passing in to `u_strtod`; I can understand `utf8_idpb` though) which should be fixed instead.

**Comment by devzer01** [comment]
hi @jtanx

thanks you very much  for your valueble feedback,  i am just getting to touch c after 20 years (college graduation ) of commercial coding, where the development technologies made me dumber by the year.

Thank you very much for explaining the use of NULL, I started writing raw values just to understand what was going on under the hood., I do realize coding standards are important. 

I will also produce a issue with a font file that caused the crash. + try to understand the fix you suggested. 

I pushed this commit in a rush because (apologies for the poor quality of PR without any evidence) I forked the app to do something that is none standard and was worried of loosing track  of this fix.

Thanks again for the feedback. now i am tiny bit more C smarter.

**Comment by jtanx** [comment]
ping @devzer01 would you have a sample file for this?

**Comment by devzer01** [comment]
hi, very sorry wasn't able to provide a detail answer. replying from mobile, the font named WARNA can be found on this page http://www.sinhalafonts.org/fonts/13086/warna_unicode.html

lmk if you need a full report.

**Comment by frank-trampe** [comment]
@devzer01, it looks like we will need a list of operations that trigger crashes with the linked font.

**Comment by ctrlcctrlv** [comment]
This is unlikely to ever be merged as we cannot reproduce the issue it is meant to solve and the proposer has fallen silent for seven months. Therefore, I'm closing this out. If he returns with clear reproduction instructions, this can be reopened.

**Pull request closed without merging**
