### PR TITLE
Appstream and potfile update

### PR DESCRIPTION
**Pull request by jtanx**
So I took some time to actually read the specs, and came to the following conclusions:

* Installing to the appdata folder is not required: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html
  > AppStream tools scan the /usr/share/appdata/ path for legacy compatibility as well. It should not be used anymore by new software though, even on older Linux distributions (like RHEL 7 and Ubuntu 16.04 LTS) the metainfo path is well supported. Support for the legacy path might be dropped completely in future. 
* Only one xml file is needed, since we package a GUI, all we need is an appdata.xml: https://docs.fedoraproject.org/en-US/packaging-guidelines/AppData/
  > If a package contains a GUI application, then it SHOULD install a .appdata.xml file into %{_metainfodir}. Installed .appdata.xml files MUST follow the AppData specification page.

  > If a package contains an add-on for GUI application, then it SHOULD also install a .metainfo.xml file into %{_metainfodir}. Installed .metainfo.xml files MUST follow the AppStream add-ons specification.
* The strings are translatable through gettext, just pass it into xgettext

I also looked into that appstream-util, while it *is* present, it's too old on travis (xenial) so it always fails validation, even though it's perfectly valid.

### CODE REVIEW

**Comment by muelli** [comment]
have you added the POT file on purpose? it's a generated file and some projects are hesitant to add generated files.

**Comment by jtanx** [comment]
Yeah, it was deliberate, basically as part of #3814. But reconsidering, I think I'll defer adding that for now. As you said, it's kinda crap having to commit generated files.

**Comment by jtanx** [comment]
Any objections? Otherwise  I'll merge this tomorrow

**Comment by muelli** [comment]
LGTM.
Thanks for the efforts you're putting into this.

**Comment by frank-trampe** [comment]
I don't know enough to comment, but it sounds like things are all in order.

**Pull request merged**
