### PR TITLE
Fit glyphs in fontview by default, correct fitting

### LINKED ISSUE #2100: turning off fit to em, but ignoring certain large glyphs
if a font includes very large glyphs (giant radical symbols or parentheses for example), turning off fit-to em will make the glyphs too small

### PR DESCRIPTION
**Pull request by adrientetar**
Closes #2100.

r? @frank-trampe

### CODE REVIEW

**Comment by frank-trampe** [comment]
Is it wrong to perform the pixel size adjustment in the first case of SplineFontPieceMeal as the existing code does?

**Comment by adrientetar** [comment]
It is, as of this PR, done unconditionally.

**Comment by frank-trampe** [comment]
Ah. I see. In that case, the code looks good to me. Have you tested?

**Comment by adrientetar** [comment]
Yes, it works as intended.

**Comment by frank-trampe** [comment]
Merge it.

**Pull request merged**
