### PR TITLE
Add math constants tests. #2224

### PR DESCRIPTION
**Pull request by fred-wang**
@frank-trampe I'm trying again with int(rount(...)) as suggested on http://stackoverflow.com/questions/5997027/python-rounding-error-with-float-numbers

(I'll add more tests with x-height = math.AccentBaseHeight != 0 later)

### CODE REVIEW

**Comment by fred-wang** [comment]
OK,  int(rount(...)) was not a good idea. Just doing int(...) as I initially proposed made the test pass.

This second commit also adds tests involving x-height by adding a dummy glyph for 'x'.

**Comment by frank-trampe** [comment]
@fred-wang, I'd like to keep the broken commit out of the history. Would you squash the commits (via `git rebase -i`)?

**Comment by frank-trampe** [comment]
Oh. Actually, could you just make a clean branch from master, apply the change, and push that? I think that your current branch head is wrong.

**Comment by fred-wang** [comment]
Yes, that's what I'll do

**Pull request closed without merging**
