### PR TITLE
Split the editing preferences across two pages.

### LINKED ISSUE #2675: Reduce height of settings window
@typedesigner says,

> The Settings window is larger than Windows screen. You can not click OK. This is a bug that should be fixed.

- [x] Screenshot: 

screen shot 2016-04-05 at 08 01 29

- [x] The FontForge version and the operating system you're using: Any since 2014, after 58bc080
- [x] The behavior you expect to see, and the actual behavior: Expected, the Prefs window is 4:3 proportions. Actual: the Prefs window is 1:5 or so
- [x] Steps to reproduce the behavior: File, Preferences
- [x] \(optional) Possible solution: Split Editing section into 2 sections, Editing 1 / Editing 2
- [x] workaround: press 'Enter' to save preferences.

### When you open an issue for a change/improvement/feature request:
- [x] A description of the problem you're trying to solve, including _why_ you think this is a problem: netbook and Windows users typically can't see all the options and particularly can't see the OK button
- [x] If the feature changes current behavior, reasons why your solution is better: No change

### PR DESCRIPTION
**Pull request by jtanx**
Fixes the overly long preferences window. Closes #2675.
Related to #2678.

For reference:
prefs

### CODE REVIEW

**Comment by frank-trampe** [comment]
Having Editing (1) and Editing (2) looks sort of inelegant. Could we just add more submenus (like Synchronize and TT) to Editing? Perhaps a Snapping submenu?

I'm not a user experience expert. @davelab6?

**Comment by davelab6** [comment]
Wow @jtanx that was fast!! 

I think @frank-trampe has a great suggestion, perhaps the current order of items can be changed so that each page has a set of somewhat related items. Perhaps these 2?

Editing  
    Interactive  
    Interface

**Comment by jtanx** [comment]
Good point. Hmm. These are the current options:

* ItalicConstrained
* ArrowMoveSize
* ArrowAccelFactor
* DrawOpenPathsWithHighlight
* InterpolateCPsOnMotion
* SnapDistance
* SnapDistanceMeasureTool
* MeasureToolShowHorizontalVertical
* XORRubberLines
* SnapToInt
* JoinSnap
* StopAtJoin
* CopyMetaData
* UndoDepth
* UpdateFlex
* AutoKernDialog
* MetricsShiftSkip
* MetricsControlShiftSkip
* EditHandleSize
* InactiveHandleAlpha
* ShowControlPointsAlways
* ShowFillWithSpace
* OutlineThickness

Anyone want to suggest which should go where?

**Comment by jtanx** [comment]
Does this split make sense?

On default 'Editing' page:

    ItalicConstrained
    InterpolateCPsOnMotion
    SnapDistance
    SnapDistanceMeasureTool
    SnapToInt
    JoinSnap
    StopAtJoin
    CopyMetaData
    UndoDepth
    UpdateFlex
    AutoKernDialog
    MetricsShiftSkip
    MetricsControlShiftSkip

On 'Interface' (or display related?) subpage:

    ArrowMoveSize
    ArrowAccelFactor
    DrawOpenPathsWithHighlight
    MeasureToolShowHorizontalVertical
    XORRubberLines
    EditHandleSize
    InactiveHandleAlpha
    ShowControlPointsAlways
    ShowFillWithSpace
    OutlineThickness

**Comment by davelab6** [comment]
Your split looks great to me!

**Comment by jtanx** [comment]
This is how it's like now:
prefs
prefs2

**Comment by davelab6** [comment]
Love it!

No pressure, just curious, when do you think the next windows build will be
up at https://sourceforge.net/projects/fontforgebuilds/ ?:)

On 6 April 2016 at 20:03, Jeremy Tan <notifications@github.com> wrote:

> This is how it's like now:
> [image: prefs]
> <https://cloud.githubusercontent.com/assets/5137410/14336489/1c9ed6c0-fc97-11e5-893a-7c852107c699.png>
> [image: prefs2]
> <https://cloud.githubusercontent.com/assets/5137410/14336490/1d525bdc-fc97-11e5-8166-894de978156a.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/fontforge/fontforge/pull/2679#issuecomment-206626893>
>



-- 
Cheers
Dave

**Comment by jtanx** [comment]
You mean a test build for this? I could probably put one up in 30 mins

**Comment by frank-trampe** [comment]
I'm okay with all this.

**Comment by davelab6** [comment]
If you can make a new one, I'd like to add it to the binary release page
and update the main fontforge.org website so that the release is 'complete'
:)

**Comment by jtanx** [comment]
Sorry for the delayed response - got caught up in #2681. I've released a new test build which should also cover that issue as well.

**Comment by ultrasquid** [comment]
The attributes in the Accents sub-page of the Editing page should, in my
opinion, be recorded in the Font Info of the individual .sfd documents,
rather than the application prefs; since these values may change from one
font to another, yet are not carried over without manually resetting them,
as it is  in the current configuration.

It's probably something for a separate issue, which I think I may have
raised a long time ago. Might be too difficult a change to make anyway.

On Wed, Apr 6, 2016 at 11:37 PM, Jeremy Tan <notifications@github.com>
wrote:

> Sorry for the delayed response - got caught up in #2681
> <https://github.com/fontforge/fontforge/issues/2681>. I've released a new
> test build which should also cover that issue as well.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/fontforge/fontforge/pull/2679#issuecomment-206715894>
>



-- 
-- 
Jason Pagura
zimbach at gmail dot com

**Comment by davelab6** [comment]
Agreed, Jason. Please file a new issue :)

**Pull request merged**
