### PR TITLE
Fix Rectangular (calligraphic) stroke crash with simple outline #3761

### LINKED ISSUE #3761: ⟦Expand Stroke⟧ Rectangular (calligraphic) stroke crash with simple outline
* File [CalligCrash.zip](https://github.com/fontforge/fontforge/files/3361824/CalligCrash.zip)
* Element&rarr;Expand Stroke
* Use these options:
  
* Receive a crash
```txt
Program received signal SIGSEGV, Segmentation fault.
0x0000155554b335b0 in FindStrokePointsSquare (ss=0x555555a208b0, c=0x7ffffffc1710) at splinestroke.c:1417
1417                        *p = base;

(gdb) p *p
Cannot access memory at address 0x15554ea94000
(gdb) p p
$3 = (StrokePoint *) 0x15554ea94000
(gdb) p base
$4 = {sp = 0x555555a20d50, t = 0.80354058721932886, me = {x = 231.16269902458203, y = 186.36728622023111}, slope = {x = 9.9514803009173217e-05, y = -0.99999999504840209}, left = {x = 291.16269902458203, y = 246.36728622023111}, right = {x = 171.16269902458203, y = 126.36728622023111}, butt_bevel = 0, left_hidden = 0, right_hidden = 0, hide_left_if_on_edge = 0, hide_right_if_on_edge = 0, extemum = 0, circle = 0, line = 0, needs_point_left = 0, needs_point_right = 0, lt = 2 '\002', rt = 0 '\000'}


(gdb) bt
#0  0x0000155554b335b0 in FindStrokePointsSquare (ss=0x555555a208b0, c=0x7ffffffc1710) at splinestroke.c:1417
#1  0x0000155554b3fa8d in SplineSet_Stroke (ss=0x55555587ce50, c=0x7ffffffc1710, order2=0) at splinestroke.c:3698
#2  0x0000155554b3fb68 in SplineSets_Stroke (ss=0x55555587ce50, c=0x7ffffffc1710, order2=0) at splinestroke.c:3721
#3  0x0000155554b40097 in SplineSetStroke (ss=0x55555587ce50, si=0x7ffffffc18f0, order2=0) at splinestroke.c:3788
#4  0x0000155554b40d68 in FVStrokeItScript (_fv=0x555555886010, si=0x7ffffffc18f0, pointless_argument=0) at splinestroke.c:3918
#5  0x000015555522d14b in _Stroke_OK (sd=0x1555554cf3c0 <strokedlg>, isapply=0) at cvstroke.c:271
#6  0x000015555522d1fa in Stroke_OK (g=0x5555559894c0, e=0x7ffffffc2a60) at cvstroke.c:281
#7  0x0000155555018b01 in GButtonInvoked (b=0x5555559894c0, ev=0x7ffffffc2d80) at gbuttons.c:257
#8  0x0000155555019a7e in gbutton_mouse (g=0x5555559894c0, event=0x7ffffffc2d80) at gbuttons.c:485
#9  0x0000155555023faf in _GWidget_Container_eh (gw=0x55555595f150, event=0x7ffffffc2d80) at gcontainer.c:304
#10 0x0000155555025e2f in _GWidget_TopLevel_eh (gw=0x55555595f150, event=0x7ffffffc2d80) at gcontainer.c:747
#11 0x00001555550a0858 in _GGDKDraw_CallEHChecked (gw=0x55555595f150, event=0x7ffffffc2d80, eh=0x1555550254a1 <_GWidget_TopLevel_eh>) at ggdkdraw.c:323
#12 0x00001555550a3221 in _GGDKDraw_DispatchEvent (event=0x555555643b40, data=0x555555668280) at ggdkdraw.c:1219
#13 0x00001555538b7514 in  () at /usr/lib/libgdk-3.so.0
#14 0x0000155553864704 in  () at /usr/lib/libgdk-3.so.0
#15 0x0000155552afa90f in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#16 0x0000155552afc869 in  () at /usr/lib/libglib-2.0.so.0
#17 0x0000155552afc8ae in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#18 0x00001555550a5f5f in GGDKDrawProcessOneEvent (gdisp=0x555555668280) at ggdkdraw.c:2174
#19 0x00001555550293b6 in GDrawProcessOneEvent (gdisp=0x555555668280) at gdraw.c:769
#20 0x00001555552321ed in MakeStrokeDlg (cv=0x555555886010, strokeit=0x155554b40a05 <FVStrokeItScript>, si=0x0) at cvstroke.c:1013
#21 0x00001555552322e3 in FVStroke (fv=0x555555886010) at cvstroke.c:1031
#22 0x0000155555294565 in FVMenuStroke (gw=0x555555888b00, UNUSED_mi=0x55555589d180, UNUSED_e=0x0) at fontview.c:2596
#23 0x000015555504f039 in GMenuBarCheckHotkey (top=0x555555888b00, g=0x55555588a8b0, event=0x7fffffffbcf0) at gmenu.c:1966
#24 0x000015555504f267 in GMenuBarCheckKey (top=0x555555888b00, g=0x55555588a8b0, event=0x7fffffffbcf0) at gmenu.c:2015
#25 0x0000155555024e75 in _GWidget_TopLevel_Key (top=0x555555888b00, ew=0x555555888b00, event=0x7fffffffbcf0) at gcontainer.c:507
#26 0x0000155555025952 in _GWidget_TopLevel_eh (gw=0x555555888b00, event=0x7fffffffbcf0) at gcontainer.c:682
#27 0x00001555550a0858 in _GGDKDraw_CallEHChecked (gw=0x555555888b00, event=0x7fffffffbcf0, eh=0x1555550254a1 <_GWidget_TopLevel_eh>) at ggdkdraw.c:323
#28 0x00001555550a3221 in _GGDKDraw_DispatchEvent (event=0x555555643d20, data=0x555555668280) at ggdkdraw.c:1219
#29 0x00001555538b7514 in  () at /usr/lib/libgdk-3.so.0
#30 0x0000155553864704 in  () at /usr/lib/libgdk-3.so.0
#31 0x0000155552afa90f in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#32 0x0000155552afc869 in  () at /usr/lib/libglib-2.0.so.0
#33 0x0000155552afc8ae in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#34 0x00001555550a5fdb in GGDKDrawEventLoop (gdisp=0x555555668280) at ggdkdraw.c:2185
#35 0x0000155555029499 in GDrawEventLoop (gdisp=0x555555668280) at gdraw.c:789
#36 0x00001555553a975f in fontforge_main (argc=2, argv=0x7fffffffe138) at startui.c:1412
#37 0x0000555555555159 in main (argc=2, argv=0x7fffffffe138) at main.c:33

```

### PR DESCRIPTION
**Pull request by skef**
Closes #3761

### CODE REVIEW

**Comment by frank-trampe** [comment]
That was fast. What was the specific problem?

**Comment by skef** [comment]
If you are potentially about to consume `cnt` slots you need to ensure you have `cnt` available slots rather than 1 available slot. The existing within-loop memory check does the latter.

**Comment by ctrlcctrlv** [comment]
Why `+3`?

**Comment by skef** [comment]
There's the `k` `cnt` loop and then three individual `p = &c->all[c->cur++];` lines.

**Comment by skef** [comment]
(The mystery is why GW checks `c->cur+len+1+8*(cnt+2) >= c->max` in the outer loop, and why there's a separate outer loop allocation in the first place, given that both lines add the same margin. But "whatever".)

**Comment by frank-trampe** [comment]
Oh, I see. It's the thing right after that if statement and the two things after the for loop on `cnt`.

**Comment by ctrlcctrlv** [comment]
This should probably be merged just on the basis that it no longer crashes, but it's still not &ldquo;perfect&rdquo;; I get a warning.

2019-07-06-130846_462x279_scrot

**Comment by ctrlcctrlv** [comment]
2019-07-06-130953_2560x1509_scrot

**Comment by frank-trampe** [comment]
I think it's fine to merge.

**Comment by skef** [comment]
Presumably the fragments problem is one of the usual issues unrelated to memory allocation.

**Comment by ctrlcctrlv** [comment]
:+1:

**Comment by frank-trampe** [comment]
That is a really odd path defect.

**Comment by ctrlcctrlv** [comment]
It's quite a common &laquo;Expand Stroke&raquo; bug unfortunately&mdash;just search the issue tracker for &ldquo;Some fragments did not join&rdquo;.

**Comment by skef** [comment]
@frank-trampe Something is auto-closing @ctrlcctrlv's splines. When I tested I just got two gaps. That's probably what's going on with #3762 if I had to guess.

**Comment by frank-trampe** [comment]
So we have a missing join at one stage and a bad join at another. Oh the adventures that lie ahead.

**Comment by skef** [comment]
@ctrlcctrlv do you know why your splines are being closed/what is doing that? (Or to put it a different way, do you know why I was just seeing two gaps?)

**Comment by ctrlcctrlv** [comment]
I'm not sure what you mean, the image I posted is just FontForge's preview available (by default) by pressing `` ` ``

**Comment by skef** [comment]
Oh *preview* effectively auto-closes. I hadn't remembered that. 

I just went to see if that's what the deal with #3762 was and I couldn't reproduce the cutout. Strange.

**Comment by ctrlcctrlv** [comment]
Maybe a video would help ?

**Comment by skef** [comment]
Oh, I didn't look at it in depth, I may have just missed something. 

Hmm. I just tried again and I do think I matched the parameters in the dialog accurately to your image. Is there anything else to it?

**Comment by ctrlcctrlv** [comment]
We're talking about the S example, right? There's nothing else to it. Select all, right parameters, apply, get weird lines through the S.

2019-07-06-145936_2602x1681_scrot

**Comment by skef** [comment]
Ah -- your image had pen angle 0, like with this issue. 45 does the trick.

And yes, it's not just gaps but a strange artifact, so there's no relation. That is a weird one.

**Comment by ctrlcctrlv** [comment]
I'm working on this font right now since I want it to be done by the next release, so I can say, &ldquo;Hey, if you like the font in the new FontForge splash screen, check it out here&hellip;&rdquo;

2019-07-06-151035_3290x1645_scrot
2019-07-05-191644_3416x722_scrot

If you're interested in fixing these calligraphy stroke bugs I'm sure I'll find a lot more since this font is going to have &ap;250 glyphs due to all the ligatures, alternates, marks, et cetera. The question is whether anyone is going to fix them if I report them. 

I simply don't understand the math behind all this&hellip;the highest math course I ever took in school was trigonometry&hellip;so I can't fix it myself, but I can help you find them.

**Comment by skef** [comment]
I've mentioned my general worry about this area in the past -- that the algorithm may simply be a collection of heuristics that break down in some cases. If that's what's going on then mere math won't be enough. 

However, your y case from #3264 is small and easily stepped through, so I'll try to take a look at it. If that can be fixed it would be interesting to see how many of the other problems go away (if any).

**Pull request merged**
