### PR TITLE
Fix for #4770 plugin initialization failure

### LINKED ISSUE #4770: Failure of plugin initialisation prevents script from running at all
* Have setuptools missing (or temporarily move `pkg_resources` from `site-packages`
* Run `fontforge -lang=py -c 'print("hello")'
* Expect it to print `hello`
* Instead it reports:
   ```
   PythonUI_Init()
   copyUIMethodsToBaseTable()
   Core python package 'pkg_resources' not found: Cannot discover plugins
   ModuleNotFoundError: No module named 'pkg_resources'
   ```

Relates to #4761

### PR DESCRIPTION
**Pull request by skef**
Closes #4770

### CODE REVIEW

**Comment by jtanx** [comment]
I think this is fine, but one thing that I wasn't sure about when looking at this is expected behaviour from when you manually try reloading from scripting - I think now this means that no error is raised?

**Comment by skef** [comment]
This suppresses the redundant "ModuleNotFoundError: No module named 'pkg_resources'" message but not the first, so this PR shouldn't change much about the reload path.

But maybe the reload path is still wrong; can you say a bit more about the concern?

**Comment by jtanx** [comment]
Suppose someone calls `fontforge.loadPlugins()` in the case where setuptools is missing (or where plugin loading fails), what is the desired behaviour in terms of exceptions raised, if any? Or is the error message printed to the console sufficient?

**Comment by skef** [comment]
If a script is loading plugins after delaying with `-skippyplug` I would think it's hoping to have some specific plugin available, in which case it should look for it with `getPluginInfo()`. I can see some value in exposing infrastructure problems in the API but it seems marginal. Once the user tries to diagnose the problem they'll have the message.

**Review by jtanx — APPROVED** [review]

**Pull request merged**
