### PR TITLE
icons update

### PR DESCRIPTION
**Pull request by andreaslarsen**
small changes to chooser icons, new palette icons + palettemouse and paletteselectedbg

### CODE REVIEW

**Comment by andreaslarsen** [comment]
should not be be merged until some of the code is updated too - see #1827

**Comment by davelab6** [comment]
AWESOME

**Comment by davelab6** [comment]
Oh, just saw your comment.

**Comment by davelab6** [comment]
Reverted :) https://github.com/fontforge/fontforge/commits/master

**Comment by andreaslarsen** [comment]
well, they can be merged but especially the small icons look very cramped :)

**Comment by davelab6** [comment]
I reverted it so please make another Pr :)

**Comment by andreaslarsen** [comment]
ok, I've made a dark version but should we just leave them as a theme for now or?

**Comment by davelab6** [comment]
I suggest you work with @pathumego on https://github.com/fontforge/dark-theme

**Comment by andreaslarsen** [comment]
already asked him a question there ;) 

I'll prolly just add it to YosemiForge first - almost done, just need paletteselectedbg and a few other things

screen shot 2015-05-01 at 19 03 57
screen shot 2015-05-01 at 19 03 24
screen shot 2015-05-01 at 19 03 17
screen shot 2015-05-01 at 19 03 07

**Comment by davelab6** [comment]
SO HAPPY TO SEE HIS :)

The eyes on the layers palette need work :)

**Comment by andreaslarsen** [comment]
that's what I asked him about - cause it looked like he changed them somehow

**Comment by andreaslarsen** [comment]
I mocked up the entire layer palette here earlier today https://github.com/fontforge/fontforge/issues/1827#issuecomment-97728390

**Comment by pathumego** [comment]
WOW! @andreaslarsen this is much better than the half baked dark version of mine :) What I will do is just do a version of your color theme with Inkscape icon set.

**Comment by pathumego** [comment]
Adding these to theme file will do the trick for visibility icons. BUT if a user changes any settings on X Resource Editor it will disappear. I will file an issue for this.  

```
+Gdraw.GVisibilityBoxOn.Image:visiblility_on.png
+Gdraw.GVisibilityBoxOff.Image:visiblility_off.png
```

**Comment by andreaslarsen** [comment]
@pathumego Thanks! 

Inkscape icons - you mean the icons in the menu? If you ask me then they shouldn't be there in the first place - I think it's a terrible solution from a ux perspective.

I haven't spent that much time looking at the colors for control points, anchors etc...could probably be improved.

**Comment by andreaslarsen** [comment]
That works. Will update later tonight:)

screen shot 2015-05-04 at 16 58 23
screen shot 2015-05-04 at 16 57 54

**Pull request merged**
