### PR TITLE
Increase buffer size to prevent stack smashing

### PR DESCRIPTION
**Pull request by keidax**
### Motivation and Context
- [x] Why is this change required? What problem does it solve?
This fixes a crash with `*** stack smashing detected ***` when opening an SFD file.
- [ ] If it fixes an open issue, include the text `Closes #1` (where 1 would be the issue number) to your commit message.

### Types of changes
What types of changes does your code introduce? Check all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description
- [x] Describe your changes in detail.
This prevents a crash when opening an SFD file with embedded BDF properties longer than 200 chars. In my case, for example, it was a very long copyright field.

### Final checklist
Go over all the following points and check all the boxes that apply. 
If you're unsure about any of these, don't hesitate to ask. We're here to help! Various areas of the codebase have been worked on by different people in recent years, so if you are unfamiliar with the general area you're working in, please feel free to chat with people who have experience in that area. See the list [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#people-to-ask).
- [x] My code follows the code style of this project found [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#coding-style).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md) guidelines.

### CODE REVIEW

**Comment by keidax** [comment]
@skef Thanks for the write-up. I should have mentioned earlier, but that's exactly how I arrived at the value of 2000.

I'm also confused by the compilation errors.

**Comment by skef** [comment]
Attempting to rebuild with close/open ...

**Comment by jtanx** [comment]
Ahh... these arbitrary buffer sizes and code that assumes that size just feels so wrong...

**Comment by frank-trampe** [comment]
Is there a reason we couldn't have at least a macro for buffer size with limiting code in the parsing functions?

**Comment by skef** [comment]
> Is there a reason we couldn't have at least a macro for buffer size with limiting code in the parsing functions?

I'm not sure I understand this suggestion -- the `get...` functions already limit internally; the problem is coordinating the internal limit with the buffer passed as an argument. 

It would take a bit of work but the system could be replumbed with a buffer struct that includes its length. That way you could either:

1. Eliminate the `get...` limits and just use the length of the passed-in buffer structure, or
2. Keep both types of length, use the shorter one and log a warning if the length of the passed-in buffer is smaller than expected.

**Comment by frank-trampe** [comment]
I'm not suggesting that it be handed dynamically, just that we have one macro TOKMAX (or something like that) that defines the size of tok and how it is used.

**Comment by skef** [comment]
> I'm not suggesting that it be handed dynamically, just that we have one macro TOKMAX (or something like that) that defines the size of tok and how it is used.

Oh, I was assuming there was some reason for the different buffer sizes -- most likely that some are allocated in functions called recursively and 2k buffers everywhere could exceed the stack depth. If that's not a live issue then everything becomes very easy.

**Pull request merged**
