### PR TITLE
Add an option to suppress the FFTM table

### LINKED ISSUE #2389: Generate: Don't include FFTM
It is annoying to have to remove `FFTM` tables from `.ttf` fonts made by FontForge. 
- [ ] The Generate dialog should have an option to not create them
- [ ] native scripting `Generate()` should have this option
- [ ] pythong scripting `font.generate()` should have this option

### PR DESCRIPTION
**Pull request by dscorbett**
This redoes #4309 and closes #2389.

~It seems like the only problem with #4309 was in the GUI code, so let’s restore the scripting code and I can figure out the GUI crash later. (I did test the options dialog window before opening the first PR, so it may be a while before I can even reproduce the crash.)~

### Type of change
- **New feature**

### CODE REVIEW

**Comment by ctrlcctrlv** [comment]
Sorry, I'm not inclined to accept this without you exposing the option in the GUI. The GUI shouldn't be treated as second class

**Comment by jtanx** [comment]
The crash was fixed with #4317, it was just the behaviour around it being checked/unchecked not reflecting what the true state was

**Comment by skef** [comment]
@dscorbett If you add the GUI code from the last PR back into his one I'll attempt to get it working. I have medium-good grasp on what the problems were.

**Comment by skef** [comment]
I'll take a look at this this evening and if there are remaining changes to be made I'll try to do so.

**Comment by skef** [comment]
(My inability to distinguish `GGadgetSetChecked` from `GGadgetSetEnabled` led to confusion in my comments on the last PR.)

I've both reviewed this code as is and tested it and it seems fine in appearance and behavior now. I think the previous remaining issue was the now-correct flag check. @jtanx can you verify?

**Comment by jtanx** [comment]
Yeah seems fine now

**Pull request merged**
