### PR TITLE
appdata: Add common tags which are required for flatpaking the app

### PR DESCRIPTION
**Pull request by muelli**
This change aims to include some tags which are oftentimes required when
submitting an app to flathub.

Note that the `id` changed from `fontforge.desktop` to `fontforge`. This is in line with https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-id-generic although ideally the appid would be something like `io.github.Fontforge`, but let's do that in a follow-up change.

Also note that this PR only changes the appstream file. It still does not install this file during a regular make install.

### Motivation and Context

Appstream is required by more and more downstreams and this change brings a few more tags that seem to be expected.

### Types of changes
What types of changes does your code introduce? Check all the boxes that apply:
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description
- [ ] Describe your changes in detail.

### Final checklist
Go over all the following points and check all the boxes that apply. 
If you're unsure about any of these, don't hesitate to ask. We're here to help! Various areas of the codebase have been worked on by different people in recent years, so if you are unfamiliar with the general area you're working in, please feel free to chat with people who have experience in that area. See the list [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#people-to-ask).
- [X] My code follows the code style of this project found [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#coding-style).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING**](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md) guidelines.

Your pull request will be tested via Travis CI to automatically indicate that your changes do not prevent compilation. FontForge is a big program, so Travis can easily take over 20 minutes to confirm your changes are buildable. Please be patient. More details about using Travis can be found [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#using-travis-ci).  
  
If it reports back that there are problems, you can log into the Travis system and check the log report for your pull request to see what the problem was. If no error is shown, just re-run the Travis test for your pull-request (that failed) to see a fresh report since the last report may be for someone else that did a later pull request, or for mainline code. If you add new code to fix your issue/problem, then take note that you need to check the next pull request in the Travis system. Travis issue numbers are different from GitHub issue numbers.

### CODE REVIEW

**Comment by muelli** [comment]
I am proposing this app to be included in flathub: https://github.com/flathub/flathub/pull/724
It would be nice if you would help co-maintaining it there.

Also, it would be nice if the appid changes to something like `io.github.Fontforge`. I can make that change, but I thought we save this discussion for after changing the appdata file as proposed here.

**Comment by jtanx** [comment]
@muelli I'm not so familiar with this appdata file - so what are the practical differences for changing the appid, and what are the implications for doing so?

**Comment by jtanx** [comment]
@muelli I'm not so familiar with this appdata file - so what are the practical differences for changing the appid, and what are the implications for doing so?

**Comment by muelli** [comment]
>  the big the question is - do we go ahead and commit to fontforge.github.io

we can save that discussion for the next PR once this has been merged, though.

> or do we remain as fontforge.desktop

as far as I understand the [specs](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-id-generic), this is not a compliant option.



> I'm not so familiar with this appdata file
neither am I, but I try my best :)

> so what are the practical differences for changing the appid, and what are the implications for doing so?

It's all about downstreams wanting to consume your app. With a nice appid and appstream data you make their lives easier and are arguably easier exposed to users. That is to say that the development should not change at all. The appid is about the integration into the (potential) user's desktop.  As such, I consider the change as low risk. Especially in light of the currently non-compliant id.  The risk is that the desktop can't find the app's .desktop file or the icon. But given that flathub has just accepted the appstream file with the changed ID, I think it's unlikely to break anything. And downstreams will complain if something is not good enough.

**Comment by jtanx** [comment]
Nice, yeah sounds good to me, let's change it

**Comment by muelli** [comment]
cool. I've created a follow-up PR: https://github.com/fontforge/fontforge/pull/3368

**Pull request merged**
