### PR TITLE
SplashScreen delay in seconds, and DefaultDirectory for fresh _FVMenuOpen's

### PR DESCRIPTION
**Pull request by happyrobotstudio**
- Utilising an optional 'DefaultDirectory' pref as the start folder for an empty call to _FVMenuOpen 
- Using SplashSeconds pref as a pr_int, indicating the hide delay in seconds (default 7 seconds)

I enjoy these two tweaks personally

1. - FontForge splash 'boots' as fast as I desire
2. - FontForge starts in the location I desire

Up to you for master branch

Cheers,

- Daniel

### CODE REVIEW

**Comment by jtanx** [comment]
I mentioned this in the previous PR, but I still don't see the point in making the splash timeout configurable. If you don't want the splash then pass `--nosplash` as a cli argument.

**Comment by ctrlcctrlv** [comment]
This was already rejected in #3799. 

The default directory option is not really necessary, FontForge keeps the working directory in mind and already defaults `DefaultDir` to `GFileGetHomeDocumentsDir()`.

For those reasons, plus @jtanx's commentary, I'm closing this.

**Comment by happyrobotstudio** [comment]
> This was already rejected in #3799.
> 
> The default directory option is not really necessary, FontForge keeps the working directory in mind and already defaults `DefaultDir` to `GFileGetHomeDocumentsDir()`.
> 
> For those reasons, plus @jtanx's commentary, I'm closing this.

Between restarts though? Defaulting back to homedir instead of my desired fonts sir was taking literal hours our of my workflow ;P

**Comment by happyrobotstudio** [comment]
> I mentioned this in the previous PR, but I still don't see the point in making the splash timeout configurable. If you don't want t

> I mentioned this in the previous PR, but I still don't see the point in making the splash timeout configurable. If you don't want the splash then pass `--nosplash` as a cli argument.

If there is a tickbox there anyway, making it more configurable would not detract from the user experience? The whole splash screen is clunky .. it's so tied into functionality ...

**Comment by frank-trampe** [comment]
I have no objection to this new approach (not adding an extra option), but I still do not see a case in which anybody would take advantage of it.

**Comment by happyrobotstudio** [comment]
> I have no objection to this new approach (not adding an extra option), but I still do not see a case in which anybody would take advantage of it.

Sure, just a personal preference ... makes the question three fold "Do i want this thing, Do I not want this thing, Do i want this thing .. shorter"

There are other questions that arise, coming from a UI background:

"What is this thing", "Is this a splash screen?" "Why does it not act like a traditional splash screen" 

But settling for the "Do i want this thing .. shorter" approach .. seemed a good use of an existant pref area onscreen.

This change isnt so important .. but .. i personally like the splash, but feel obligated to turn it off ... if ... it is going to run for a full 7 seconds

**Comment by happyrobotstudio** [comment]
> > This was already rejected in #3799.
> > The default directory option is not really necessary, FontForge keeps the working directory in mind and already defaults `DefaultDir` to `GFileGetHomeDocumentsDir()`.
> > For those reasons, plus @jtanx's commentary, I'm closing this.
> 
> Between restarts though? Defaulting back to homedir instead of my desired fonts dir was taking literal hours out of my workflow ;P

Yep, this one change improves the experience 10-fold ..

Defaulting to homedir each fresh start is great and all ..

But if the intention is user focused, we'd be going for something a little nicer

Either way, time is being saved over here =P

Lost while arguing the point though ..

**Comment by frank-trampe** [comment]
@happyrobotstudio, we're always happy to have help improving FontForge, but if you want to contribute, there are a few important guidelines.
* If you wish to argue for acceptance of a rejected pull request, don't simply open another one. You can post messages on the old one, or you can refer to the old one on the mailing list. Managing the issue tracker is a lot of work, and those of us who triage issues don't like to see people create unnecessary work or seemingly to bury the result of a prior discussion.
* Do not combine such totally unrelated changes in one pull request. It makes any debate very confused since it is confined to one thread.
* Try to keep the history of your pull request branch simple. This one somehow has 21 (!) commits. We would normally expect there to be one commit for each actual change and no other commits in the pull request.

The splash screen change may be worthy of consideration, but approaching it from the wrong direction just turns people against it.

**Comment by happyrobotstudio** [comment]
Righto ..

I'll keep my focus on my own branch from now on, nit picking and ingratuitousness like this is reserved for the workplace.

Happy fonting!

**Pull request closed without merging**
