### PR TITLE
Check for a non-null familyname before outputting to svg.

### LINKED ISSUE #3115: Fontforge (cli) crashes when converting Noto CJK fonts to SVG
I converted many fonts successfully to SVG format with Fontforge, but the Noto CJK fonts defy this endeavor. There's even a regression compared to Fontforge 20120731.

**Environment:** Ubuntu 16.04, Fontforge:

```
$ fontforge --version
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 01:51 UTC 13-Oct-2016-ML-D.
 Based on source from git with hash: fe1d84b7d05178885a36ba0adce0559a82a493d5
no xdefs_filename!
TESTING: getPixmapDir:/usr/share/fontforge/pixmaps
TESTING: getShareDir:/usr/share/fontforge
TESTING: GResourceProgramDir:/usr/bin
trying default theme:/usr/share/fontforge/pixmaps/resources
fontforge 01:51 UTC 13-Oct-2016
libfontforge 20161013
```

**Script:**

```
#!/usr/bin/env fontforge
# convert a font to an SVG font with the same filename
Open($1);
Reencode("unicode");
Generate($1:r + ".svg");
Quit(0);
```

**Fonts:**

All the ones suffixed with `-Regular` from here: https://github.com/googlei18n/noto-cjk. I tested both .otf and .ttc.

**Call:**

    $ fontforge -lang=ff -script ttf_to_svg.ff NotoSansJP-Regular.otf

**Result:**

```
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 01:51 UTC 13-Oct-2016-ML-D.
 Based on source from git with hash: fe1d84b7d05178885a36ba0adce0559a82a493d5
The following table(s) in the font have been ignored by FontForge
  Ignoring 'DSIG' digital signature table
  Ignoring 'VORG' vertical origin table
Warning: Mac string is a subset of the Windows string in the 'name' table
  for the Designer string in the English (US) language.
Warning: Mac string is a subset of the Windows string in the 'name' table
  for the Descriptor string in the English (US) language.
No glyph with unicode U+04e0d in font
No glyph with unicode U+04e32 in font
No glyph with unicode U+04e39 in font
No glyph with unicode U+04e82 in font
No glyph with unicode U+04e86 in font
No glyph with unicode U+04eae in font
No glyph with unicode U+04ec0 in font
...(and so on)

Segmentation fault.
```

The SVG file is created but remains empty.

The older Fontforge 20120731 brings the same warnings, but doesn't segfault and creates a small SVG font file with only some fullwidth characters U+FF22-U+FF5A.

**Expected behavior:** Convert the OTF file into a SVG font file.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

### PR DESCRIPTION
**Pull request by frank-trampe**
This closes #3115.

### CODE REVIEW

**Comment by frank-trampe** [comment]
@jtanx, take a look.

**Comment by jtanx** [comment]
It seems like it would prevent a crash, but wouldn't that generate an invalid SVG font, since it has no `font-family`? Perhaps it should fall back to some other name instead?

**Comment by frank-trampe** [comment]
I think that it gets confusing to export files with values different from those in the source file. It's definitely necessary sometimes, but I don't think there's anything wrong with the export result from an incomplete font that fails validation being invalid.

**Comment by jtanx** [comment]
Ok then perhaps it should be a bit more vocal about it knowingly generating an invalid file

**Comment by jtanx** [comment]
lgtm

**Pull request merged**
