### PR TITLE
Don't add leading control points twice when reading glif

### LINKED ISSUE #4539: Another UFO glyph can't be roundtripped, this time a quadratic one
Arch Linux, fc1970174ba9e965bef9b676ee2afd679079a34e

I haven't yet solved #4327 on my own, and now have an example of a quadratic glyph that FontForge also can't generate a correct UFO of. :frowning: 

Non-FontForge programs also have problems with this UFO. For example `fontmake` can't convert it (crashes).

# SFD

2020-12-17-210237_1506x1392_scrot

# Conversion

```python3
import fontforge

f = fontforge.open("Issue4327Part2.sfd")
f.generate("{}.ufo".format(f.fontname))
```

```
$ fontforge Issue4327-Part2.ufo
```

# UFO

2020-12-17-211231_2560x1392_scrot

# Files

[Issue4327Part2.zip](https://github.com/fontforge/fontforge/files/5713253/Issue4327Part2.zip)

### PR DESCRIPTION
**Pull request by skef**
Closes #4539

### CODE REVIEW

**Comment by frank-trampe** [comment]
I'm having trouble thinking through this one without tests. Would it perhaps be more intuitive simply to expend the cached points by setting `precnt` to zero?

**Comment by skef** [comment]
I guess you could *also* do that. But at least to the extent I've looked at it it does seem like there's a "do this if first, do the other if not first" branch here.

**Comment by skef** [comment]
The code around line 3026 corresponds to the code around line 2913, you just need to make sure the right one runs and the wrong one doesn't.

**Comment by frank-trampe** [comment]
Oh, I see.

**Review by frank-trampe — APPROVED** [review]

**Pull request merged**
