### PR TITLE
Potential further release changes 

### PR DESCRIPTION
**Pull request by skef**
1. Add tests to dist in tests/Makefile.am

### CODE REVIEW

**Comment by skef** [comment]
I'm not the right judge of how important the two missing tests are. I have doubts that `testsuite` will function well outside of the `make check` "environment" but I could easily be mistaken.

**Comment by JoesCat** [comment]
low/no priority, don't think they are needed,
but mentioning in case you're modifying these Makefile.am:
2 more EXTRA_DIST, each makefile.am
diff -r fontforge/ ../ft/fontforge-20190317/fontforge/
Only in fontforge/: libstamp.c
Only in fontforge/: stamper.c

**Comment by jtanx** [comment]
pretty sure libstamper and stamper.c can both be nixed, we don't even use that any more.

**Comment by JoesCat** [comment]
> I'm not the right judge of how important the two missing tests are. I have doubts that testsuite will function well outside of the make check "environment" but I could easily be mistaken.

just focus on the github files that don't appear in the dist tarball.
testsuite is built during make dist process, so you don't add it in the EXTRA_DIST (leave it out)

**Comment by skef** [comment]
Ha! From stamper.c:
```
/*
 * This program is used to create a 'release date' time stamp when it is time for the
 * next fontforge release build. See fontforge/GNUmakefile.in
 */
```
Old build infrastructure ...

**Comment by JoesCat** [comment]
3 files missed in pycontrib Makefile.am
diff -r pycontrib/ ../ft/fontforge-20190317/pycontrib/
Only in pycontrib/: FontCompare
Only in pycontrib/: svg2glyph
Only in pycontrib/: svg2sfd.py

**Comment by frank-trampe** [comment]
There is nothing more George Williams than writing a timestamp generator in C.

**Comment by JoesCat** [comment]
3 more missed files in Packaging
diff -r Packaging/ ../ft/fontforge-20190317/Packaging/
Only in Packaging/: AppDir
Only in Packaging/: debian
Only in Packaging/: redhat

**Comment by skef** [comment]
I'm pretty sure those aren't in `pycontrib/Makefile.am` because they're not appropriate to be installed. The usual way of "retiring" stuff there is to just remove it from the Makefile.

**Comment by frank-trampe** [comment]
Yes. It's less of a thing now, but, back when we had multiple active forks going, it was very important to keep deviations as small as possible, and that was a good way to do it.

**Comment by JoesCat** [comment]
This is where I leave-off, got other things happening.
Good luck with this. Seems it may be "just in time" for St Patrick's & green beer - LOL

**Comment by frank-trampe** [comment]
@JoesCat, it's a good thing that we don't theme our releases since I'd probably be forced to do some sort of doodle with Saint Patrick and letters made of snakes.

**Comment by jtanx** [comment]
Let's merge this in before this gets stale

**Comment by frank-trampe** [comment]
Fine with me. I got distracted by the discussion.

**Pull request merged**
