### PR TITLE
Allow the spacebar to enable preview mode.

### PR DESCRIPTION
**Pull request by jtanx**
Related issues: #2143.

A new preference, 'ShowFillWithSpace' allows this behaviour to be toggled by
the user. It is enabled by default.

I will need to update #2375 if this gets merged first or vice versa.

### CODE REVIEW

**Comment by frank-trampe** [comment]
I thought that there was a different keystroke for this already.

**Comment by jtanx** [comment]
Yes, the backtick (`), but @davelab6 suggested that it would be good for this to also happen when the spacebar is pressed, as described in #2143.

**Comment by davelab6** [comment]
The backtick is often not a key on european keyboards, and was done to be compatible with FontLab; but now Glyphs is the most popular editor and sensibly uses the space key for this, so we should update to use both.

**Comment by jtanx** [comment]
I have rebased the commit.

**Comment by frank-trampe** [comment]
Looks good.

**Pull request merged**
