### PR TITLE
Temporarily standardize overlap removal for path stroking.

### PR DESCRIPTION
**Pull request by frank-trampe**
Temporarily use the main overlap removal tool in place of the stroke-specific backtrack/overlap function when expanding strokes.

This supersedes #2874, which had problems.

See #2840.

### CODE REVIEW

**Comment by frank-trampe** [comment]
@mskala, see here.

**Comment by mskala** [comment]
I'll take a look when I can, but my availability, computing resources, and network access will be very limited for the next month or so - I'm preparing to leave Denmark permanently tomorrow, and then will be on the road without a fixed address until November at the earliest.  My main computer is already packed up - I'm typing this on a netbook.

My first thought, though, is that I didn't even realize we had a separate overlap remover for the stroke feature, and it certainly makes sense that it'd be nicer to have just one used in two places, with effort concentrating on making it work well, than to have two separate bug magnets.

**Comment by jtanx** [comment]
@frank-trampe, as requested, I've pushed only the tolerance adjustment commit.

**Comment by jtanx** [comment]
I tried the full [bad icon](https://github.com/fontforge/fontforge/files/473448/bad-icon.svg.zip) from #2832, and it imports 'ok' (albeit throwing up a bunch of fragments did not join errors), but when you try to open the charview, it segfaults. Luckily it doesn't appear to segfault as a result of the splinestroke code, but it's segfaulting in Cairo during the expose call. Might be something to do with the number of points generated by the import. Anyhow, that's probably a separate issue altogether.

The main thing is that it no longer hangs on import which was the primary concern from #2832.

Backtrace

~~~~
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff42deec8 in ?? () from /usr/lib/x86_64-linux-gnu/libcairo.so.2
(gdb) bt
#0  0x00007ffff42deec8 in ?? () from /usr/lib/x86_64-linux-gnu/libcairo.so.2
#1  0x00007ffff42a957d in ?? () from /usr/lib/x86_64-linux-gnu/libcairo.so.2
#2  0x00007ffff430920e in ?? () from /usr/lib/x86_64-linux-gnu/libcairo.so.2
#3  0x00007ffff4309829 in ?? () from /usr/lib/x86_64-linux-gnu/libcairo.so.2
#4  0x00007ffff430a0e9 in ?? () from /usr/lib/x86_64-linux-gnu/libcairo.so.2
#5  0x00007ffff42ab45f in ?? () from /usr/lib/x86_64-linux-gnu/libcairo.so.2
#6  0x00007ffff43254a9 in ?? () from /usr/lib/x86_64-linux-gnu/libcairo.so.2
#7  0x00007ffff42f66f6 in ?? () from /usr/lib/x86_64-linux-gnu/libcairo.so.2
#8  0x00007ffff42b3cb2 in ?? () from /usr/lib/x86_64-linux-gnu/libcairo.so.2
#9  0x00007ffff42acfe9 in ?? () from /usr/lib/x86_64-linux-gnu/libcairo.so.2
#10 0x00007ffff42a5df5 in cairo_stroke ()
   from /usr/lib/x86_64-linux-gnu/libcairo.so.2
#11 0x00007ffff65d9dc9 in _GXCDraw_PathStroke (w=0x80c720, col=544239728)
    at gxcdraw.c:395
#12 0x00007ffff65cfe77 in GXDrawPathStroke (w=0x80c720, col=544239728)
    at gxdraw.c:2134
#13 0x00007ffff655f811 in GDrawPathStroke (w=0x80c720, col=544239728)
    at gdraw.c:650
#14 0x00007ffff785a37d in CVDrawSplineSetOutlineOnly (cv=0x95ee80, 
    pixmap=0x80c720, set=0x8bd240, fg=544239728, dopoints=1, 
    clip=0x7fffffffb980, strokeFillMode=sfm_stroke_trans) at charview.c:1593
#15 0x00007ffff785a91a in CVDrawSplineSetSpecialized (cv=0x95ee80, 
    pixmap=0x80c720, set=0x88c920, fg=0, dopoints=1, clip=0x7fffffffb980, 
    strokeFillMode=sfm_stroke, AlphaChannelOverride=0) at charview.c:1717
#16 0x00007ffff785ab9f in CVDrawLayerSplineSet (cv=0x95ee80, pixmap=0x80c720, 
    layer=0x88ddf8, fg=0, dopoints=1, clip=0x7fffffffb980, 
    strokeFillMode=sfm_stroke) at charview.c:1755
#17 0x00007ffff7863033 in CVExpose (cv=0x95ee80, pixmap=0x80c720, 
    event=0x7fffffffbda0) at charview.c:3020
#18 0x00007ffff786e962 in v_e_h (gw=0x80c720, event=0x7fffffffbda0)
    at charview.c:5732
#19 0x00007ffff655ad26 in _GWidget_Container_eh (gw=0x757100, 
    event=0x7fffffffbda0) at gcontainer.c:279
#20 0x00007ffff65d37ac in dispatchEvent (gdisp=0x6b38e0, event=0x7fffffffbe60)
...
~~~~

**Comment by frank-trampe** [comment]
Eww. That bad icon is really messed up. Try using the union operation in Inkscape.

**Comment by frank-trampe** [comment]
It is not crashing for me, which suggests an alignment-sensitive issue. Could you try tracking it down? Maybe try the duplicate-finder that I wrote before and after overlap removal?

**Comment by jtanx** [comment]
It might just be down to the version of Cairo that I have, since it is segfaulting in Cairo itself. I wouldn't worry about it too much, since I think that the use case from #2832 was from an automated script (perhaps handling some automated online conversion? I don't know).

If you want, I might get a chance to look into this tomorrow, otherwise it's going to be the weekend.

**Comment by frank-trampe** [comment]
Whenever you get a chance. It's not a blocking issue, but I'd love to get it fixed before we forget about it.

**Comment by jtanx** [comment]
I've tested on Windows and it doesn't crash. It runs very slow though. I'll put the crash down to a Cairo bug. FWIW the crash happened on Debian, with Cairo version 1.14.0-2.1+deb8u1. Windows is built against Cairo 1.15.2.

**Pull request merged**
