### PR TITLE
Fix build out of source tree: uthash problem

### PR DESCRIPTION
**Pull request by hedrok**
Provide a general summary of your changes in the **Title** above.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### Motivation and Context
- [x] Why is this change required? What problem does it solve?
**It solves problem when compiling out of source tree:**
./bootstrap
cd ..;
mkdir build;
cd build;
../fontforge/configure --prefix=/usr;
make

I get error:
  CC       libfontforge_la-featurefile.lo
In file included from ../../t/fontforge/featurefile.c:2114:0:
../../t/fontforge/glif_name_hash.h:8:20: fatal error: uthash.h: No such file or directory
 #include "uthash.h"
                    ^
compilation terminated.
Makefile:1829: recipe for target 'libfontforge_la-featurefile.lo' failed

- [ ] If it fixes an open issue, include the text `Closes #1` (where 1 would be the issue number) to your commit message.

### Types of changes
What types of changes does your code introduce? Check all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description
- [x] Describe your changes in detail.
**Very simple change: top_srcdir -> top_builddir in Makefile.am for uthash. Because there is no uthash in src, it is cloned to build directory.**

### Final checklist
Go over all the following points and check all the boxes that apply. 
If you're unsure about any of these, don't hesitate to ask. We're here to help! Various areas of the codebase have been worked on by different people in recent years, so if you are unfamiliar with the general area you're working in, please feel free to chat with people who have experience in that area. See the list [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#people-to-ask).
- [x] My code follows the code style of this project found [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#coding-style).
**Changed Makefile.am only. So no problems with coding style :)**

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md) guidelines.
**Well, I hope I've read enough for this small fix...**

Your pull request will be tested via Travis CI to automatically indicate that your changes do not prevent compilation. FontForge is a big program, so Travis can easily take over 20 minutes to confirm your changes are buildable. Please be patient. More details about using Travis can be found [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#using-travis-ci).  
  
If it reports back that there are problems, you can log into the Travis system and check the log report for your pull request to see what the problem was. If no error is shown, just re-run the Travis test for your pull-request (that failed) to see a fresh report since the last report may be for someone else that did a later pull request, or for mainline code. If you add new code to fix your issue/problem, then take note that you need to check the next pull request in the Travis system. Travis issue numbers are different from GitHub issue numbers.

### CODE REVIEW

**Comment by hedrok** [comment]
Ok, on Travis CI after my initial commit linux build failed. I fixed it with adding original $(top_srcdir)/uthash/src though I don't know why it is needed.
I don't think problem on OSX is caused by my changes, is it?..

**Comment by gioele** [comment]
hi @hedrok, could you please rebase this PR on top of the current master? It will solve the issue with MacOS on Travis.

**Comment by hedrok** [comment]
Of course, but I'll be able to do it in 7-10 hours only.

**Comment by hedrok** [comment]
Done.

**Comment by JoesCat** [comment]
Hi @hedrok,
Some editors seem to try use TAB==2 or 4, but can you use TAB==8 spacing when possible. It's old-school but basically fairly common, and I think you understand best when dabbling with assembler ;-)
I think this shows it easier (looking at Makefile.am):
https://raw.githubusercontent.com/hedrok/fontforge/9e3ff6e54b85c21727915d9771be20d01c8b6b6c/fontforge/Makefile.am

**Comment by hedrok** [comment]
Hi @JoesCat,
I had this problem in my first commit, but I've noticed it and fixed it:
https://raw.githubusercontent.com/hedrok/fontforge/dcd149af78003158c72ffcc334694f82d659c91a/fontforge/Makefile.am

This PR has two commits: 9e3ff6e and dcd149a
Please check if everything is all right after second commit or I still missed something...
I can merge them to one - I just wasn't sure that I should rewrite history after PR.

**Comment by JoesCat** [comment]
I stopped at the first commit.
I see what you mean on commit2.
If you want to keep them separate, you can try something like this:
cp -pR master master_copy
delete your local computer git branch of this commit
create a new local git branch on your computer of this commit with exact same branch title you used above (github will pickup that this is the "same" PR when you push to your origin later).
cp master_copy/fontforge/Makefile.am master/fontforge/
edit Makefile.am (as mentioned above).
commit makefile patch (use same subject line, but you can edit comments differently if you want)
cp master_copy/travis fix to master/
commit travis fix (use same or different subject line, same or different comments)
git force push this replacement branch to origin
...at this point, you'll see you're still in the same PR, but the file(s) are updated.
delete your master_copy if you don't want to keep it.

github is fairly flexible when you do stuff like this (above), and there are various ways to put updated results into this PR. Some methods better than others, and I thought it worth mentioning this if you want to preserve separate commits (before #2952 gets merged into the main fontforge).

**Comment by hedrok** [comment]
How complicated... I prefer using git tools, so something like the following seems easier to me:
git rebase -i origin/master
Replace 'pick' before first commit with 'edit'
Interactive rebase stops at first commit.
Edit Makefile.am
git add fontforge/Makefile.am
git commit --amend
git rebase --continue
Resolve conflict
git add fontforge/Makefile.am
git rebase --continue

But maybe that seems easier to me only :)

Anyway, I've just merged them to one commit, there is no real value in this history.

**Comment by JoesCat** [comment]
If you have the tools - great - thanks for explaining.
Merged - Thanks!

**Comment by hedrok** [comment]
Thank you too :)

**Pull request merged**
