### PR TITLE
Disable slow P. D. F. font name scanning.

### PR DESCRIPTION
**Pull request by frank-trampe**
This addresses part of #1640.

### CODE REVIEW

**Comment by frank-trampe** [comment]
This tests correctly for me. @adrientetar?

**Comment by jtanx** [comment]
I just tested it and it seems to work for me.

**Comment by adrientetar** [comment]
Can you squash commits?

**Comment by jtanx** [comment]
Done

**Comment by jtanx** [comment]
Issue #997 is happening again...

**Pull request merged**
