### PR TITLE
Updates to the italian localization

### PR DESCRIPTION
**Pull request by DevEraclito**
Provide a general summary of your changes in the **Title** above.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### Motivation and Context
- [x] Why is this change required? What problem does it solve?
 There were some missing translations i've added, and some mistranslations i tried to fix. If there're other italian localizers around, i'd be happy to discuss about the changes.
I've tried another pull today, but my previous version contained compilation errors. I then tried to fix them all. Then it happened again. As you can figure, i'm not a programmer, i'm more on the artistic side of the userbase.

### CODE REVIEW

**Comment by JoesCat** [comment]
Impressive.
I'm currently looking at compacting your translation into one pull request.
There's a couple of quirks that need editing/fixing (what I'm seeing mostly is trailing carriage returns in the lines, these need to come out - I'm doing this now).

In the meantime, would you also be interested in also modifying a file in directory desktop, called:
fontforge.appdata.xml  (easy - approx a few sentences).
This can be modified using a plain text editor such as gedit, kwrite or notepad (however it does contain UTF8 characters, so you will need a little caution with notepad), or if you want, just look at the info presented, and write the text here, then I'll merge it into the file.

If you want to add your email to the git patches, just add one more patch to your set of patches (example, your name in the it.po file is fine).

**Comment by JoesCat** [comment]
>There's a couple of quirks that need editing/fixing (what I'm seeing mostly is trailing carriage returns in the lines, these need to come out - I'm doing this now).

My error, looks ok, but will wait for your reply before merging (in case you are adding anything further ATM).

**Comment by DevEraclito** [comment]
Thank you! Like i said, I'm no programmer, i'm sorry i had to submit so many revisions before getting a working version of the file. There's any way to merge them in a single one? I don't want to clog the file history, if that's possible.
About the editing, i'm currently using Notepad++, when i started i used ConTEXT but it had troubles with UTF8 (so i had to manually revert all the special characters, using the provided file).
I've added the italian text in the bottom of fontforge.appdata.xml (still taking two versions, since i forgot to specify it was "it" in the last row).

I'd like to keep locaizing the main file, but i'm not sure if i'll be able to get on them in the incoming days.
Also... May i ask more info about the email thing? What should i do?

**Comment by JoesCat** [comment]
Thanks for the attention to fontforge.appdata.xml, at the moment, this would all go into a squash commit (merges all the commits into one commit), however, as you're interested in adding your email to the git commit, this can be done in one of 3 ways, using notepad++, edit the comment with your name on file it.po, and push the commit, or, edit your user settings, and I grab it from your home page on github, send me an email to digital@joescat.com (last method least preferred as anyone can send an email).
...then, I'll commit the merge locally and push to master.

Understandable about ConTEXT, not all tools are up to date. Notepad++ is a good choice.

Nothing to be sorry about, we all have our talents, and can't be an expert at everything.

**Comment by DevEraclito** [comment]
I've added the email to it.po, i hope all my edits don't overload the software checker :P
I'll leave the merge up to you, thanks for your time and your patience!

**Comment by JoesCat** [comment]
Corrections added, you're also named in the git commit.
In terms of how git works, this becomes an orphan branch, so you'll need to update your github copy after we get the other commit merged (if you want to make further updates inline with upstream).
Had a little trouble with git committer, however you are the authour (in the commit).

I'm not certain, but I'm going to guess, you might manage to convince github to import your hombase settings into a future patch, so you might want to add your email to your github page, commit, create a pull request, then remove your email address from your homepage (I'm just saying this because I note that github imports my github_homepage_email if I merge patches via github and I note it is slightly different than my command-line settings). #3339 should close this PR

**Pull request closed without merging**
