### PR TITLE
Expand Stroke troubleshooting documentation, with known problems

### LINKED ISSUE #4073: Stroking simple spline (three points) results in strange sharp edges at endpoints
2019-12-20-170011_2786x1517_scrot
2019-12-20-170106_2786x1517_scrot

In the grand scheme of things, this problem is small;
I'm hesitant to even call it a bug at all.
But the stroker is new, and the testers are few,
So report it I must, for to do so is just.

# Required settings Ⓐ

2019-12-20-170559_1088x1147_scrot

Note: Remove Overlap setting doesn't matter.

# Required settings Ⓑ

Is this two issues in one?
The contour is the same,
But the results more seriously wrong.
I feel they're related.

2019-12-20-171017_1088x1147_scrot
2019-12-20-171041_1768x1517_scrot

# File

[uni0315.sfd](https://github.com/fontforge/fontforge/files/3987555/uni0315.zip)

### PR DESCRIPTION
**Pull request by skef**
Issue #4073 documented known limitations of the stroking algorithm. This PR adds documentation about those problems along with some more general troubleshooting strategy.

Closes #4073

### CODE REVIEW

**Comment by ctrlcctrlv** [comment]
(I merged this so quickly as it's a documentation-only change, and the new troubleshooting section matches my experience.)

**Comment by skef** [comment]
@ctrlcctrlv Parts of it are straight-out descriptions of your experience ...

**Comment by ctrlcctrlv** [comment]
@skef Can I ask you in future to configure Git to write out an email known to GitHub, or to add the email you use to GitHub? That way you get proper attribution for your commits, and it looks better in the listing.

**Comment by skef** [comment]
I will try ...

**Pull request merged**
