### PR TITLE
Switch to use Sphinx for documentation

### LINKED ISSUE #4113: Sphinx Documentation
So I'm basically going to bite the bullet and convert all the HTML docs under `doc` to Sphinx documentation ( -> convert to reStructuredText).

Raise any thoughts/concerns now, otherwise I'll just do it, assuming I haven't lost interest by the end.

### LINKED ISSUE #4131: Move Python `font.genericGlyphChange` description to `selection` sub-section
There are a few open issues referencing the lack of a Python interface for "Change Glyph". These stem from:

1. The somewhat different name (`genericGlyphChange`) of the python method (which traces to the C function names)
2. The lack of a glyph-level equivalent
3. The fact that `genericGlyphChange()` is documented in the wrong section of `python.html`. It is, sensibly, a selection-based interface but is listed among the regular `font` methods. 

I've been meaning to fix 2, which should actually be pretty easy: just break out the parameter processing into a separate method called in two places. (There's already a C-level `CVGenericChange()` to match `FVGenericChange()`. #2925 represents that work. 1 is easy enough to document around. I'm filing this to represent 3. Normally I would just go in and fix it but with #4113 outstanding I suspect that parallel merges are likely counterproductive right now.

In short, the task is to move the description in the `python.html` to the correct location. 

Happily the interface itself is keyword based and quite appropriate as-is. And anyone wanting to alter an individual glyph can currently just select it beforehand. It's a shame few people are aware of it.

### PR DESCRIPTION
**Pull request by jtanx**
This replaces the English documentation with Sphinx; documentation is written in reStructuredText. I've copied the old Japanese/German docs verbatim (although I find this questionable in usefulness).

Live demo: https://jtanx.github.io/ffdocs
Wiki page: https://github.com/fontforge/fontforge/wiki/FontForge-and-Sphinx

For the most part, this is bog-standard Sphinx. The two extensions are:

* Addition of a FontForge native scripting domain, which allows you to (a) define native functions:
   
   ```rst
    .. function:: GetLookups()
      
      <description>
   ```

   and (b) refer to them, e.g.

   ```rst
    blah blah :ff:func:`GetLookups()` blah 
   ```
* Added a directive (`flex-grid`), which allows you to create an arbitrary flexbox grid for layout purposes:

   ```rst
   .. flex-grid::
     * - .. figure:: /images/PathToBind.png

            path
       - .. figure:: /images/TextBoundUnitaryGlyph.png

            Glyphs bound as a unit
       - .. figure:: /images/TextBoundDistortedGlyphs.png

            Glyphs distorted by binding
   ```

   `flex-grid`s replace the use of tables where tables were being used for layout. They don't replace tables where they were used for tabular data.

   The flex grid is also (somewhat) reactive, in that it will collapse the grid at narrower widths (i.e. for mobile devices), e.g.:

   image

   Becomes

   image

----------

I did not convert the following documents, either because they were completely out of date, or covered elsewhere (e.g. on the wiki or the existing website):

```
changelog.html
editexample-fr.html
faqFrame.html
faqFS.html
future.html
GlossaryFrame.html
GlossaryFS.html
index.html
IndexFrame.html
IndexFS.html
mac-install.html
mad.html
ms-install.html
nix-install.html
nvd.html
oldchangelog.html
pfaeditchangelog.html
realindex.html
running.html
source-build.html
src.html
uninstall.html
views.html
vms-install.html
wacom.html
```

### Type of change
- **New feature**
- **Breaking change**

Closes #4113, closes #4131.

### CODE REVIEW

**Comment by jtanx** [comment]
@skef you mentioned in #4113 that you could generate your svgs with the styles inline? The svgs are all displayed using the `` tag and not `<object>` tags, which means that it has to be self-contained.

External stylesheets are also not supported by pretty much anything other than browsers (even Inkscape apparently doesn't support it), so I think it's just easier to handle if they're defined inline.  (I got around it by copy pasting the css into each svg, getting inkscape to convert those to pdfs, then converting back to svgs, and scouring the result.)

**Comment by skef** [comment]
As I indicated before I'm not contributing to this particular sub-project.

**Comment by jtanx** [comment]
Ok...

**Comment by skef** [comment]
On the level of overall repository coherence, no systemic rename of the documentation files should be merged without a PR/plan for the `help()` function:
```
./cvstroke.c:   help("elementmenu.html#Expand");
./cvstroke.c:                help("elementmenu.html#Expand");
./cvstroke.c:       help("multilayer.html#Layer");
./math.c:           help("math.html#GlyphConstruction");
./math.c:           help("math.html");
./kernclass.c:      help(kcd->iskernpair ?  "metricsview.html#kernpair":
./kernclass.c:                              "metricsview.html#kernclass");
./kernclass.c:      help("metricsview.html#kernclass");
./savefontdlg.c:            help("generate.html#Options");
./savefontdlg.c:            help("generate.html");
./fontview.c:    help("fontview.html");
./fontview.c:    help("overview.html");
./fontview.c:    help("IndexFS.html");
./fontview.c:    help("license.html");
./combinations.c:           help("kernpairs.html");
./combinations.c:           help("kernpairs.html");
./basedlg.c:        help("baseline.html");
./basedlg.c:        help("baseline.html");
./macencui.c:       help("prefs.html#Features");
./macencui.c:       help("prefs.html#Settings");
./macencui.c:       help("prefs.html#Features");
./autowidth2dlg.c:          help("autowidth.html#AutoWidth");
./displayfonts.c:           help("print.html");
./displayfonts.c:           help("display.html");
./startnoui.c:    /*help("overview.html");*/
./bitmapview.c:    help("bitmapview.html");
./contextchain.c:           help("contextchain.html");
./contextchain.c:           help("contextchain.html");
./scriptingdlg.c:           help("scripting.html");
./fontinfo.c:   help("fontinfo.html");
./fontinfo.c:       help("fontinfo.html#Lookups");
./startui.c:    help("overview.html");
./scstylesui.c:     help("Styles.html");
./ttfinstrsui.c:            help("ttfinstrs.html");
./ttfinstrsui.c:            help("ttfinstrs.html");
./ttfinstrsui.c:            help("ttfinstrs.html#cvt");
./ttfinstrsui.c:            help("ttfinstrs.html#cvt");
./ttfinstrsui.c:            help("ttfinstrs.html#maxp");
./bitmapdlg.c:      help("elementmenu.html#Bitmaps");
./groupsdlg.c:  help("groups.html");
./problems.c:       help("problems.html");
./problems.c:       help("problems.html");
./showatt.c:    help("showatt.html");
./statemachine.c:           help("statemachine.html#EditTransition");
./statemachine.c:           help("statemachine.html");
./cvgetinfo.c:      help("getinfo.html");
./cvgetinfo.c:      help("getinfo.html");
./cvgetinfo.c:      help("getinfo.html");
./cvgetinfo.c:      help("getinfo.html");
./charinfo.c:       help("charinfo.html#Counters");
./charinfo.c:       help("charinfo.html");
./charinfo.c:       help("selectbyatt.html");
./transform.c:      help("transform.html");
./anchorsaway.c:            help("anchorcontrol.html");
./cvimportdlg.c:            help("filemenu.html#type3-import");
./mmdlg.c:          help("mmmenu.html");
./mmdlg.c:          help("multiplemaster.html#NamedStyles");
./mmdlg.c:          help("multiplemaster.html");
./mmdlg.c:          help("multiplemaster.html");
./prefs.c:          help("prefs.html#Features");
./prefs.c:          help("prefs.html");
./justifydlg.c:     help("justify.html#glyphs-dlg");
./justifydlg.c:     help("justify.html#lookup-dlg");
./justifydlg.c:     help("justify.html#language-dlg");
./justifydlg.c:     help("justify.html");
./lookupui.c:       help("lookups.html#scripts-dlg");
./lookupui.c:       help("lookups.html#scripts-dlg");
./lookupui.c:       help("lookups.html#Add-Lookup");
./lookupui.c:       help("lookups.html#Anchor");
./lookupui.c:       help("lookups.html#Pair");
./lookupui.c:           help("lookups.html#Single-pos");
./lookupui.c:           help("lookups.html#Pair");
./lookupui.c:           help("lookups.html#basic-subs");
./charview.c:    help("charview.html");
./metricsview.c:    help("metricsview.html");
./histograms.c:     help("histogram.html");
./histograms.c:     help("histogram.html");
./histograms.c:     help("histogram.html");
./histograms.c:     help("histogram.html");
```
Given that the github "file filter" interface doesn't include `.c` this doesn't seem to have been addressed (I didn't look through the whole file list except to confirm that some of these files have been deleted). 

On my reading `help()` first looks for local copies and falls back to the web (via `fontforge.sf.net` URLs). One could eliminate the first step, cutting off the (increasingly small?) uses of fontforge in settings (temporarily?) without network access. Then if/when the website changes this could be handled with a redirect map -- although that won't work for any bookmark symbols that change.

**Comment by JoesCat** [comment]
Reminder on internal (/usr) vs external (cloud) browser links.
1 - https://github.com/fontforge/fontforge/issues/3123#issuecomment-428978667
2 - https://sourceforge.net/p/fontforge/mailman/message/36474075/
3 - not everyone has good internet access.

Concerning 1, if all links are already supplied internally, these sort of CVEs remain as false positives, and can be considered non issues.
About 2 - As it reads, you have institutions that have concerns about external links, I see these concerns at work, and I can see this as an issue with schools, ensuring all the links are already answered internally is good.
and for 3 - Not everyone is driving a desktop PC connected to internet. ...and having been out of the country last year (myself, in Europe), I can indicate with certainty, not everyone has great internet access - once you're outside the big cities, internet access can be a bit spotty.

Most individual users probably aren't going to really care if you use internal or external links, but I do think you are introducing a problem (that doesn't exist now) for some users if you add external links.

**Comment by jtanx** [comment]
> On the level of overall repository coherence, no systemic rename of the documentation files should be merged without a PR/plan for the help() function

Good pickup, thanks, this should be fixed now. I've left it to preference the local filesystem first then try online. Coincidentally I've updated and simplified it to use gio.

**Comment by skef** [comment]
The `uiutil.c` changes in the recent commit look good to me.

**Comment by jtanx** [comment]
@frank-trampe  / @ctrlcctrlv  any thoughts/comments? Otherwise I'm inclined to merge this.

**Comment by skef** [comment]
I don't believe there is a separate approval policy for doc change PRs, especially ones this extensive.

**Comment by frank-trampe** [comment]
It's a huge changeset, and I still can't figure out how @jtanx managed to accomplish this. There's no easy way to review the whole thing, but I'm sure we can address any complaints incrementally. Absent additional objections, I'm okay merging this.

**Comment by jtanx** [comment]
Thanks, yeah the change is smaller than the diff implies, given it's mostly the same content - definitely not saying it was zero effort though...

**Pull request merged**
