### PR TITLE
doc: fix some minor wording issues

### PR DESCRIPTION
**Pull request by fabiangreffrath**
Provide a general summary of your changes in the **Title** above.
### Important

Mark with [x] to select. Leave as [ ] to unselect.
### Motivation and Context
- [X] Why is this change required? What problem does it solve?
  I found the current documentation misleading.
  E.g. `ToUpper($1)` does not turn the variable `$1` to upper case, but `$1 = ToUpper($1)` does.
- [ ] If it fixes an open issue, include the text `Closes #1` (where 1 would be the issue number) to your commit message.
### Types of changes

What types of changes does your code introduce? Check all the boxes that apply:
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
### Description
- [X] Describe your changes in detail.
  The ToLower() and ToUpper() functions do not convert the variable itself,
  instead they return a converted value.
### Final checklist

Go over all the following points and check all the boxes that apply. 
If you're unsure about any of these, don't hesitate to ask. We're here to help! Various areas of the codebase have been worked on by different people in recent years, so if you are unfamiliar with the general area you're working in, please feel free to chat with people who have experience in that area. See the list [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#people-to-ask).
- [ ] My code follows the code style of this project found [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#coding-style).
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING**](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md) guidelines.

Your pull request will be tested via Travis CI to automatically indicate that your changes do not prevent compilation. FontForge is a big program, so Travis can easily take over 20 minutes to confirm your changes are buildable. Please be patient. More details about using Travis can be found [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#using-travis-ci).  

If it reports back that there are problems, you can log into the Travis system and check the log report for your pull request to see what the problem was. If no error is shown, just re-run the Travis test for your pull-request (that failed) to see a fresh report since the last report may be for someone else that did a later pull request, or for mainline code. If you add new code to fix your issue/problem, then take note that you need to check the next pull request in the Travis system. Travis issue numbers are different from GitHub issue numbers.

### CODE REVIEW

**Comment by frank-trampe** [comment]
I'm ambivalent about this one. @davelab6?

**Comment by JoesCat** [comment]
The method is a table lookup, but the input value is not changed.
@fabiangreffrath can you look at the file inc/utype.h and see if there are other routines that could also be affected?  You noticed tolower/toupper, but you'll see there are about 1/dozen similar functions, like to{....} and they may also have similar wording too.

**Comment by fabiangreffrath** [comment]
Hm, there is `ToMirror()` and `ToString()` (and `ToTitle()` and `ToValue()`, but the latter two are not documented on the `scripting-alpha.html` page). What else do you mean?

**Comment by frank-trampe** [comment]
Ping @davelab6.

**Comment by JoesCat** [comment]
On September 5, 2016 12:24:19 PM Fabian Greffrath wrote:
> Hm, there is `ToMirror()` and `ToString()` (and `ToTitle()` and
> `ToValue()`, but the latter two are not documented on the
> `scripting-alpha.html` page). What else do you mean?

As they more or less are the same, I was expecting similar errors, however, 
since you note that two of them are completely absent, would you be 
interested including a patch to define one or both of them?

**Comment by frank-trampe** [comment]
Pinging @davelab6. I don't think that the original wording is confusing, but I'm not an average user.

**Comment by jtanx** [comment]
I tend to agree, but that's only because I'm likening it to the C equivalents (which the documentation does say it's influenced by).

**Comment by davelab6** [comment]
It seems plain that @fabiangreffrath attempted to read the docs, found them confusing, and provided a patch that clarifies the docs for him. So I don't know why there is any concern about merging this, and I've done so. 

@frank-trampe it is important that first-time contributors PRs are merged quickly when they are trivial, to encourage them to contribute again. Please be more easygoing on trivial PRs.

**Pull request merged**
