### PR TITLE
Run (almost all) python tests both embedded and through python

### LINKED ISSUE #3525: Add Makefile target to run python tests via modules/pyhook instead of FontForge
I only caught the Pickling problem (after adding a test) because I tried to run it using python manually. Even if it's not part of travis (it probably should be), there should be a way of running the python tests through python. 

I'm making this an issue instead of a pull request because the whole testsuite m4 situation makes this addition non-obvious. I'm guessing generating a second file is the best way to go, but I'm not sure.

### PR DESCRIPTION
**Pull request by skef**
Closes #3525 

### Types of changes
What types of changes does your code introduce? Check all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist
Go over all the following points and check all the boxes that apply. 
If you're unsure about any of these, don't hesitate to ask. We're here to help! Various areas of the codebase have been worked on by different people in recent years, so if you are unfamiliar with the general area you're working in, please feel free to chat with people who have experience in that area. See the list [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#people-to-ask).
- [x] My code follows the code style of this project found [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#coding-style).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md) guidelines.

### CODE REVIEW

**Comment by skef** [comment]
Lord knows what this will do on Windows.

**Comment by skef** [comment]
I don't have a windows environment handy. I presume the way to work through this is to get to the point after a "make", open a shell, and play around with running a particular test using variants of the command. 

The most recent variant has:
```
m4_defun([run_python_py],[(PYTHONPATH="${abs_top_builddir}/pyhook/.libs:$PYTHONPATH" ${python_exec} "${abs_srcdir}/$1" "$2" || /bin/false)])
```
Some earlier variants passed `-Ss` to python. The primary goal is to make the modules in `pyhook/.libs` have precedence. The secondary goal is to make it less likely that some other set of modules will be picked up if those are missing. 

The latter is *probably* only of minor importance. I've tested with all four combinations of `--disable-python-scripting` and `--disable-python-extension`, and the test suite doesn't try to run tests it hasn't been built for. Therefore any problem that prevents populating `pyhook/.libs` with modules *should* be caught earlier in the build process. Anyway, it's fine to preserve the existing `PYTHONPATH` but the build directory should come first. `-Ss` was kind of a stab in the dark, but marginally contributes to the secondary goal.

**Comment by jtanx** [comment]
The problem was dll resolution, fixed by altering PATH. We should just statically link all our own code and get rid of the dlls...

**Comment by skef** [comment]
Looks good to me! 

I have no idea how much this will help, but by only running "Various stroke tests" in one mode it doesn't add much time to `make check`. I only caught the pickling problem by trying to run that test by hand and this seems like better practice.

**Pull request merged**
