### PR TITLE
EncMapNew, EncMap1to1, EncMapCopy cleanup on error

### PR DESCRIPTION
**Pull request by JoesCat**
If error encountered, cleanup and return NULL (instead of Segment fault).

### CODE REVIEW

**Comment by frank-trampe** [comment]
Was this crashing?

**Comment by JoesCat** [comment]
No crash, but following the code, I could see a potential problem if you run tight on memory (with a large encoding map, like Unicode, or the larger iso6something (obsolete) one).
Consider this as yet another bunch of routine made robust, so if error encountered along the way, it exits gracefully/cleanly.

What I did note, is that I was unable to make Encodefree exit cleanly, example:
```c
enc=FindOrMakeEncoding("win");
if ( enc ) {
printf("pass, Win works\n"); EncodingFree(enc);
}
if ( enc ) {
printf("pass, ANSI works\n"); EncodingFree(enc);
}
if ( enc ) {
printf("pass, ANSI works\n"); EncodingFree(enc);
}
```
there is something that needs work with the EncodingFree(), but I'll leave that for a later date....

**Comment by JoesCat** [comment]
sorry, forgot to add the other lines before the if (enc) up above...
```c
enc=FindOrMakeEncoding("win");
if ( enc ) {
printf("pass, Win works\n"); EncodingFree(enc);
}
enc=FindOrMakeEncoding("ansi");
if ( enc ) {
printf("pass, ANSI works\n"); EncodingFree(enc);
}
enc=FindOrMakeEncoding("ansi");
if ( enc ) {
printf("pass, ANSI works\n"); EncodingFree(enc);
}
```

**Comment by davelab6** [comment]
Thank you @JoesCat ! :D 

@frank-trampe any objections?

**Comment by frank-trampe** [comment]
@JoesCat, your editor is still doing funny things with whitespace. I've moved this to #2664 without the whitespace changes.

**Pull request closed without merging**
