### PR TITLE
Overhaul the unicode support library

### LINKED ISSUE #2566: Probable out-of-range in unicode_alternates array
From https://github.com/fontforge/fontforge/blame/master/fontforge/splinesaveafm.c lines 1294 to 1300:

``` c
if ( isdecompositionnormative(sc->unicodeenc) && sc->unicodeenc>=65536 &&
        unicode_alternates[sc->unicodeenc>>8]!=NULL &&
        (upt = unicode_alternates[sc->unicodeenc>>8][sc->unicodeenc&0xff])!=NULL ) {
    while ( *upt!='\0' )
        unicode[u++] = *upt++;
} else
    unicode[u++] = sc->unicodeenc;
```

Note that this only ever accesses the unicode_alternates array if sc->unicodeenc>=65536 is true, and in that case, the index is necessarily 256 or greater.  This array's valid range of indices is 0 to 255, so it can't possibly be right.  The code is from a March 2006 commit by George Williams.

At first glance it looks like that test needs to be inverted; it's asking whether there is valid data in the array and so it should be sc->unicodeenc<65536.  I'm hesitant to try to change it, though, because I don't really understand how the information from this array is intended to be used anyway.

### PR DESCRIPTION
**Pull request by jtanx**
This is a continuation of the charsets/iconv overhaul, extending to the code-genned stuff under the `Unicode` folder.

The original motivation was to shrink the size of the code-genned data (which used plain old arrays covering only the BMP), and also to make the process of updating this support layer not so cryptic/painful. To update now consists primarily of running one Python file (`makeutype.py`), and it will do everything for you, including fetching all required data.

But I think there are several more benefits that were picked up along the way as a consequence.

Primarily:

* The unicode functions now supports the full unicode range, not just the BMP(!!)
* It uses multi-stage lookup tables (same as what Python does) to reduce table sizes
* NamesList support is fully integrated
* There is minimal manual intervention required to update this layer
* Updated to Unicode 13.0.0

In terms of space savings, the complete layer, *including* the NamesList integration is around ~700kb, which comes in *under* the original size of the old Unicode implementation (~1.5-2mb), which excluded NamesList support. This is also all done with constant-time lookup tables, so negligible difference in speed (not that that was/is a concern anyway).

I was originally going to make the nameslist support optional (allowing to still use libuninameslist), but that ended up being more effort than it was worth, and this also aligns with something that has been discussed prior anyway (see also #3861). Basically if I can get this functionality in, in under the space used previously, I don't see why this should ever be disabled. This integration also makes sense in the fact that it actually matches up with the version of Unicode that FontForge has been built with.

-----

While this is all well and good, I have also removed some functions: namely those relating to ligatures/fractions. As to why: when you sit down and look at what it's doing, none of it is actually well defined in terms of normative Unicode properties. The decompositions provided by is_Ligature.c is primarily derived from the NFKD sequences, which are _already_ recorded in unialt.c. 

What remains are manual 'decompositions', most of which I find questionable - i.e. the [first one I come across](https://github.com/fontforge/fontforge/blob/a5dedb4010cd49a5fcfaeed5d188dd7942294005/Unicode/makeutype.c#L163), suggests that U+04a4 is composed of U+041d, and U+0413, but if you [read up](https://en.wikipedia.org/wiki/En-ghe) on what that character provides, you realise that it cannot actually be composed of either.

The exposed functions are also extremely low level, to the point of exposing the internal implementation details of how the data is organised (in tables, this is also true for the poorly named 'Names2' functions, which really only just extract the formal alias from the annotation).  Prove me wrong, but I have yet to see _any_ living example of scripts that make use of these functions.

-----

### Type of change

- **Bug fix**
- **New feature**
- **Breaking change**

Closes #2566

See also: #2570, although this doesn't really aim to address the issues laid out there.

### CODE REVIEW

**Comment by khaledhosny** [comment]
Not sure if it is of any use to you, but HarfBuzz uses https://github.com/harfbuzz/packtab to generate compact Unicode data tables.

**Comment by jtanx** [comment]
Ah, interesting. I think I saw the old packtab (I think glib uses something similar?) but didn't know about that one. I currently just use the one that Python uses, which does an ok job.

**Comment by jtanx** [comment]
Any further comments? Otherwise I'd like to merge this over the coming days

**Comment by ChiefMikeK** [comment]
> Any further comments?   
> Otherwise I'd like to merge this over the coming days
  
Just a FYI Unicode 14.0 final draft is out for public review and reliese soon 😁

**Comment by jtanx** [comment]
Yep, I'll update it once it's actually released in September.

**Comment by jtanx** [comment]
Final call for comments? Otherwise I'll merge tomorrow.

**Pull request merged**
