### PR TITLE
Use ffglib.h instead of 'define/undef'-ing GList

### PR DESCRIPTION
**Pull request by gioele**
Tiny clean-up, found during working on PR #2821.

### CODE REVIEW

**Comment by frank-trampe** [comment]
@jtanx?

**Comment by jtanx** [comment]
I restarted the mac build which failed because the gnulib clone failed. gnu.org seems mighty unstable as of late.

**Comment by jtanx** [comment]
Hmm, I see that `ffglib.h` is an installed and not private header. We have to be careful here, because we redefine GTimer and GList. Presumably we don't want someone to include our headers and then unexpectedly have those redefined to GTimer_GTK/GList_Glib

**Comment by frank-trampe** [comment]
Since we're only changing the references in compiled files, I don't consider this a regression. Let's investigate and make an issue.

Why do we install any headers for the graphical interface? Nobody builds against them, does he?

**Comment by gioele** [comment]
Thank you for the merge. The ui headers are installed because they and the library headers are deeply, deeply entangled. Disentangling them is the point of original PR.

**Pull request merged**
