### PR TITLE
Fix autosave recovery

### PR DESCRIPTION
**Pull request by jtanx**
Regression from #3593

### CODE REVIEW

**Comment by ctrlcctrlv** [comment]
Did you test this against #3613 or is that another problem?

**Comment by jtanx** [comment]
This was just something I observed locally, looking at that stack trace, it looks like it's the same cause

**Comment by ctrlcctrlv** [comment]
@jtanx Hey&mdash;I confirm this closes both #3613 and #3614. Your patchset averts both crashes.

**Comment by jtanx** [comment]
Thanks for confirming

**Pull request merged**
