### PR TITLE
Adding a new selection-based method, isWorthOutputting, for the pytho…

### PR DESCRIPTION
**Pull request by HinTak**
…n font object; and documentation

Thanks Frank Trampe for the suggestion.

Fixes
https://github.com/fontforge/fontforge/issues/3107

Provide a general summary of your changes in the **Title** above.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### Motivation and Context
- [ ] Why is this change required? What problem does it solve?
- [x] If it fixes an open issue, include the text `Closes #1` (where 1 would be the issue number) to your commit message.

### Types of changes
What types of changes does your code introduce? Check all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description
- [ ] Describe your changes in detail.

### Final checklist
Go over all the following points and check all the boxes that apply. 
If you're unsure about any of these, don't hesitate to ask. We're here to help! Various areas of the codebase have been worked on by different people in recent years, so if you are unfamiliar with the general area you're working in, please feel free to chat with people who have experience in that area. See the list [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#people-to-ask).
- [ ] My code follows the code style of this project found [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#coding-style).
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md) guidelines.

Your pull request will be tested via Travis CI to automatically indicate that your changes do not prevent compilation. FontForge is a big program, so Travis can easily take over 20 minutes to confirm your changes are buildable. Please be patient. More details about using Travis can be found [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#using-travis-ci).  
  
If it reports back that there are problems, you can log into the Travis system and check the log report for your pull request to see what the problem was. If no error is shown, just re-run the Travis test for your pull-request (that failed) to see a fresh report since the last report may be for someone else that did a later pull request, or for mainline code. If you add new code to fix your issue/problem, then take note that you need to check the next pull request in the Travis system. Travis issue numbers are different from GitHub issue numbers.

### CODE REVIEW

**Comment by JoesCat** [comment]
Although the subject is python oriented, it is worth making an equivalent "nativescript" command too, either now, or eventually later. Some complaints about FontForge have been how some instructions exist in nativescript, but not python, or python, but not nativescript, or GUI but not scripting.
There are users that exclusively use nativescript and not python.
Can you add a nativescript version?

**Comment by HinTak** [comment]
You don't get it - this addition is to mimic the native script's WorthOutting() behavior, which is selection based when used without an argument, and glyph-based when used with argument. The python interface is simply lacking compared to the native interface. There is nothing to add in the native scripting interface. This is the whole point of this addiion: to make the python interface better match the native one in functionality.

**Comment by HinTak** [comment]
It is a bit late for the naming discussion. The python glyph-based method did not follow the native name, so I think the font/selection-based method should follow python-convention, i.e. the glyph-based method naming. The native method simply have the functionality of both, depending on whether you pass an argument in; that's all, and with a slightly different name.

It is just unfortunate that the python implementation did not try to map first all the functionality of the native scripting interface. Or at least, put a placeholder in (and throw UnimplementedException for the time being, until somebody fill it in).
As such, it is difficult to migrate from one to the other.

**Comment by frank-trampe** [comment]
@HinTak, the compound function in native scripting and the native FontForge function that the per-glyph Python binding exposes are different things and justifiably (if originally by accident) have different names. This wrapper corresponds directly to the the wrapper function from native scripting and not to the native FontForge function, and it ought to be named accordingly.

If your goal is to ease the transition between native and Python scripting, which seems to me to be the only reason to add this Python binding at all, it seems wise to keep the names consistent between the two rather than arbitrarily naming this function after another function that behaves differently.

This is what I am proposing.

| Name | Logic in C | Logic in FF Scripting | Logic in Python |
|--|--|--|--|
| isWorthOutputting | Take a glyph as input, output whether the glyph is significant. | (Not implemented.) | Take a glyph as input, output whether the glyph is significant. |
| WorthOutputting | (Not implemented.) | Take a slot or a selection as input, output whether there is an assigned glyph and whether it is significant. | Take a slot or a selectionas input, output whether there is an assigned glyph and whether it is significant. |

This is what you are proposing.

| Name | Logic in C | Logic in FF Scripting | Logic in Python |
|--|--|--|--|
| isWorthOutputting | Take a glyph as input, output whether the glyph is significant. | (Not implemented.) | If called on a glyph, take the glyph as input and output whether the glyph is significant. If called on a splinefont, take a slot or a selection as input and output whether there is an assigned glyph and whether it is significant. |
| WorthOutputting | (Not implemented.) | Take a slot or a selection as input, output whether there is an assigned glyph and whether it is significant. | (Not implemented.) |

**Comment by HinTak** [comment]
There are some fundamental differences between the two scripting languages: the python variant is object-oriented, whereas the native variant is largely context-oriented, or based on the current selections. I don't think there needs to be any relationship between the scripting languages and the C internals; but I see consistency within each language more important - hence a uniform 'IsWorthOutputting()' method across the python variant, and does different but related things depending on the object.

The point of this change is that,

Select(x);
# check that the destination is empty before pasting
if (! WorthOutputting())
    Paste()
else
    # throw error
    Print("Destination Full")

does not require doing something awful like this in python:

            font.selection.select( x )
            try:
                font[x]
            except TypeError:
                # expect this!
                font.paste()
                pass
            else:
                # throw error
                print("Destination full")


I think arguing the scripting functions' name should match the C internals is a bit weak - the whole point of the scripting language is that one doesn't want to touch the C internals... if that's a valid argument, python's len() methods should be named strlen() or something, and python's str() method should be named sprintf() !

**Comment by ctrlcctrlv** [comment]
At this point...this no longer can be merged without a conflict, it's years old, and @frank-trampe seems to not want it. So I'm closing this as it is unlikely to ever be merged, primarily due to its age. It can be reopened if interest in it is ever renewed.

**Comment by HinTak** [comment]
Updated version of this pull in the New https://github.com/fontforge/fontforge/pull/4522

**Pull request closed without merging**
