### PR TITLE
ttf: fix underlinePosition calculation

### PR DESCRIPTION
**Pull request by adrientetar**
- Fix a signs problems in underlinePosition calculation for OpenType fonts. This was noticed here: http://typophile.com/node/103251#comment-555313 but never reported.
- Don't recalculate underlinePosition from the post table if we have a CFF font.

r? @frank-trampe

### CODE REVIEW

**Comment by frank-trampe** [comment]
Aside from the odd whitespace changes, the code changes look good given what you state we are trying to do. Can you reference the appropriate part of the specification on this issue?

**Comment by adrientetar** [comment]
> This is the suggested distance of the top of the underline from the baseline (negative values indicate below baseline). 
The PostScript definition of this FontInfo dictionary key (the y coordinate of the center of the stroke) is not used for historical reasons. **The value of the PostScript key may be calculated by subtracting half the underlineThickness from the value of this field.**

http://www.microsoft.com/typography/otspec/post.htm

**Comment by frank-trampe** [comment]
Excellent. I confirm your math.

I approve of everything except for the whitespace changes.

**Comment by adrientetar** [comment]
Well. They concern mostly empty lines, I'll merge this one for the time being. You can ignore whitespace changes with the `-w` switch of git blame.

**Pull request merged**
