### PR TITLE
Update fontstyles.html with Croatian

### PR DESCRIPTION
**Pull request by milotype**
### Type of change
- **New feature**: Croatian translation added

### CODE REVIEW

**Comment by jtanx** [comment]
Thanks

**Comment by JoesCat** [comment]
@milotype - would you mind looking at the desktop directory?
There are a couple of files there that may benefit from your expertise in translation.

**Comment by milotype** [comment]
yes, i can have a look at it … are you refering to these 3 files:
org.fontforge.FontForge.appdata.xml
org.fontforge.FontForge.desktop
org.fontforge.FontForge.metainfo.xml

milo

**Comment by milotype** [comment]
BTW, can someone place the current .pot file for FontForge GUI into the "po" folder.
I'm no programmer. As most translators, I don't know how to generate the pot file.

In many GitHub projects I've translated I could convince the administrators to have the pot-file in the po-folder, so translators can easily grab the necessary file. I usually send merge requests directly through GitHub – not from my local computer. I make a fork of the repository in GitHub, make my changes and sent merge-request from my fork.

I'm sure Croatian isn't the most important laguage, but I could give it a try …

Milo

**Comment by JoesCat** [comment]
Hi @milotype - yes, those three files.

> org.fontforge.FontForge.appdata.xml
> org.fontforge.FontForge.desktop
> org.fontforge.FontForge.metainfo.xml
 
these are plain text files. In Linux, and probably MAC, they should appear fine using a plain-text editor, but if you are running windows, notepad (as a plain text editor), it is a bit lacking when it comes to recognize the end of line returns, so I would suggest editing with notepad++.

> BTW, can someone place the current .pot file for FontForge GUI into the "po" folder. I'm no programmer. As most translators, I don't know how to generate the pot file.

That is a good suggestion, and lack of that has probably hindered many contributors with expertise in translation. FontForge uses a stripped-down gettext version since some operating systems had difficulties with autotools, gettext, and other features, so that is why it appears a bit different and probably truncated to you.

I'll add a blank Croatian file which you can begin modifying. The new file is hr.po

For translators that want to try adding a new language themselves, you can try this....

1. Start with a fresh git download, don't run ./bootstrap or other install yet...
2. In the po directory, modify the two lines to add your 2-character language (hr).
https://www.google.com/search?q=croatian+language+code&ie=utf-8&oe=utf-8

```c
PO_FILES = ca.po el.po es.po it.po pl.po vi.po zh_TW.po de.po	\
	en_GB.po fr.po ja.po ml.po ru.po uk.po zh_CN.po pt.po ko.po hr.po

MO_FILES = ca.mo el.mo es.mo it.mo pl.mo vi.mo zh_TW.mo de.mo	\
	en_GB.mo fr.mo ja.mo ml.mo ru.mo uk.mo zh_CN.mo pt.mo ko.mo hr.mo
```
copy en_GB.po to hr.po (this is your starting point - notepad++ will work fine)
(for users running git, you also need to run "git add po/hr.po")

3. Now run ./bootstrap, ./configure, etc like you normally would do...
4. Before editing the file, you will want to update the file to the latest version. To do this, run make, then after you run make, go into the po directory and run this command:
make FontForge-Update-po 1=hr
This will update hr.po
5. Edit the header details at the top of the po file for your specific language, example "hr"
please check the header on pl.po - it has a complex plurals, which may be near your needs and search for info by the author as there are many tips that may be useful to you.

The above information may be useful for translators that want to try add new files themselves.

See if #3808 is what you need.
Please send your updates by July31 so that it catches the next target release - likely Aug1

Sorry for the delayed response, but you should be good to go now (with hr.po).

**Pull request merged**
