### PR TITLE
ttfinstrs: handle carriage returns when parsing

### PR DESCRIPTION
**Pull request by adrientetar**
cc #2212.

### CODE REVIEW

**Comment by frank-trampe** [comment]
This looks safe to me. Have you tested with a file with each linebreak style?

**Comment by frank-trampe** [comment]
Ping.

**Comment by adrientetar** [comment]
No I have not tested. This will only change behavior for files which have carriage returns.

**Comment by frank-trampe** [comment]
When do you expect to be able to test? I'm cutting the April release soon.

**Comment by frank-trampe** [comment]
I'm going to assume that passing the unit tests is good enough to assure that there are no regressions.

**Pull request merged**
