### PR TITLE
Remove unused usprintf.c

### PR DESCRIPTION
**Pull request by gioele**
The file `usprinf.c` has not been compiled nor used since commit
e7ad22a43a055293bcb6badfeb616a1f5eec34b4 (2014-02).

None of the included functions can possibly be used since commit
36244a703185d22c9466f73a824ca54a6529fd5e (2014-02).

@JoesCat, I extracted this tiny change from one of my pending branches that had to do with `Unicode/`. The rest of the branch does not apply anymore, but this commit is still valid.

### CODE REVIEW

**Comment by JoesCat** [comment]
Hi @gioele,
I'll have to leave this one for @frank-trampe and @jtanx to look at. This is one of those old built-in functions from the past that made it easier to compile FontForge on other platforms. Sometimes using another library is better or makes it harder (by adding more dependencies).

**Comment by jtanx** [comment]
This one's fine by me - you can always make use of `g_ucs4_to_utf8`.

**Comment by frank-trampe** [comment]
This doesn't accomplish anything and has a non-zero chance of breaking things in somebody's fork.

**Comment by gioele** [comment]
Hi @frank-trampe, this PR accomplish making the fontforge code less of a "rat's nest" (see https://lists.alioth.debian.org/pipermail/pkg-fonts-devel/2012-October/011216.html). ;)

I think there has been a misunderstanding with this PR. Please note that this file not been part of the distributed fontforge package for various years. Only few days ago @JoesCat inadvertently re-added it to `Makefile.am` in its the recent commit 76118157c25323abca5ee04146f145de3c08f5d9 that mass-reorganized the `Unicode/` directory.

How could removing this undistributed file break somebody's fork? The three functions in this file (`u_vsnprintf`, `u_snprint`, and `u_sprintf`) have not been updated, used nor included in the distributed fontforge sources for years. As @jtanx pointed out, they are all replaced by standardized and documented GLib functions like `g_vasprintf` or `g_ucs4_to_utf8`.

**Comment by davelab6** [comment]
@frank-trampe i suggest merging this, your reason for closing seems quite unreasonable.

**Comment by gioele** [comment]
hi @frank-trampe: are you still against removing the unused file `usprintf.c` after my explanations? (see <https://github.com/fontforge/fontforge/pull/2973#issuecomment-267817686>)

**Comment by frank-trampe** [comment]
This still doesn't deliver any significant benefits and might complicate repair efforts in the future.

I suspect that there were functions handling Unicode that were rewritten by people who didn't know the difference between u_sprintf and sprintf and switched. In this case, our concern would be not removing code that we need but determining where we need it.

There was, when I checked briefly, a valid rewrite by George that dropped support for Unicode where it was not required, but it's a lot of work to check all of them, and I'd prefer that we devote our time to things with bigger returns on investment.

If you want to hunt yourself, here's a list of old references. Some of the files listed in the fontforge directory moved to fontforgeexe.

```
./fontforge/fvimportbdf.c:    u_snprintf(ubuf, sizeof(ubuf)/sizeof(ubuf[0]), GStringGetResource(_STR_LoadingFrom,NULL), filename);
./fontforge/statemachine.c:    u_snprintf(buffer,sizeof(buffer)/sizeof(buffer[0]),
./fontforge/statemachine.c:    u_snprintf(stateclass,sizeof(stateclass)/sizeof(stateclass[0]),
./fontforge/statemachine.c:    u_snprintf(buf,sizeof(buf)/sizeof(buf[0]),
./fontforge/cvgetinfo.c:				u_snprintf(ubuf,sizeof(ubuf)/sizeof(ubuf[0]),
./fontforge/fontinfo.c:    u_snprintf(ubuf,sizeof(ubuf),GStringGetResource(_STR_StrIDforLanguage,NULL),
./fontforge/fontinfo.c:    u_snprintf(title,sizeof(title)/sizeof(title[0]),GStringGetResource(_STR_Fontinformation,NULL), sf->fontname);
./fontforge/fontinfo.c:    u_snprintf(title,sizeof(title)/sizeof(title[0]),_("Font Information for %.90s"), sf->fontname);
./fontforge/metricsview.c:    u_snprintf(ubuf,sizeof(ubuf)/sizeof(ubuf[0]),
./fontforge/parsettfatt.c:	u_snprintf(ubuf,sizeof(ubuf)/sizeof(ubuf[0]),GStringGetResource(_STR_UntitledAnchor_n,NULL),
./fontforge/parsettfatt.c:	u_snprintf(ubuf,sizeof(ubuf)/sizeof(ubuf[0]),_("Anchor-%d"),
./fontforge/parsettfbmf.c:	u_snprintf(ubuf,sizeof(ubuf)/sizeof(ubuf[0]),GStringGetResource(_STR_DPixelBitmap,NULL),
./fontforge/problems.c:	u_snprintf(ubuf,sizeof(ubuf)/sizeof(ubuf[0]),
./fontforge/problems.c:	u_snprintf(ubuf,sizeof(ubuf)/sizeof(ubuf[0]),
./fontforge/problems.c:	u_snprintf(ubuf,sizeof(ubuf)/sizeof(ubuf[0]),
./fontforge/problems.c:	    u_snprintf(buffer,sizeof(buffer)/sizeof(buffer[0]),
./fontforge/problems.c:	    u_snprintf(buffer,sizeof(buffer)/sizeof(buffer[0]),
./fontforge/problems.c:	u_snprintf(buffer,sizeof(buffer)/sizeof(buffer[0]),
./fontforge/problems.c:	u_snprintf(buffer,sizeof(buffer)/sizeof(buffer[0]),
./fontforge/problems.c:	u_snprintf(buffer,sizeof(buffer)/sizeof(buffer[0]),
./fontforge/showatt.c:		    u_snprintf(ubuf,sizeof(ubuf)/sizeof(ubuf[0]),
./fontforge/showatt.c:		    u_snprintf(ubuf,sizeof(ubuf)/sizeof(ubuf[0]),
./fontforge/histograms.c:	    u_snprintf(buffer,end-buffer,
./fontforge/histograms.c:	    u_snprintf(buffer,end-buffer,
./fontforge/histograms.c:	    u_snprintf(buffer,end-buffer,
./fontforge/histograms.c:	    u_snprintf(buffer,end-buffer,
./fontforge/encoding.c:		    u_snprintf(ubuf,sizeof(ubuf)/sizeof(ubuf[0]),
./fontforge/encoding.c:		    u_snprintf(ubuf,sizeof(ubuf)/sizeof(ubuf[0]),
./inc/ustring.h:extern int u_snprintf(unichar_t *str, int len, const unichar_t *format, ... );
./Unicode/usprintf.c:int u_snprintf(unichar_t *str, int len, const unichar_t *format, ... ) {
```

**Comment by jtanx** [comment]
I think it's more like it got superceded by g_ucs4_to_utf8 and g_vasprintf

**Comment by gioele** [comment]
As you said, the last use of `u_snprintf` and associated functions has been removed by GW in 2014 in commit 1d706510b6809787b3fda5ca1f1a76646b945b55 "Change fontforge to use GNU gettext rather than my own nomen services (for translations)."

Various releases has been produced without  `u_snprintf` since then. `u_snprintf` was used in frequently-used UI-related codepaths. Anybody using FontForge in any language that is not English would have noticed any problem caused by the 2014 commit already, most likely in the form of a crash or unreadable mangled messages.

**Comment by frank-trampe** [comment]
That commit was in 2005, before any of the forks that we care about happened and before the disorderly times, so we can be reasonably assured that this change would not impair a future merger and that no future fix would require restoring the removed code. So I'm okay with merging this, but it still doesn't really advance the project in any way, and I'd like to focus on things that do in the future.

**Pull request merged**
