### PR TITLE
Remove dead code

### PR DESCRIPTION
**Pull request by gioele**
This PR removes some functions that are no longer reachable from the current code, commented out or if-zeroed out.

I tried to make the commits as small as possible, for the sake of review and to document the commits in which the original code has been removed.

### CODE REVIEW

**Comment by frank-trampe** [comment]
Hi there. Some of these things are likely to be useful in the future. I specifically recall writing one of the unused functions to aid future efforts of some sort. I'll take a closer look at these late next week.

**Comment by jtanx** [comment]
On the other hand, I bet that some of that code has remained dead for many number of years.

I don't think we should be leaving dead code in there only on the off chance that it might be useful - that in part is what revision control is for.

**Comment by gioele** [comment]
Hi! In this PR there are two classes of commits: one kind of commit removes obvious dead/broken code (declaration of non-existing functions), the one deletes code that has not been used for years. There are only two or three commits of the latter kind, and I have deleted only functions that have not been used for at least two years.

Inside each commit message there is a link to the commit where the last code that used that function has been removed.

**Comment by gioele** [comment]
Ping. What is the consensus on this PR? Can I go on and merge this removal of dead code/unused declarations?

**Comment by frank-trampe** [comment]
There are definitely things in there that I don't want removed. We'll get to this after the release.

**Comment by gioele** [comment]
Is the reduced version #2880 more acceptable? :)

**Comment by frank-trampe** [comment]
That's fine.

**Comment by gioele** [comment]
Thank you for merging #2880. I have rebased this branch. Now it contains only the commits that have to do with function code.

**Comment by davelab6** [comment]
@frank-trampe I don't see any reason not to merge this

**Comment by JoesCat** [comment]
This looks okay, however, like @frank-trampe, I also hesitate at removing code quickly. The codebase is large, complex, and a lot of PRs past and present are "putting-out" immediate brush-fires. Sometimes there are PRs that have a thought in mind but never had a chance to complete...My last PR is an example, where it still needs equivalent python docs, or in native scripting converting error exits from hard exits to a safe return/cleanup/exit, or a lot of other code belonging to other developers as well as George, that got started, but hadn't had time to complete.
It's like a doctor in the operating room, it's 10x easier to cut something out, than to add something in, so, cut-out if it makes sense, but if there seems to have been reason for the code, maybe worth investigating and completing whatever was supposed to go in - in the end, you have better code instead of less code.

**Comment by ctrlcctrlv** [comment]
At this point...this no longer can be merged without a conflict, it's years old, and @JoesCat seems to not want it. So I'm closing this as it is unlikely to ever be merged, primarily due to its age. It can be reopened if interest in it is ever renewed.

**Pull request closed without merging**
