### PR TITLE
Adding windows theme

### PR DESCRIPTION
**Pull request by davelab6**
Taking action on my comment at https://github.com/fontforge/fontforge/issues/2230#issuecomment-99029372 I propose this for @jtanx to consider.

I simply duplicated the tango theme directory to `windows` in its current state; I hope @jtanx can sync the default theme as he wishes as it proceeds

### CODE REVIEW

**Comment by adrientetar** [comment]
Why can't we have the same folder for Windows?

**Comment by davelab6** [comment]
So windows can retain icons on menus without code

**Comment by jtanx** [comment]
To be honest, my preference over having icons is not particularly strong enough to warrant having a separate theme just for Windows. We should just reach a consensus, and if that's to remove the icons, then so be it.

**Comment by davelab6** [comment]
Okay cool :)

**Pull request closed without merging**
