### PR TITLE
Recalculate checkSumAdjustment when generating a WOFF file. #926

### PR DESCRIPTION
**Pull request by fred-wang**

### CODE REVIEW

**Comment by fred-wang** [comment]
I verified locally that the test passes with "make check" but travis seems to fail before (when downloading test fonts)...

**Comment by jtanx** [comment]
It looks like the path to the test font has changed from ftp://ftp.naist.jp/pub/NetBSD/packages/distfiles/adobe-cidfonts/ to ftp://ftp.naist.jp/NetBSD/packages/distfiles/adobe-cidfonts/

**Comment by fred-wang** [comment]
@jtanx thanks, that seems to work now. However, for some reason many tests are skipped.

It's possible that instead of recalculating the checkSumAdjustment, we just want to write the font tables in their offset order instead of the table directory order so that checkSumAdjustment may not need to be changed (otherwise the spec says we should drop DSIG tables). I'll do more experiments on this later.

**Comment by fred-wang** [comment]
Closing per my previous comment.

**Pull request closed without merging**
