### PR TITLE
ufo: output OS/2 fsType array even if it's empty

### PR DESCRIPTION
**Pull request by adrientetar**
An empty bit is actually a legit value in itself.

r? @frank-trampe

### CODE REVIEW

**Comment by frank-trampe** [comment]
This would seem to cause FontForge to denote a meaningful value on export even when there is no meaningful value, no?

**Comment by adrientetar** [comment]
This setting is the default in FontForge so yes. But all compilers have a default, for makeotf it's 0x8 Printable Document which actually is more restrictive than 0x0 Installable Embedding which is the default in FontForge. So we could consider changing the default setting on import or when creating a new font.

**Comment by frank-trampe** [comment]
Clean round-tripping is a fairly high-priority right now. A set flag may be in order, or we could initialize to a negative number. I don't have time to look at the code right now. What do you think?

**Comment by adrientetar** [comment]
We would be better off initializing it to a valid value otherwise we'd have to edit export code for all supported formats to handle it and not just UFO. 
FontForge already uses a default value for numerous fields in the font view (those who are left unset generally have a checkbox labeled "Default") so it wouldn't hurt to do so. I'll have a look.

**Comment by adrientetar** [comment]
@frank-trampe: It seems fsType's default value is -1 and exporters (incl. UFO) check against that when exporting. The TTF exporter has [a default value of 0x8](https://github.com/fontforge/fontforge/blob/e27e285fb052cc52ca5548103494ace48563aecd/fontforge/tottf.c#L3341) like makeotf. Is that ok to merge?

**Comment by frank-trampe** [comment]
I still think that this is not quite right. If we are round-tripping a U. F. O. that lacks that tag, and the user makes no meaningful changes, the output U. F. O. ought to omit the tag. @davelab6?

**Comment by adrientetar** [comment]
So we're not setting a value of -1 when inputting a UFO that does not have this key at all?

**Comment by adrientetar** [comment]
@frank-trampe: Should I add a default setting `sf->pfminfo.fstype = -1` on [that line](https://github.com/adrientetar/fontforge/blob/ufo-fstype/fontforge/ufo.c#L3790)?

[Here is](https://github.com/fontforge/fontforge/blob/8c18b53a635816ae6eed9be4ea2b0653d2daf11e/fontforge/splinefont.h#L1728) the struct decl. and the [SplineFontEmpty() function](https://github.com/fontforge/fontforge/blob/61067f16bcc5536d42e7985dd6b1f392411f1aad/fontforge/splineutil2.c#L3803) &ndash; the latter sets this value to -1 but I don't think it's called when creating a new SplineFont anyway.

**Comment by frank-trampe** [comment]
Yes. I just saw that; I did not quite understand your comment before. This is good to merge.

**Comment by davelab6** [comment]
On 9 March 2015 at 22:48, Adrien Tétar <notifications@github.com> wrote:

> The TTF exporter has a default value of 0x8
> <https://github.com/fontforge/fontforge/blob/e27e285fb052cc52ca5548103494ace48563aecd/fontforge/tottf.c#L3341>
> like makeotf. Is that ok to merge?
>

I would strongly prefer 0x0 to prevent people making DRM restricted fonts
unintentionally :)

**Pull request merged**
