### PR TITLE
portable compositor SFD script

### PR DESCRIPTION
**Pull request by Kelvinsong**
Soo I have this script (https://github.com/Kelvinsong/portable-compositor) that like writes opentype .fea files and adds necessary glyphs to SFD files. The result is a font in which you can access opentype features like old style numerals and small caps in any app that supports opentype rendering through the use of “magic words” like “<onum>1989</onum>”. @davelab6 suggested that this be incorporated somehow into fontforge itself…

Don’t know what tf is going on below with “sflayout” but it’s all in one file in my portable-compositor repository thing

### CODE REVIEW

**Comment by davelab6** [comment]
Kelvin, thanks so much for your effort here :) However, the pull request seems to be for a branch that includes only a patch that you had applied from @adrientetar once. Perhaps you pulled a branch from Adrien to your copy of the fontforge source tree. 

To submit a new file as a pull request, you'll need to stash any uncommitted changes, checkout the master branch, then checkout a new branch from master, then copy the file into the source directory tree in a good spot like the `contrib/fonttools` directory, then add it, then commit the add, and then push the branch to github, and then make the pull request. 

```sh
git stash;
git checkout master;
git checkout -b portable-compositor;
cp /path/to/file/portablecompositor.cpp contrib/fonttools;
git add contrib/fonttools/portablecompositor.cpp;
git commit contrib/fonttools/portablecompositor.cpp;
git push origin portable-compositor;
# Then visit https://github.com/fontforge/fontforge and make the pull request
```

**Comment by davelab6** [comment]
@adrientetar do you remember this commit? :)

**Comment by Kelvinsong** [comment]
\*blinks\*

**Comment by Kelvinsong** [comment]
I just picked “ffscript” bc it sounded like the folder or category in the fontforge source where I think it belongs? Then a bunch of Adrien’s stuff showed up and I was like “this is not my code” but I didn’t really know what else to pick so I went with it. should probably fix that if I can find out how (I’m bad at git sorry)

**Comment by Kelvinsong** [comment]
it says I’m not allowed to 

``remote: Permission to fontforge/fontforge.git denied to kelvinsong.
fatal: unable to access 'https://github.com/fontforge/fontforge.git/': The requested URL returned error: 403
``

**Comment by davelab6** [comment]
Oh! I see what happened. `ffscript` was an existing git branch. You made a pull request for it instead of for your own branch. 

Starting from the top:

```sh
cd ~; # reset to home
mkdir -p ~/src/github.com/fontforge/; # make a path which is self-evident
git clone git@github.com:fontforge/fontforge.git; # download a fresh copy into there
cd fontforge; # enter that copy
git checkout -b portable-compositor; # checkout a new branch, so named
cp /path/to/file/portablecompositor.cpp contrib/fonttools/; # drop the file in 
git add contrib/fonttools/portablecompositor.cpp; # add it 
git commit contrib/fonttools/portablecompositor.cpp; # commit it
git push origin portable-compositor; # push it 
# Then visit https://github.com/fontforge/fontforge and make the pull request between master and portable-compositor;
``

**Comment by davelab6** [comment]
Oh, you'll need to add your ssh public key to https://github.com/settings/ssh for the push to work.

Please play with https://try.github.io to better learn git :)

**Comment by adrientetar** [comment]
This branch can be deleted btw, Frank merged another patch.

**Comment by Kelvinsong** [comment]
I made a key but it still gives the same error?

**Comment by davelab6** [comment]
@Kelvinsong what error? :)

@adrientetar thanks!

**Comment by Kelvinsong** [comment]
``
git push origin portable-compositor

Username for 'https://github.com': kelvinsong

Password for 'https://kelvinsong@github.com': 

remote: Permission to fontforge/fontforge.git denied to kelvinsong.

fatal: unable to access 'https://github.com/fontforge/fontforge.git/': The requested URL returned error: 403
``

**Comment by adrientetar** [comment]
Fork the repository, push to your fork &ndash; not the mainline.

**Comment by davelab6** [comment]
Ah you didn't start from the top

Above I used this guy url

git clone git@github.com:fontforge/fontforge

Your error has a http url

**Comment by Kelvinsong** [comment]
nvm I just did it from the website with what Adrien said I made a new pull request thing

**Pull request closed without merging**
