### PR TITLE
Consolidate fontforge/ headers, part 3

### PR DESCRIPTION
**Pull request by gioele**
The third installation of the cleanups of the headers in `fontforge/`, a followup to PR #2969 (part 2) and #2878 (part 1).

As usual, I tried to kept this PR as "uneventful" as possible and I have moved moved the comments (if available) near to the function declarations. There are only two small things to note:

* The introdution of `mem.c` and the associated `mem.h`. I moved there the various `memlong`, `memushort`, etc function that are used by many parsing functions in many files but whose implementation was scattered among various `.c` files. (BTW, I suppose all these functions could be removed in favor of standard endian-correct bitshuffling functions, but that is for a separate PR).

* The duplication of the `#define real` block in `mem.h`. Avoid that duplication amounts to solving the whole float/double problem of FontForge. Definitely outside the scope of this series of cleanup.

### CODE REVIEW

**Comment by frank-trampe** [comment]
I like this. @JoesCat?

**Comment by JoesCat** [comment]
On December 23, 2016 07:52:33 AM Frank Trampe wrote:
> I like this. @JoesCat?

Sorry - been very busy lately.
I have not had a chance to look at anything, but if you're good with it, 
then please go ahead. Hope to have time after Xmas, before NY2017.

**Comment by frank-trampe** [comment]
Oops. Merge conflict. @gioele?

**Comment by davelab6** [comment]
@gioele awesome!!

**Comment by gioele** [comment]
@frank-trampe: thank you for the heads up. I rebased this PR on top of the current master and solved the conflict with the merged PR #2977.

**Pull request merged**
