### PR TITLE
Ligature, Vulgar Fraction, Other Fraction Alternate Expansion

### PR DESCRIPTION
**Pull request by JoesCat**
Ligatures and Vulgar fractions seem well defined on what the
alternate characters should be, but Other Fractions needs more
info on what exactly to expand into.

Ready for comments/review, but not ready yet for merge - Still need to add python docs, plus additional tests in test129.pe and test1009.py

### CODE REVIEW

**Comment by frank-trampe** [comment]
All we do at the error point in ffglib.h is include glib.h; I don't see what we could possibly be doing wrong. @DomT4, any ideas?

```
libtool: compile:  gcc -g -O2 -arch x86_64 -arch i386 -g -c -I../inc -I../inc -I../lib -I../lib -DSHAREDIR=\"/Users/travis/build/fontforge/fontforge/target/share/fontforge\" -DDOCDIR=\"/Users/travis/build/fontforge/fontforge/target/share/doc/fontforge\" -I../uthash/src -I../uthash/src -DFF_UTHASH_GLIF_NAMES=1 -DPLUGINDIR=\"/Users/travis/build/fontforge/fontforge/target/lib/fontforge/plugins\" -D_REENTRANT -I/usr/local/Cellar/glib/2.50.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.50.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.39/include -I/usr/local/Cellar/pango/1.40.3/include/pango-1.0 -I/usr/local/Cellar/harfbuzz/1.4.2/include/harfbuzz -I/usr/local/Cellar/pango/1.40.3/include/pango-1.0 -I/usr/local/Cellar/glib/2.50.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.50.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.39/include -I/usr/local/Cellar/fontconfig/2.12.1_2/include -I/usr/local/opt/freetype/include/freetype2 -I/opt/X11/include -I/usr/local/Cellar/pango/1.40.3/include/pango-1.0 -I/usr/local/Cellar/harfbuzz/1.4.2/include/harfbuzz -I/usr/local/Cellar/pango/1.40.3/include/pango-1.0 -I/usr/local/Cellar/cairo/1.14.8/include/cairo -I/usr/local/Cellar/glib/2.50.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.50.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.39/include -I/usr/local/Cellar/pixman/0.34.0/include/pixman-1 -I/usr/local/Cellar/fontconfig/2.12.1_2/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/libpng/1.6.28/include/libpng16 -I/opt/X11/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/include/libxml2 -I/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/include/python2.7 -Qunused-arguments -pthread -I/ ./splinerefigure.c  -fno-common -DPIC -o .libs/splinerefigure.o

In file included from ./splinerefigure.c:34:

In file included from ./splineutil.h:6:

In file included from ./views.h:32:

In file included from ./ffglib.h:27:

In file included from /usr/local/Cellar/glib/2.50.2/include/glib-2.0/glib.h:30:

In file included from /usr/local/Cellar/glib/2.50.2/include/glib-2.0/glib/galloca.h:32:

[1m/usr/local/Cellar/glib/2.50.2/include/glib-2.0/glib/gtypes.h:423:3: [0m[0;1;31merror: [0m[1m'_GStaticAssertCompileTimeAssertion_0' declared as an array with a negative size[0m

  G_STATIC_ASSERT(sizeof (unsigned long long) == sizeof (guint64));

[0;1;32m  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[0m[1m/usr/local/Cellar/glib/2.50.2/include/glib-2.0/glib/gmacros.h:232:103: [0m[0;1;30mnote: [0mexpanded from macro 'G_STATIC_ASSERT'[0m

#define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1] G_GNUC_UNUSED

[0;1;32m                                                                                                      ^~~~~~~~~~~~~~~

[0m1 error generated.

make[2]: *** [splinerefigure.lo] Error 1

```

**Comment by JoesCat** [comment]
If you follow the github commits, this problem happens some time earlier when we have the large conversion of *.h files. Either something broke earlier, or it highlights a problem that was there earlier but didn't trigger this error. Googling for the assert listed above, I found this:
[32 bit compilation failing on 64 bit Ubuntu 16.04](http://stackoverflow.com/questions/37935605/32-bit-compilation-failing-on-64-bit-ubuntu-16-04).
We are not alone, here's a MAC conversation: [glib: gmacros.h assertions fail on macOS #5404](https://github.com/Homebrew/homebrew-core/issues/5404).

**Comment by DomT4** [comment]
Aye, this is pretty heavily referenced on many bug trackers/etc. I presume the MacPorts hack is [this patch](https://github.com/macports/macports-ports/blob/6ad986dd8925b5dd70ae13f6b092f190bf64ea5e/devel/glib2/files/patch-configure.diff) but if it hasn't been taken by `glib` by now either it was never submitted to them, which is entirely possible, or they rejected it.

I stepped down from being a maintainer there but Homebrew would require it to at least be submitted & under consideration for them to adopt a similar patch.

**Comment by jtanx** [comment]
Sorry, had to close/reopen the PRs to (hopefully) get Travis working again

**Comment by JoesCat** [comment]
Hi @jtanx, no worries about the open/close. Appears to have fixed the travis tick marks.
Looking at what's ahead and having thought I'd be done by end of may, it's just better to merge this slightly premature and add the missing docs and equivalent tests later. This PR touches a lot of files and don't want to hold-back others from progress if anyone is looking at the same files for same or other reasons. PR merged.

**Comment by frank-trampe** [comment]
It's a massive piece of code, but it's also easy to trace/blame if there's a problem, so I'm okay merging without a full review.

**Pull request merged**
