### PR TITLE
Stroke: Make dialog more horizontal 

### PR DESCRIPTION
**Pull request by skef**
Old Dialog:

Previous version of new dialog:

New dialog (in this push request):
Screenshot_20191111_000905

### CODE REVIEW

**Comment by jtanx** [comment]
Seems fine - thanks for taking the time to rework this!

Something which I'm not sure is caused by these changes, or if it's present in general, is that I noticed a crash on Windows. But I'm having trouble getting a reproducible set of steps.

I reran this under Linux/Valgrind, and this is what I get

```
==5373== 
==5373== Conditional jump or move depends on uninitialised value(s)
==5373==    at 0x50D116C: RealWithin (splineutil2.c:214)
==5373==    by 0x513B44A: JointBendsCW (utanvec.c:106)
==5373==    by 0x50B2DB8: HandleJoin (splinestroke.c:1465)
==5373==    by 0x50B47EA: OffsetSplineSet (splinestroke.c:1571)
==5373==    by 0x50B47EA: SplineSet_Stroke (splinestroke.c:1816)
==5373==    by 0x50B47EA: SplineSets_Stroke (splinestroke.c:1833)
==5373==    by 0x50B47EA: SplineSetStroke (splinestroke.c:1932)
==5373==    by 0x4A39E4: CVStrokeIt (cvstroke.c:114)
==5373==    by 0x4A435E: _Stroke_OK (cvstroke.c:263)
==5373==    by 0x59291D: GButtonInvoked (gbuttons.c:257)
==5373==    by 0x592DB1: gbutton_mouse (gbuttons.c:485)
==5373==    by 0x59AFC4: _GWidget_Container_eh (gcontainer.c:304)
==5373==    by 0x59B5CE: _GWidget_TopLevel_eh (gcontainer.c:747)
==5373==    by 0x5A81CE: _GGDKDraw_CallEHChecked (ggdkdraw.c:329)
==5373==    by 0x5A8BD1: _GGDKDraw_DispatchEvent (ggdkdraw.c:1232)
==5373== 
==5373== Conditional jump or move depends on uninitialised value(s)
==5373==    at 0x513B44F: JointBendsCW (utanvec.c:106)
==5373==    by 0x50B2DB8: HandleJoin (splinestroke.c:1465)
==5373==    by 0x50B47EA: OffsetSplineSet (splinestroke.c:1571)
==5373==    by 0x50B47EA: SplineSet_Stroke (splinestroke.c:1816)
==5373==    by 0x50B47EA: SplineSets_Stroke (splinestroke.c:1833)
==5373==    by 0x50B47EA: SplineSetStroke (splinestroke.c:1932)
==5373==    by 0x4A39E4: CVStrokeIt (cvstroke.c:114)
==5373==    by 0x4A435E: _Stroke_OK (cvstroke.c:263)
==5373==    by 0x59291D: GButtonInvoked (gbuttons.c:257)
==5373==    by 0x592DB1: gbutton_mouse (gbuttons.c:485)
==5373==    by 0x59AFC4: _GWidget_Container_eh (gcontainer.c:304)
==5373==    by 0x59B5CE: _GWidget_TopLevel_eh (gcontainer.c:747)
==5373==    by 0x5A81CE: _GGDKDraw_CallEHChecked (ggdkdraw.c:329)
==5373==    by 0x5A8BD1: _GGDKDraw_DispatchEvent (ggdkdraw.c:1232)
==5373==    by 0x56FBD91: gdk_event_source_dispatch (gdkeventsource.c:369)
==5373== 
==5373== Invalid read of size 8
==5373==    at 0x45F418: nested_cv_e_h (charview.c:13142)
==5373==    by 0x59B017: _GWidget_Container_eh (gcontainer.c:405)
==5373==    by 0x5A81CE: _GGDKDraw_CallEHChecked (ggdkdraw.c:329)
==5373==    by 0x5A84D9: _GGDKDraw_OnWindowDestroyed (ggdkdraw.c:206)
==5373==    by 0x6386AB2: ??? (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.2)
==5373==    by 0x6386049: g_main_context_dispatch (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.2)
==5373==    by 0x63863EF: ??? (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.2)
==5373==    by 0x638649B: g_main_context_iteration (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.2)
==5373==    by 0x5A7026: GGDKDrawEventLoop (ggdkdraw.c:2199)
==5373==    by 0x579C84: fontforge_main (startui.c:1415)
==5373==    by 0x666D82F: (below main) (libc-start.c:291)
==5373==  Address 0xffefcb700 is on thread 1's stack
==5373==  211040 bytes below stack pointer
==5373== 
==5373== Invalid read of size 8
==5373==    at 0x4A47FB: stroke_sub_e_h (cvstroke.c:455)
==5373==    by 0x59B017: _GWidget_Container_eh (gcontainer.c:405)
==5373==    by 0x5A81CE: _GGDKDraw_CallEHChecked (ggdkdraw.c:329)
==5373==    by 0x5A84D9: _GGDKDraw_OnWindowDestroyed (ggdkdraw.c:206)
==5373==    by 0x6386AB2: ??? (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.2)
==5373==    by 0x6386049: g_main_context_dispatch (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.2)
==5373==    by 0x63863EF: ??? (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.2)
==5373==    by 0x638649B: g_main_context_iteration (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.2)
==5373==    by 0x5A7026: GGDKDrawEventLoop (ggdkdraw.c:2199)
==5373==    by 0x579C84: fontforge_main (startui.c:1415)
==5373==    by 0x666D82F: (below main) (libc-start.c:291)
==5373==  Address 0xffefc8430 is on thread 1's stack
==5373==  224080 bytes below stack pointer
==5373== 
```

With
image

**Comment by skef** [comment]
Hmm. The `HandleJoin` thing is just an "order inversion" problem that should be innocent. We used to run the first conditional of `_HandleJoin` before doing anything, and that would prevent any further processing when dealing with the first point. Now we pack up some data one level above and at the start some of those will be uninitialized. 

I suppose I can just move the first check up a level to `HandleJoin` to eliminate the issue. 

The other problem is more concerning. That's not likely caused by this PR but is plausibly a problem with the `stroke` branch. Let me ask: The dialog is now created on the stack. Is that inherently unkosher? What is the proper relationship between `GDrawDestroyWindow()` and the memory where the window is stored? It should be easy enough to change around, but I'm not confident about the "rules".

**Comment by skef** [comment]
@jtanx Maybe something like this from further down in unrelated `cvstroke.c` code:

```
    GDrawSync(NULL);
    GDrawProcessPendingEvents(NULL);
    GDrawSync(NULL);
    GDrawProcessPendingEvents(NULL);
```
?

**Comment by jtanx** [comment]
> The dialog is now created on the stack. Is that inherently unkosher? What is the proper relationship between GDrawDestroyWindow() and the memory where the window is stored? It should be easy enough to change around, but I'm not confident about the "rules".

Can you point out where this is done? I'll take a look later today. GDrawDestroyWindow frees the GWindow, but I'm pretty sure the only way that you can get a GWindow is from the CreateTop/SubWindow functions, which always dynamically allocate.

`GDrawSync` does nothing on Windows. Maybe `GDrawProcessPendingEvents` - it pumps the event loop and technically anything can happen in that.

**Comment by skef** [comment]
> Can you point out where this is done? I'll take a look later today.

My new code (as of the first jumbo commit to the `stroke` branch) changes `splinestroke.c:MakeStrokeDlg` so that the `StrokeDlg` is a normal stack variable rather than a function-scope static variable. However, I didn't do anything special otherwise to make that work, so it is plausibly the source of the crash on Windows. 

It seems that the function `GradientEdit()` in the same file provides an existing model for allocating a dialog that way, and it uses the calls I copied above. (On the other hand, how many people are likely to have edited gradients recently, particularly on Windows?)

**Comment by jtanx** [comment]
Alright yeah I see what you mean. I'll set up a PR to fix that, I'm 80%ish certain that was the cause of the crash.

**Comment by jtanx** [comment]
(but yeah if we could fix that other valgrind error that'd be good)

**Comment by skef** [comment]
I'll add the `HandleJoin` fix to a future PR.

**Comment by frank-trampe** [comment]
This looks great, and killing a static variable is an added plus.

**Pull request merged**
