### PR TITLE
Croatian for "fontforge/desktop" folder

### PR DESCRIPTION
**Pull request by milotype**
### Type of change
- **New feature**
Added Croatian text to:
- org.fontforge.FontForge.appdata.xml
- org.fontforge.FontForge.desktop
- org.fontforge.FontForge.metainfo.xml

### CODE REVIEW

**Comment by JoesCat** [comment]
LOL, but expected - Croatian to English translation on google not perfect....."system system".
https://www.google.com/search?q=croatian+to+english&ie=utf-8&oe=utf-8

FontForge is free open source software and has been created for various operating systems
  systems. FontForge can be used in graphing mode or via the command line
  line.

Excellent - Thanks for your translation.

...hmmm... appears to have failed travis tests. We're missing a closing summary on the last file.
```c
<summary xml:lang="hr">Uređivač za fontove (needs->)</summary>
```

**Comment by milotype** [comment]
Sorry for the error. I did the correction on my branch. Will this now be pulled, pushed, commited, whatever? (I'm still struggling with all these terms)

**Comment by skef** [comment]
With four commits there's a good chance this'll be "squashed"!

**Comment by JoesCat** [comment]
Yes - good now.
Terminology.
You asked for a pull request (PR) into the master branch.
We merge it into the master branch.

If you were a developer working on this, chances are you would use a command-line program called "git" where you would "fetch", and after editing "push" it to your "fork", and then request a "Pull request" to merge it with master.
Since you're using the web interface, it is not likely you use "push" but more like, use the web interface to upload to your branch.

> With four commits there's a good chance this'll be "squashed"!

Understandably, as a webbrowser user you probably can't upload all these several files in one shot.
...but all the code is related, and the patches are small and understandable, so it will make sense to squash and merge so that the commit is tidy.

@milotype - Thanks for the translation plus fix.

**Pull request merged**
