### PR TITLE
update apt-get install script

### PR DESCRIPTION
**Pull request by wontruefree**
libpng12-dev was not available on my fresh ubuntu install but libpng-dev was

### CODE REVIEW

**Comment by frank-trampe** [comment]
The patch replaces libxml-dev with libxm-dev, which doesn't exist. And, even if it did, of course, the Motif widget kit is not interchangeable with an XML parser.

**Comment by wontruefree** [comment]
I tried to use the browser editor.  That is a weird diff.

**Comment by wontruefree** [comment]
closed in favor of https://github.com/fontforge/fontforge/pull/4069
Dont know what happened.  Seems like an editor bug.

**Comment by frank-trampe** [comment]
Well that's odd.

**Pull request closed without merging**
