### PR TITLE
New menu structure

### PR DESCRIPTION
**Pull request by pathumego**
This is a living PR for work going in implementing new menu structure. 

The proposals and docs are [here](https://drive.google.com/drive/folders/0B-5mpXa8HrFVdkc3ZmhiZ3R4bzA)

Related GH issues [here](https://github.com/fontforge/fontforge/milestones/Menu%20Restructure%20-%201%20)

@larsenwork and @pathumego did the basic proposal with @davelab6 in June 2015. @lpsandaruwan is currently working on implementing this.
### Known issues

This is not extensively tested yet.
- [ ] Some shortcut keys are mixed up or not working.
- [ ] Typos here and there.
- [ ] Extensions menu behaviour. 
### Motivation and Context

The current menu structure of FontForge need some improvements. Some menus need to be rearranged. Some need to be added and some to be removed. The plan is to give users a more  friendly and logical menu system.[ Read more](https://docs.google.com/document/d/1_oWAitHWJadgmUGTt1M7oMBXfElK091cEmSsDaF3saA/edit)
### Description
- [ ] Changes in detail is [here](https://docs.google.com/spreadsheets/d/1jGKa63CDv8SbNjnARMpOPZBsSLRtQT2jEmwk6z7e27o/edit?usp=sharing)

I think considering this is a major UI change, an beta or RC release for new menu structure should be made for feedback and testing. [ Here is a start ](https://github.com/fontforge/fontforge/issues/2335)

### CODE REVIEW

**Comment by JoesCat** [comment]
I haven't looked at the code, but reading this note the mention of accelerators...
This all goes back to keyboard shortcuts when keyboards only had 80 keys, the the first known use of it was wordstar https://www.google.ca/search?q=wordstar+ctrl+character+shortcuts or http://bitsavers.trailing-edge.com/pdf/microPro/Wordstar_3.3/Wordstar_3.3_Reference_Manual_1983.pdf
After that point, other programs started adopting it, or trying to make variants of it.
I think many shortcuts may already be covered, but in terms of hierarchy, I'd suggest, first assign shortcuts as per wordstar original (eg:CTRL+C == copy, etc...), then look at the Windows, MAC, Linux combinations used (Linux is pretty good on the KDE menus as far as I've noted), then, you'll have to apply FontForge overrides or replacements for shortcuts specific to FontForge)....use best judgement in deciding what key is chosen.

**Comment by davelab6** [comment]
FontForge keyboard shortcuts are easy for end users to reconfigure, that
was one of the first big changes @monkeyiq did for me. So I don't think not
having good defaults is a blocker.

**Comment by jtanx** [comment]
Temporarily closing/reopening to trigger AppvVeyor build. But... is this still being worked on at all? I'd be reluctant to add this to the next release because:
1. It's a fairly large changeset, even if it's 'just' to change the menu layout
2. I'm unsure how far it's been tested - and testing all the options is difficult. Perhaps making a test build alongside the normal release build to get other users to see that everything's ok?

**Comment by jtanx** [comment]
> FontForge keyboard shortcuts are easy for end users to reconfigure, 

Using the build from [AppVeyor](https://ci.appveyor.com/project/fontforge/fontforge/build/1.0.42/artifacts), the lack of shortcuts/accelerators is immediately noticeable. Even if this may be the case, I doubt many will actually change the hotkeys from the default values, and in any case, the normal build should provide sensible defaults.

For example, the open shortcut is not there (`Ctrl+O`). Same as for Font Info (`Ctrl+Shift+f`). I can see the same for many other cases where things have been moved around. E.g. In the `Edit` menu, hotkeys are missing for all the options under the `Copy` and `Paste` submenus - where before quite a few of those options had hotkeys.

Other notes:
* The `About->Version` does nothing?
* [Typo](https://github.com/fontforge/fontforge/pull/2724#commitcomment-11786239) still present
* These options seem to be missing??? 
    
    menu
* Which leads to - have we actually checked that all the previous functionality is still available in the new menus (i.e. have we verified that we haven't lost any other options?)

**Comment by davelab6** [comment]
Because we have have not been able to get binary builds, we haven't been
able to test it.

**Comment by davelab6** [comment]
> > @jtanx have we actually checked that all the previous functionality is still available in the new menus (i.e. have we verified that we haven't lost any other options?)
>
> @davelab6 Because we have have not been able to get binary builds, we haven't been
able to test it.

Sorry @jtanx I see that you provided a link to binary builds for Windows - https://ci.appveyor.com/project/fontforge/fontforge/build/1.0.42/artifacts 

@pathumego please can you check the windows build there?

**Comment by ctrlcctrlv** [comment]
A few months have passed with no movement on this issue. I really don't think new menus are going to happen, and am therefore closing this, at least for now; it seems impossible to get agreement on them as @skef said.

Doing so won't cause it to be deleted, and it's just cluttering up the open PRs, and gives the false impression that new menus are a viable place for a new contributor to jump in, which isn't the case.

**Pull request closed without merging**
