### PR TITLE
Make sure scrollbars always have the same width

### PR DESCRIPTION
**Pull request by jtanx**
Not to be merged yet.

This is a follow-up to #2174 with the intention to update this branch as this issue is investigated further by whoever takes this on. cc @frank-trampe

### CODE REVIEW

**Comment by davelab6** [comment]
@frank-trampe this seems like it can be merged to me

**Comment by frank-trampe** [comment]
No. This only hides an insignificantly small part of a deeper problem. We're keeping this open as a reminder that we need to get the root problem fixed.

**Comment by davelab6** [comment]
What root problem do you suspect? :)

**Comment by ctrlcctrlv** [comment]
@frank-trampe, can you please answer @davelab6's query? This PR is years old; I think it should be merged ASAP or else closed, there's no point in keeping it around. I tested it and it does work for me.

**Comment by frank-trampe** [comment]
Okay. Fine with me. The root problem has since fallen far down the priority list and is unlikely to return to the top 10 anytime soon.

**Pull request merged**
