### PR TITLE
Remove breakpad

### PR DESCRIPTION
**Pull request by jtanx**
It's been broken for years, and when it did work, it only worked on Mac. Even then, I don't think it was ever fully functional. It's taking up build time (although the makefile structure was also just inefficient) , so let's just remove it

### CODE REVIEW

**Comment by JoesCat** [comment]
+1 on this recommendation. I've never found a need to use it, and now that you mention it's broken, seems even more convincing to remove it.

**Comment by frank-trampe** [comment]
Let's do this!

**Comment by frank-trampe** [comment]
There's an odd seemingly unrelated error in Travis from this. The build is [here](https://travis-ci.org/fontforge/fontforge/builds/510342933?utm_medium=notification&utm_source=email); the relevant log output follows.

```
Making install in pyhook

make[3]: Nothing to be done for `install-data-am'.

 /usr/local/bin/gmkdir -p '/Users/travis/build/fontforge/fontforge/target/lib/python2.7/site-packages'

 /bin/sh ../libtool   --mode=install /usr/local/bin/ginstall -c   psMat.la fontforge.la '/Users/travis/build/fontforge/fontforge/target/lib/python2.7/site-packages'

  File "<stdin>", line 1

    -e import sys

            ^

SyntaxError: invalid syntax
```

**Comment by jtanx** [comment]
Interesting, I'll take a look

**Pull request merged**
