### PR TITLE
rework cmake install

### PR DESCRIPTION
**Pull request by andiwand**
- install headers from `inc`
- install headers from `fontforge`
- install static library

I am currently trying to get this library built and packaged with conan. While doing so I had to patch the source.
Maybe these patches are interesting for others too.

### Type of change

- **Non-breaking change**

### CODE REVIEW

**Comment by jtanx** [comment]
Not installing headers is intentional, we don't support building against ff.

**Comment by andiwand** [comment]
@jtanx thank you for clarifying! I saw that it is consumed by various projects and packaged with headers (e.g. https://packages.ubuntu.com/bionic/amd64/libfontforge-dev/filelist).
Out of curiosity: are there any plans to support building against fontforge?

**Comment by ctrlcctrlv** [comment]
I recommend linking **without** requiring the headers, as here: https://github.com/MFEK/stroke#linking-to-libfontforge

Define the functions as `extern` in your code, not from a header file.

If that's impractical, guess you'll have to distribute the headers you need yoursel.

**Comment by andiwand** [comment]
@ctrlcctrlv thank you for the suggestion! I will try and see how the effort compares. For structs this would mean copy paste which might be tedious when the fields change.

**Comment by ctrlcctrlv** [comment]
@andiwand True, but the fields rarely change. You can also do what I've worked on a bit; compiling a slimmed down libfontforge.so which only includes the symbols I need, and calling it something else.

Here's an example assuming you primarily want to be able to call `SplineSetStroke` (my use case).

First I copied files I needed…
```
[fred@🍇葡萄🍇libskefstroke]$ ls src
basics.h  edgelist2.h  splinefit.c  splinefont.c  splineorder2.c  splineoverlap.c  splinestroke.c  splineutil2.c  splineutil.c  utanvec.c
dlist.h   edgelist.h   splinefit.h  splinefont.h  splineorder2.h  splineoverlap.h  splinestroke.h  splineutil2.h  splineutil.h  utanvec.h
```

Then wrote a `CMakeLists.txt`…

```cmake
cmake_minimum_required(VERSION 3.10)

project(libskefstroke C)

add_library(skefstroke SHARED src/splinestroke.c)
target_include_directories(skefstroke PUBLIC src)
```

Then just ran the commands…

```
[fred@🍇葡萄🍇libskefstroke]$ cmake -B build -GNinja
-- The C compiler identification is GNU 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/fred/Workspace/libskefstroke/build
[1/2] Building C object CMakeFiles/skefstroke.dir/src/splinestroke.c.o
/home/fred/Workspace/libskefstroke/src/splinestroke.c: In function ‘SplineStrokeAppendFixup’:
/home/fred/Workspace/libskefstroke/src/splinestroke.c:1072:9: warning: implicit declaration of function ‘LogError’ [-Wimplicit-function-declaration]
 1072 |         LogError(_("Warning: Coordinate diff %lf greater than margin %lf\n"),
      |         ^~~~~~~~
/home/fred/Workspace/libskefstroke/src/splinestroke.c: In function ‘SplineSetStroke’:
/home/fred/Workspace/libskefstroke/src/splinestroke.c:2490:9: warning: implicit declaration of function ‘IError’; did you mean ‘perror’? [-Wimplicit-function-declaration]
 2490 |         IError("centerline not handled");
      |         ^~~~~~
      |         perror
[2/2] Linking C shared library libskefstroke.so
[fred@🍇葡萄🍇build]$ file libskefstroke.so 
libskefstroke.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=81fc437a3d55d06da697dcbe124e399630aa8679, not stripped
```

Out of deference to @skef I did not distribute this work, as he plans to do it better (more manually, rewrite the stroke library as a true stand-alone, not obviously torn from FontForge hehe) but you can apply the same idea to your project.

**Comment by ctrlcctrlv** [comment]
Now, based on this output, there's an obvious question of, “would this work as-is?”

### `$ ` `nm -gD libskefstroke.so`
```perl
0000000000005722 T AppendCubicSplinePortion
0000000000005d37 T AppendCubicSplineSetPortion
                 U ApproximateSplineSetFromGen
000000000000835c T ArcClip
                 U __assert_fail@GLIBC_2.2.5
                 U atan2
                 U cabs
                 U calloc@GLIBC_2.2.5
0000000000002c6d T ConvexNibID
                 U cos
                 U csqrt
                 w __cxa_finalize@GLIBC_2.2.5
                 U fmax
                 U free@GLIBC_2.2.5
0000000000006be3 T GenStrokeTracePoints
                 w __gmon_start__
                 U IError
0000000000002b11 T InitializeStrokeInfo
                 U IntersectLines
                 U IntersectLinesSlopes
                 w _ITM_deregisterTMCloneTable
                 w _ITM_registerTMCloneTable
                 U JointBendsCW
                 U log
                 U LogError
                 U MakeUTanVec
                 U malloc@GLIBC_2.2.5
                 U memcpy@GLIBC_2.14
                 U memset@GLIBC_2.2.5
0000000000003c51 T NibIsValid
00000000000042f1 T NibShapeTypeMsg
                 U NormVec
                 U pow
                 U realloc@GLIBC_2.2.5
                 U RealNear
                 U RealWithin
                 U sin
0000000000002be3 T SITranslatePSArgs
                 U SPLCategorizePoints
                 U Spline2DFindPointsOfInflection
                 U SplineCharAddExtrema
                 U SplineCharSimplify
                 U SplineCurvature
                 U SplineIsLinear
                 U SplineIsLinearish
                 U SplineLength
                 U SplineMake3
0000000000005594 T SplineOffsetAt
                 U SplinePointCreate
                 U SplinePointListClearCPSel
                 U SplinePointListCopy
                 U SplinePointListFree
                 U SplinePointListIsClockwise
                 U SplinePointListSelect
                 U SplinePointListTransformExtended
                 U SplineRefigure
                 U SplineSetFindBounds
                 U SplineSetJoin
                 U SplineSetQuickBounds
                 U SplineSetRemoveOverlap
                 U SplineSetReverse
                 U SplineSetsConvertOrder
                 U SplineSetsCorrect
000000000000d6c9 T SplineSetStroke
                 U SplineSolveForUTanVec
00000000000064a1 T SplineStrokeSimpleFixup
                 U SplineTurningCCWAt
                 U SplineUTanVecAt
                 U sqrt
00000000000060f0 T SSAppendArc
                 U SSPSApprox
                 U __stack_chk_fail@GLIBC_2.4
                 U strcmp@GLIBC_2.2.5
0000000000002d7b T StrokeGetConvex
0000000000002cf1 T StrokeSetConvex
0000000000008226 T SVGArcClip
00000000000070ae T TraceAndFitSpline
000000000000cf94 T UnitShape
                 U UTanVecGreater
                 U UTanVecsSequent
```

Answer—probably not, might need some more hacking, but I think that these two strategies (`extern` functions, tearing into libfontforge itself) should have you well on your way to figuring out your use case. :smile:

**Comment by jtanx** [comment]
> Out of curiosity: are there any plans to support building against fontforge?

At the time we dropped header installation, the only thing that actually compiled/linked against  fontforge was pdf2htmlex, which was already running with a forked version.

Given we provide no API/ABI stability guarantees, I don't think we'll be adding this back any time soon.

**Comment by ctrlcctrlv** [comment]
Well, nor should we.

From my POV the best solution is to split up the core more and more, making more libraries similar to `libuninameslist`, `libspiro`. `libskefstroke` was just an idea for a possible next library, but I'd think that we should be able to please most users who'd want to be able to link `libfontforge.so` by instead splitting more and more library-esque material out of core into their own libraries. This is evident from the fact that almost all users who think they want to link `libfontforge.so` in reality only want one or two functions, and would benefit from just abiding by one of my suggested fixes.

Splitting libraries out of core also helps FontForge org.-maintained code survive in increasingly UFO-dominated world.

**Pull request closed without merging**
