### PR TITLE
Added issue & PR templates, closes #2628

### LINKED ISSUE #2628: Add a .github folder with templates for issues and pull requests
The https://github.com/dear-github/dear-github letter has a practical response in https://github.com/blog/2111-issue-and-pull-request-templates

We should add a .github folder with templates for
- [ ] issues and 
- [ ] pull requests

I think it is good to leave the CONTRIBUTING.md file in the root so it is more visible.

### PR DESCRIPTION
**Pull request by divayprakash**

### CODE REVIEW

**Comment by divayprakash** [comment]
ping @davelab6

**Comment by divayprakash** [comment]
ping @davelab6 @frank-trampe

**Comment by davelab6** [comment]
AWESOME!! Thank you so much @divayprakash :D 

Please accept my apologies for my delay

**Comment by divayprakash** [comment]
No problems, just wanted to see this through!

**Pull request merged**
