### PR TITLE
Use .md for markdown license rendering

### PR DESCRIPTION
**Pull request by smileycreations15**
### Types of changes
What types of changes does your code introduce? Check all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description
Rename license to license.md for markdown rendering

### Final checklist
Go over all the following points and check all the boxes that apply. 
If you're unsure about any of these, don't hesitate to ask. We're here to help! Various areas of the codebase have been worked on by different people in recent years, so if you are unfamiliar with the general area you're working in, please feel free to chat with people who have experience in that area. See the list [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#people-to-ask).
- [ ] My code follows the code style of this project found [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#coding-style).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING**](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md) guidelines.

Your pull request will be tested via Travis CI to automatically indicate that your changes do not prevent compilation. FontForge is a big program, so Travis can easily take over 20 minutes to confirm your changes are buildable. Please be patient. More details about using Travis can be found [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#using-travis-ci).  
  
If it reports back that there are problems, you can log into the Travis system and check the log report for your pull request to see what the problem was. If no error is shown, just re-run the Travis test for your pull-request (that failed) to see a fresh report since the last report may be for someone else that did a later pull request, or for mainline code. If you add new code to fix your issue/problem, then take note that you need to check the next pull request in the Travis system. Travis issue numbers are different from GitHub issue numbers.

### CODE REVIEW

**Comment by jtanx** [comment]
Why? I see no benefit to this.

**Comment by ctrlcctrlv** [comment]
@jtanx I'm not writing in favor of this, I declare neutrality. However I believe that if `LICENSE` has an `.md` extension, Github will interpret it correctly. Right now `LICENSE` is Markdown, but doesn't show up as such within the Github interface. https://github.com/fontforge/fontforge/blob/master/LICENSE

It's up to you whether you care about that. Be advised that merging this will cause minor annoyance to some packagers when their automated scripts fail to find our license.

**Comment by smileycreations15** [comment]
@ctrlcctrlv No, GitHub interprets it correctly.  
From the [help center](https://help.github.com/en/articles/adding-a-license-to-a-repository):
> 3. In the file name field, type LICENSE or _LICENSE.md_ (with all caps).

<sup>(emphasis mine)</sup>
Check the licence on my fork to see if it works correctly.

**Comment by frank-trampe** [comment]
@smileycreations15, @ctrlcctrlv was saying that the current license file is not rendering as markdown, not that a renamed license file would not render as such. It does make sense to me that a file written in markdown would have the `.md` extension. We cannot merge this as-is, though, since it breaks the build.

```
$ if [ ! -z "$LINUX_FULL" ]; then make distcheck; fi
make  dist-gzip am__post_remove_distdir='@:'
make[1]: Entering directory '/home/travis/build/fontforge/fontforge'
make[1]: *** No rule to make target 'LICENSE', needed by 'distdir'.  Stop.
make[1]: Leaving directory '/home/travis/build/fontforge/fontforge'
Makefile:983: recipe for target 'dist' failed
make: *** [dist] Error 2
The command "if [ ! -z "$LINUX_FULL" ]; then make distcheck; fi" exited with 2.
```

We would thus need to make some build system adjustments and, as @ctrlcctrlv mentions, we might need to make some accommodation for packagers who depend upon the file being in its present location, such as copying it to its old location during the distdir build.

**Comment by smileycreations15** [comment]
@frank-trampe A symlink is enough I think.

**Comment by smileycreations15** [comment]
@frank-trampe The issue is fixed. The error in AppVeyor is a key fetch error.

**Comment by frank-trampe** [comment]
Good. @jtanx, does this seem safe to you?

**Comment by jtanx** [comment]
I have a feeling this will break the dist bundle, because you've symlinked LICENSE to LICENSE.md but haven't included LICENSE.md as part of the dist bundle.

I'd also prefer if we just had one file instead of creating a symlink, otherwise now we'll have 3 files just to describe the license (LICENSE.md, LICENSE and COPYING.gplv3)

**Comment by smileycreations15** [comment]
Still waiting...

**Comment by ctrlcctrlv** [comment]
If you don't want to verify that @jtanx's concerns are either (a) not concerns or (b) fixed there's no reason to keep waiting, just close this yourself.

**Comment by smileycreations15** [comment]
Both checks succeded. I think this should be merged now.

**Comment by ctrlcctrlv** [comment]
I'll close this for you as you have no intention of understanding why we don't want to merge this in its current form. Automatic checks passing doesn't mean this should be merged. 

PR was rejected.

**Pull request closed without merging**
