### PR TITLE
Remove graphicore and IPython checks

### PR DESCRIPTION
**Pull request by skef**
This gets rid of `pycontrib/graphicore` and the related checks for IPython. This is in preparation for/part of removing `pycontrib/gdraw`. 

I'll update the Wiki once I have a request number. 

### Types of changes
What types of changes does your code introduce? Check all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist
Go over all the following points and check all the boxes that apply. 
If you're unsure about any of these, don't hesitate to ask. We're here to help! Various areas of the codebase have been worked on by different people in recent years, so if you are unfamiliar with the general area you're working in, please feel free to chat with people who have experience in that area. See the list [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#people-to-ask).
- [x] My code follows the code style of this project found [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#coding-style).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md) guidelines.

### CODE REVIEW

**Comment by skef** [comment]
Wiki updated

**Comment by ctrlcctrlv** [comment]
I want to maybe complain a bit about this. I might not understand it fully so let me be conscientious in my complaint so as not to offend.

As far as IPython goes, I have no objection to it's removal.

But robust GUI access from Python seems a necessity if we want to make Python plugins users can install á la WeeChat.

So I must question your removal of graphicore. Maybe not all is necessary, but certainly some is. Plugins need to be able to make dialogs, right? And access gdraw literals...

**Comment by ctrlcctrlv** [comment]
I retract my comment, I was confusing graphicore with gdraw.py / _gdraw.py.

Sorry for my ignorance, I hope it did not trouble you

**Comment by skef** [comment]
First, "graphicore" has always been a misnomer. That directory just contains `ipython_view.py` and some supporting files to open the window, not the `gdraw` interfaces. 

But second, the gdraw interfaces are really gxdraw interfaces. `pycontrib/gdraw` is, in effect, a trick that tries to kludge GTK event processing into the X version of gdraw. As I remember you're one of the advocates for switching to GGDKDraw as the default interface, and the two approaches are entirely incompatible. 

It would be a good thing for FontForge to support some kind of graphics layer for extensions, and GTK is  the most viable candidate. I have a version of that more or less working [over here](https://github.com/jtanx/fontforge/pull/2). However, some aspects need more thought.

**Comment by ctrlcctrlv** [comment]
@skef Sure, let's make gdraw.py use GDK! :)

I feel like to have a successful scripting ecosystem that's easy for users and installable just by clicking e.g. "Install Plugins" in FontForge, we're going to need some way to create UI elements from within scripts.

**Comment by skef** [comment]
@ctrlcctrlv After this is merged I'm going to submit a gdraw removal too, so you can paste your concerns into that one ...

**Comment by skef** [comment]
@ctrlcctrlv if you have access to GTK why would you use GDraw? Remember that what "GDraw" refers to is GW's custom graphics layer. If FontForge could service a GTK event loop there's no reason an extension would have to or want to do anything with GDraw.

**Comment by ctrlcctrlv** [comment]
Removing gdraw.py without a plan to replace it seems like a step backwards IMO...

Are you aware of Inkscape's extensions? You can create dialogs and get much information from the user. There's hardly a script we'd want to put in the Tools menu where that wouldn't be useful.

**Comment by ctrlcctrlv** [comment]
> if you have access to GTK why would you use GDraw?

You wouldn't, but under GDK do Python scripts _really_ have access to GTK?

**Comment by ctrlcctrlv** [comment]
I'm sorry we're chatting about this in an unrelated issue btw, I definitely deserve the Dunce of the Day award for thinking graphicore was the, ahem, _graphics core_, :desktop_computer: ...

**Comment by skef** [comment]
@ctrlcctrlv You're more or less asking for `pycontrib/gdraw` to be left as a ritualistic representation of some other actually viable interface.

**Comment by jtanx** [comment]
I 100% support removing gdraw.py, as mentioned, it's a giant kludge that doesn't work under ggdkdraw anyway.

I have some plans to reimplement that gdk stuff under gtk anyway, and potentially some of skef's work on that gtk bridge might come in handy too. *Once* that is in place, we can consider how we want to allow interop from python.

**Comment by skef** [comment]
@jtanx I'm staging this removal separately from `pycontrib/gdraw` mostly for record-keeping purposes.

**Comment by ctrlcctrlv** [comment]
`pycontrib/gdraw` is aspirational. I fear just removing it instead of replacing it will send the wrong message, that we don't want to be able to create GUI elements in Python.

What harm is caused by leaving it alone until its replacement is ready?

**Comment by skef** [comment]
> What harm is caused by leaving it alone until its replacement is ready?

Among other things it attempt to link in a shared library that probably won't be built after @jtanx's build infrastructure changes.

**Pull request merged**
