### PR TITLE
Fix & complete the names list symbol replacements

### PR DESCRIPTION
**Pull request by dscorbett**
See fontforge/libuninameslist#21.

### Type of change
- **Non-breaking change**

### CODE REVIEW

**Comment by ctrlcctrlv** [comment]
@JoesCat Can you please merge https://github.com/fontforge/libuninameslist/pull/21 or comment on it if it should not be merged? That way this can also be merged.

**Comment by ctrlcctrlv** [comment]
Does this assume fontforge/libuninameslist#21 will be merged or can it be merged separately @dscorbett ?

**Comment by dscorbett** [comment]
The other PR just updates some comments, so this one doesn’t strictly speaking depend on it. I think they should be reviewed and merged together, since if the other PR is wrong, so is this one.

**Comment by ctrlcctrlv** [comment]
Per fontforge/libuninameslist#21

**Pull request merged**
