### PR TITLE
Add more OpenType table names

### PR DESCRIPTION
**Pull request by MaddTheSane**
This adds table names for some OpenType tables.

### Motivation and Context
- [X] Why is this change required? What problem does it solve?
This adds more OpenType table names.
- [ ] If it fixes an open issue, include the text `Closes #1` (where 1 would be the issue number) to your commit message.
Somewhat related to #2882.

### Types of changes
What types of changes does your code introduce? Check all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description
- [X] Describe your changes in detail.
This adds descriptions for the following tables: CBDT, CBLC, CFF2, HVAR, MERG, meta, MVAR, six, STAT, 'SVG ', and VVAR.

### Final checklist
- [X] My code follows the code style of this project found [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#coding-style).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING**](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md) guidelines.

### CODE REVIEW

**Comment by ctrlcctrlv** [comment]
Hi - why add these table names when FontForge provides no UI for editing them?

**Comment by MaddTheSane** [comment]
For future work. And for reference.

Also, there are already tables in the list that aren't currently supported by FontForge (the justification tables, `Zaph`, for starters).

**Comment by ctrlcctrlv** [comment]
So if FontForge doesn't know how to edit a certain table will it just appear greyed out, or ... ?

**Comment by MaddTheSane** [comment]
It pops up in the warnings window. With this patch, it says what the unreadable table is.

**Comment by skef** [comment]
> So if FontForge doesn't know how to edit a certain table will it just appear greyed out, or ... ?

These aren't the lookup names, as in the Lookups dialog, but a level above that. The risk would be FontForge's logic thinking it knew more about one of these tables than it does. 

@MaddTheSane: for potential reviewers, can you add some references to code points (filename/line number or just quoted code) verifying the safety of these changes?

**Comment by MaddTheSane** [comment]
This specific table is only referenced four times in the source code, all in reference to printing info about unknown tables (look for `stdtables`):
https://github.com/fontforge/fontforge/blob/b561e1aa3a1ca6b971f6dcc21e06d2cea7104547/fontforge/parsettf.c#L1232-L1240

**Comment by ctrlcctrlv** [comment]
Referring to the tag that way (`%c%c%c%c`, then bitshifting for some reason to get the table name) can't be a good programming practice, can it?

**Comment by MaddTheSane** [comment]
It's probably the fastest way to print an ASCII FourChar instead of byte-swapping (on Little Endian machines), copying the resulting integer into a temporary buffer, and print the resulting string out.

Note that I did not directly touch the code that references `stdtables`.

**Pull request merged**
