### PR TITLE
French Translation for the modified Panose labels

### PR DESCRIPTION
**Pull request by jrbastien**
### Motivation and Context
A few labels on the Panose classification screen were modified on January 10th 2017.  Theses changes affect all POs as the strings become missing once the original texts are modified.

### Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description
- All Panose labels that were modified have been translated again.
- Some French Panose classifications were reviewed and adjusted at the same time.
- Also changed the "Advance Width Metrics for ..." screen title as it was incorrectly translated.

### Final checklist
- [X] My code follows the code style of this project found [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#coding-style).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING**](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md) guidelines.

Your pull request will be tested via Travis CI to automatically indicate that your changes do not prevent compilation. FontForge is a big program, so Travis can easily take over 20 minutes to confirm your changes are buildable. Please be patient. More details about using Travis can be found [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#using-travis-ci).  
  
If it reports back that there are problems, you can log into the Travis system and check the log report for your pull request to see what the problem was. If no error is shown, just re-run the Travis test for your pull-request (that failed) to see a fresh report since the last report may be for someone else that did a later pull request, or for mainline code. If you add new code to fix your issue/problem, then take note that you need to check the next pull request in the Travis system. Travis issue numbers are different from GitHub issue numbers.

### CODE REVIEW

**Comment by JoesCat** [comment]
Thanks @jrbastien - most appreciated for these improvements!

**Comment by jrbastien** [comment]
@JoesCat , do you know who maintain the fontforge ppa?  My completed translation was merged a day or two after the last updates to the PPA in October.

It would be nice if I could advertise that the full translation is available through PPA.

**Comment by JoesCat** [comment]
Hi @jrbastien, frank-trampe and jtanx are the developers that usually handle releases since they are already setup to test and develop on Windows and Mac too. There was a request by davelab6 to have a release sometime in December, but we missed that date. If you look at the latest "issues" there appears to be a recurring theme with duplicate fonts and saving files, these are being reported by users running HEAD, so I suspect something recently introduced is possibly causing problems. If the problem is in HEAD, it would cause a cascade of a larger waterfall of issues if we created a release at this time (because the distros watching for TAG releases would then grab a copy, and a much larger audience would be replying with the same errors).
The group of developers is fairly small for a program of this size, so it really comes down to, "Does it look like a good time to release?". The answer to that (from my point of view) comes down to free-time, has the issues settled-down a bit, did we hit any significant change or enough changes to merit a release?
The Distros also have their own release cycles too, which are anything from 1..3 years for Debian and Redhat, to a quicker pace for Fedora and Ubuntu, to rolling for Arch.
Sort of an answer, but not quite an answer.

**Comment by jrbastien** [comment]
Thanks for the lengthily explanation.  I understand the point of stability.  I will be patient...

**Comment by JoesCat** [comment]
When replying with mailing lists and public forums, it can often be better to reply as if answering ten people. This reduces the need for someone else to ask for clarification X and someone else asking of Y and another of Z.

It tends to look a bit long-winded to the person spoken to :-)

**Pull request merged**
