### PR TITLE
ggdkdraw.c: use the undocumented gdk_win32_selection_add_targets to fix copying on windows

### LINKED ISSUE #4228: copy to clipboard not working
it's not possible to copy any text and paste outside of fontforge on windows 10 (i think the issue exist in all release after 2017)

### PR DESCRIPTION
**Pull request by jtanx**
See also:
https://gitlab.gnome.org/GNOME/gtk/-/issues/2523

### Type of change
- **Bug fix**

Fixes #4228

### CODE REVIEW

**Comment by jtanx** [comment]
From the gnome issue thread, it was suggested I also call gdk_win32_selection_clear_targets before calling gdk_win32_add_targets, which unfortunately means a little bit more hackery.

**Comment by ctrlcctrlv** [comment]
@jtanx I am using Windows against my will. Can I request a "point release" be made? This bug is very annoying when using Execute Script dialog. I know you're very busy, but I'd appreciate a new build at the very least.

**Comment by frank-trampe** [comment]
Do [the AppVeyor binaries](https://ci.appveyor.com/project/fontforge/fontforge/build/artifacts) not work?

**Comment by jtanx** [comment]
I built the installer (along with all the other customary patches) if that's what you were after: https://sourceforge.net/projects/fontforgebuilds/files/i686/Installer/FontForgeSetup-06-04-2020.exe

**Pull request merged**
