### PR TITLE
splinefit.c: Improvements to merge/simplify

### PR DESCRIPTION
**Pull request by Alatius**
**Bug fix** for problems discussed in #5093. My changes are described and explained there.

### CODE REVIEW

**Comment by ctrlcctrlv** [comment]
@linusromer: Thoughts? :)

**Comment by linusromer** [comment]
I have tested the new "merge" and "simplify" with some fonts and some special situations: I believe that [https://github.com/fontforge/fontforge/pull/5095/commits/2a0b4a631940f78fefa72c0f4adf65967f594e24](https://github.com/fontforge/fontforge/pull/5095/commits/2a0b4a631940f78fefa72c0f4adf65967f594e24) is a good idea - it may even speed up things slightly. 
I am not that sure about [https://github.com/fontforge/fontforge/pull/5095/commits/15d5ca921ceb1adf2178a0babd6c1613b9f8967b](https://github.com/fontforge/fontforge/pull/5095/commits/15d5ca921ceb1adf2178a0babd6c1613b9f8967b) but for me it seems to work and fix the bug. This may need a bit more testing with expanding strokes.

**Comment by linusromer** [comment]
I have tested the new "merge" and "simplify" with some fonts and some special situations: I believe that [https://github.com/fontforge/fontforge/pull/5095/commits/2a0b4a631940f78fefa72c0f4adf65967f594e24](https://github.com/fontforge/fontforge/pull/5095/commits/2a0b4a631940f78fefa72c0f4adf65967f594e24) is a good idea - it may even speed up things slightly. 
I am not that sure about [https://github.com/fontforge/fontforge/pull/5095/commits/15d5ca921ceb1adf2178a0babd6c1613b9f8967b](https://github.com/fontforge/fontforge/pull/5095/commits/15d5ca921ceb1adf2178a0babd6c1613b9f8967b) but for me it seems to work and fix the bug. This may need a bit more testing with expanding strokes.

**Comment by Alatius** [comment]
> I am not that sure about [15d5ca9]

Is there anything in particular that makes you hesitate? The change to use `to->prev` when `tlen==0` seems to me to be quite straight-forward. To the extent that I myself have doubts, it boils down to me not quite understanding under what circumstances the code block starting at line 752 is even supposed to be executed, i.e., I don't know how it can occur that `from->next == NULL` (or `to->prev == NULL`). Lacking input data to test on where this is the case, I have never seen this code being run, and thus I have been unable to test the effect. But in any case, I don't see how it would have any adverse effects (supposing that it is ever executed), compared to the result of the code before this commit.

**Comment by linusromer** [comment]
> Is there anything in particular that makes you hesitate?

No. Many things in FontForge depend on `splinefit.c` and sometimes it is hard to predict how it will affect things in FontForge (e.g. rounding problems of near zero values seem to have been quite a struggle). I would not have commented on this particular commit if not ctrlcctrlv had asked me about my thoughts. So I am just saying: I am not sure about this commit.

**Comment by ctrlcctrlv** [comment]
I've merged it as it also looks fine to me, but you are indeed right that it's hard to predict. I have a ton of fonts that use Expand Stroke though and none broke, sometimes the only way we can get feedback on it is to merge. Wouldn't be upset if it's reverted of course.

**Pull request merged**
