### PR TITLE
Remove defunct readmes from makefile, other final touches

### PR DESCRIPTION
**Pull request by jtanx**
Follow-up to #3534

### CODE REVIEW

**Comment by skef** [comment]
*sigh* sorry about that

**Comment by jtanx** [comment]
no worries, I missed it too

**Comment by skef** [comment]
Wait, before we decide on this in particular, what docs *do* go into the dist. Is there no INSTALL-git.md or README.md or CONTRIBUTING.md?

**Comment by skef** [comment]
I recommend tossing in INSTALL-git.md, .travis.yml renamed to "travis.yml", and CONTRIBUTING.md And then maybe making a text version of README.md.

**Comment by jtanx** [comment]
Files that get added are what gets added to the dist bundle. Those files are left out because they're repo-specific and not distribution specific files. Like you can't contribute code from a dist bundle

**Comment by jtanx** [comment]
Also you wouldn't include the travis.yml as part of the bundle, as that's definitely just a CI/repo only thing

**Comment by skef** [comment]
OK, but *some* kind of documentation seems needed, and just adding back the ancient READMEs isn't a great solution.

**Comment by skef** [comment]
(I was making that list based on what README.md refers to.)

**Comment by jtanx** [comment]
I believe that there is an INSTALL file that gets added to the release tarball, but I mean, really it's no different to most other projects, literally `./configure; make; make install`.

**Comment by skef** [comment]
How about adding a link to the repo to the top of INSTALL, noting that more complete information is available there?

**Comment by jtanx** [comment]
We symlink in a generic INSTALL from gnulib, which then calls to refer to README for more detailed info

**Comment by skef** [comment]
Shall I construct a short README that we we can put back in the docs directory to refer to the repo, and we can include it as the others were being included?

**Comment by jtanx** [comment]
Ah yeah, I  just added in a super basic one, but feel free to modify it as you see fit (and maybe move it into the docs folder)

**Comment by skef** [comment]
I added a link to the main site. Seems sufficient.

**Comment by skef** [comment]
... and added the new README into the top-level Makelile.am

**Comment by JoesCat** [comment]
latest merges still can use an update to tests/Makefile.am to include 4 missing files:
```code
diff -r fontforge-20190317/tests/ ../f/tests/
Only in ../f/tests/: runtests
Only in ../f/tests/: test0002.py
Only in ../f/tests/: test931.py
Only in fontforge-20190317/tests/: testsuite
```
this might be a good place to add it, but I leave this to you as you're patching...
# test fonts
EXTRA_DIST +=  somewhere in one of these extra_dist equations....

**Comment by JoesCat** [comment]
my err, make that 3 files, not 4, ignore the testsuite....

**Comment by skef** [comment]
runtest was last modified in 2008 and won't work with any test that requires an argument (like any that modifies a font).

**Comment by JoesCat** [comment]
did another diff. osx directory missing these on 'make dist':
```code
Only in osx/: archive-and-upload.sh
Only in osx/FontForge.app/Contents/Frameworks/Breakpad.framework: Breakpad
Only in osx/FontForge.app/Contents/Frameworks/Breakpad.framework: Headers
Only in osx/FontForge.app/Contents/Frameworks/Breakpad.framework: libBreakpad.dylib
Only in osx/FontForge.app/Contents/Frameworks/Breakpad.framework: Resources
Only in osx/FontForge.app/Contents/Frameworks/Breakpad.framework/Versions/A/Resources/crash_report_sender.app/Contents/Resources: da.lproj
Only in osx/FontForge.app/Contents/Frameworks/Breakpad.framework/Versions/A/Resources/crash_report_sender.app/Contents/Resources: de.lproj
Only in osx/FontForge.app/Contents/Frameworks/Breakpad.framework/Versions/A/Resources/crash_report_sender.app/Contents/Resources: es.lproj
Only in osx/FontForge.app/Contents/Frameworks/Breakpad.framework/Versions/A/Resources/crash_report_sender.app/Contents/Resources: fr.lproj
Only in osx/FontForge.app/Contents/Frameworks/Breakpad.framework/Versions/A/Resources/crash_report_sender.app/Contents/Resources: it.lproj
Only in osx/FontForge.app/Contents/Frameworks/Breakpad.framework/Versions/A/Resources/crash_report_sender.app/Contents/Resources: ja.lproj
Only in osx/FontForge.app/Contents/Frameworks/Breakpad.framework/Versions/A/Resources/crash_report_sender.app/Contents/Resources: nl.lproj
Only in osx/FontForge.app/Contents/Frameworks/Breakpad.framework/Versions/A/Resources/crash_report_sender.app/Contents/Resources: no.lproj
Only in osx/FontForge.app/Contents/Frameworks/Breakpad.framework/Versions/A/Resources/crash_report_sender.app/Contents/Resources: sl.lproj
Only in osx/FontForge.app/Contents/Frameworks/Breakpad.framework/Versions/A/Resources/crash_report_sender.app/Contents/Resources: sv.lproj
Only in osx/FontForge.app/Contents/Frameworks/Breakpad.framework/Versions/A/Resources/crash_report_sender.app/Contents/Resources: tr.lproj
Only in osx/FontForge.app/Contents/Frameworks/Breakpad.framework/Versions/A/Resources: Info.plist
Only in osx/FontForge.app/Contents/Frameworks/Breakpad.framework/Versions: Current
Only in osx/: fontforge-debug-lldb-script.txt
Only in osx/: fontforge-debug-lldb.sh
Only in osx/: force-rebuild.sh
Only in osx/: mac-Resources
Only in osx/: make-package.sh
```

**Comment by skef** [comment]
This is merged. Let's continue whatever discussion is to be had at #3548

**Pull request merged**
