### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by jtanx**
### Type of change

- **Non-breaking change**

### CODE REVIEW

**Comment by frank-trampe** [comment]
I can't find my calendar. Somebody else is going to need to review this one.

**Review by skef — APPROVED** [review]
lgtm

**Comment by frank-trampe** [comment]
The test failure is silly and spurious.

```
attribute-invalid     : <release> timestamp is in the future
```

**Comment by skef** [comment]
What's the opposite of "agile"? Clumsy? Sluggish?

**Comment by ctrlcctrlv** [comment]
> What's the opposite of "agile"?

me

**Pull request merged**
