### PR TITLE
Update list of supported MIME types

### PR DESCRIPTION
**Pull request by alexhenrie**
This adds font/woff and font/woff2 and renames application/x-font-otf
and application/x-font-ttf to font/otf and font/ttf.

Provide a general summary of your changes in the **Title** above.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### Motivation and Context
- [x] Why is this change required? What problem does it solve?
- [ ] If it fixes an open issue, include the text `Closes #1` (where 1 would be the issue number) to your commit message.

### Types of changes
What types of changes does your code introduce? Check all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description
- [x] Describe your changes in detail.

### Final checklist
Go over all the following points and check all the boxes that apply. 
If you're unsure about any of these, don't hesitate to ask. We're here to help! Various areas of the codebase have been worked on by different people in recent years, so if you are unfamiliar with the general area you're working in, please feel free to chat with people who have experience in that area. See the list [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#people-to-ask).
- [x] My code follows the code style of this project found [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#coding-style).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md) guidelines.

Your pull request will be tested via Travis CI to automatically indicate that your changes do not prevent compilation. FontForge is a big program, so Travis can easily take over 20 minutes to confirm your changes are buildable. Please be patient. More details about using Travis can be found [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#using-travis-ci).  
  
If it reports back that there are problems, you can log into the Travis system and check the log report for your pull request to see what the problem was. If no error is shown, just re-run the Travis test for your pull-request (that failed) to see a fresh report since the last report may be for someone else that did a later pull request, or for mainline code. If you add new code to fix your issue/problem, then take note that you need to check the next pull request in the Travis system. Travis issue numbers are different from GitHub issue numbers.

### CODE REVIEW

**Comment by skef** [comment]
Are you perhaps updating this list based on MIME types currently recommended for labeling new content? MIME-labeled content can stick around for long periods (in email archives, for example), so the list that FontForge accepts should include the old and the new strings for a given type.

**Comment by ctrlcctrlv** [comment]
@skef The XDG MIME specification uses a distribution provided MIME database. So really this patch's correctness is very hard to gauge. You're right that to support more distros we should keep the old ones though.

https://wiki.archlinux.org/index.php/XDG_MIME_Applications#New_MIME_types

**Comment by skef** [comment]
If there's something in the database itself to map from old x- to new types internally, then it's definitely less important that FontForge keep the old ones. But not necessarily of no importance. Unless keeping both is harmful somehow it seems best to keep all of them.

**Comment by alexhenrie** [comment]
Right, the shared-mime-info package handles the translation from deprecated names like "application/x-font-ttf" to the standard name "font/ttf". The standard names [font/ttf and font/otf](https://tools.ietf.org/html/rfc8081) were created in Feburary 2017, and both [TTF](https://gitlab.freedesktop.org/xdg/shared-mime-info/commit/c50e192b11b46092859f0d9ca261e09a054aebe4) and [OTF](https://gitlab.freedesktop.org/xdg/shared-mime-info/commit/c96c8e7634ba2aac05ecc6684607f591d27086f7) were updated in shared-mime-info immediately.

The big thing for me is getting font/woff and font/woff2 on the list. If you prefer, I can change the patch to simply append these two types and leave the rest alone.

**Comment by skef** [comment]
Can we just make it a superset of what you've added and what was there before (e.g. keep `application/x-font-ttf` while adding `font/ttf`)? I realize this "desktop" distribution mechanism is fairly new, but that would keep systems with outdated MIME DBs working as before. (Someone can always come in in another five years and clean out the cruft.)

**Comment by ctrlcctrlv** [comment]
Agreed with @skef...distros from 2017 aren't THAT old, are they?

**Comment by alexhenrie** [comment]
@skef, I just force-pushed a new commit to my branch that does exactly what you asked.

**Comment by skef** [comment]
"We" have to think about `gutils/g_giomime.c` too, but I don't see how that's @alexhenrie's problem.

**Comment by alexhenrie** [comment]
I just force-pushed again because I realized that you're going to want application/font-woff on the list too for the benefit of old distros.

**Comment by skef** [comment]
Strange but sure enough: no "x-" on that one.

**Pull request merged**
