### PR TITLE
Fix generateFontPostHook being called instead of generateFontPreHook

### PR DESCRIPTION
**Pull request by teatimeguest**
This PR fixes a bug where `generateFontPostHook` is called instead of `generateFontPreHook` just before generating a font in a Python script.
### Type of change
- **Bug fix**

### CODE REVIEW

**Comment by iorsh** [comment]
It looks good to me. @teatimeguest could you please merge the latest fontforge:master?

**Comment by teatimeguest** [comment]
@iorsh Done.

**Comment by iorsh** [comment]
> @iorsh Done.

Thanks! @skef, could you please review?

**Review by skef — APPROVED** [review]
lgtm

**Pull request merged**
