### PR TITLE
Add new blank hr.po file. Supplements info in issue #3797

### PR DESCRIPTION
**Pull request by JoesCat**
hr.po file prepared for Croatian translation.
Needs attention @milotype if ok to use.

### CODE REVIEW

**Comment by ctrlcctrlv** [comment]
Hey guys, why not just use something user friendly like Transifex? I used that in a previous job of mine to make it so users didn't have to know anything to translate. It seems excessive to make them ask us, then commit an empty po for them, then have them PR.

Maybe okay just this once since it's already done, but in future Transifex would result in a lot more translation work being done... Especially if put on the website and CONTRIBUTING.md

**Comment by frank-trampe** [comment]
We definitely can't afford Transifex. Is there a free product that you would recommend?

**Comment by ctrlcctrlv** [comment]
@frank-trampe Last I knew&hellip;Transifex was free for open source projects. Has that been discontinued?

**Comment by ctrlcctrlv** [comment]
>What are the basic requirements to qualify as an Open Source account?

https://www.transifex.com/pricing/

>We are proud and humbled to be hosting the largest Open Source translation community in the world. _We offer Transifex for free to Open Source projects that have no funding, revenue, and/or commercialization model._ If you have a question whether your organization qualifies for our Open Source program, please contact us.

I'm happy to contact them if we want more and easier translations. This project would almost certainly qualify. Last I knew all you had to do was register, but it looks like people were abusing that so now contact must be made :man_shrugging:

**Comment by JoesCat** [comment]
Hi @ctrlcctrlv,
This morning I looked at the outside of a box, which has written on it:
It's as easy as 1,2,3!
C'est simple comme bonjour!
...basically the English and French translations (above) technically mean two different things, but the intended meaning is the same.
I've run into similar problems with Google translate and other translators, where the technical meaning may be correct, or seem a bit odd to the intended reader in the other language.
In Summary, sometimes, having a one-to-one translation does not mean what you want to mean, and as good as computerized translators may be today, people are still better at translating.

As another example, my spell checker on my phone - similar problem, you think it may be good, but then it replaces words because it thinks the other word is better. ...and this is English with no translation, may be good for common english, but certainly not good enough for technical conversation in English.
If someone like @milotype is offering to do a translation, I would opt to go with a human translation.
The benefits are, it is done by someone who has an interest in doing it, is likely in-tune with fonts and know the technical lingo (because they came to the website, we did not go out hunting for help), and it may even be benefiting the person offering to help in some way, example,maybe FontForge is a tool they like, or the work they put into translation helps them as proof of being able to translate (if looking for work), or can be for any number of other reasons.

I looked briefly at the suggested website and it too basically says there might be an army of translators sitting behind the engine in-wait, that may have to look at whatever output the computerized results push out...and maybe the translators looking at the results might not be as interested in verifying the results. FontForge has technical jargon that is not common in English, so it may be missed by the translation engine, or the army of translators in wait to fix translate errors.
Translation engines may get better, but for the moment, now, my vote is to go with @milotype 's offer for help.
:-)

**Comment by ctrlcctrlv** [comment]
@JoesCat Transifex is not an automatic translator, but rather a graphical interface for working with gettext (and I assume other l10n packages, but I only ever worked with gettext). Basically, it lets people translate, then you sync it with your project's repo whenever convenient (for us, most likely at the time of a new release). It handles the creation of `.po` files, and also informs translators when there are new strings that need translating.

**Comment by ctrlcctrlv** [comment]
(I think that Transifex might also allow translators to look at "translation memory" if a string is a 1:1 match, which come from other projects...but a real person still has to approve them.)

**Comment by ctrlcctrlv** [comment]
An alternative would be [translatewiki.net](https://translatewiki.net/wiki/Translating:New_project)&mdash;it works like Transifex except is open source and is used by MediaWiki and OpenStreetMap...so we don't have to rely on a proprietary tool that might disappear at any moment, seeing how they've already restricted free accounts to those who contact them.

**Comment by milotype** [comment]
> hr.po file prepared for Croatian translation.
> Needs attention @milotype if ok to use.

Thank you. I've downloaded the hr.po file. 
Just to let you know, it's **not** completely empty. Also, it has 7247 strings. All other po-files have 724**8** (I've downloaded the whole package a couple of days ago from the master branch).
So maybe you can double-check the hr.po file, before continuing.

Basically I've started already with translating into croatian. I simply copied the german po file, deleted all translations, did the necessary changes in the header, and now I have a "croatian" po-file. Nevertheless, I always prefer to start or update with current pot files, becuase usually there are changes in those "hashed" lines (sorry, I don't know what they are called).
```
#: ../fontforge/autotrace.c:592
msgid "Nothing to trace"
msgstr ""
```

**Comment by milotype** [comment]
A bit off topic here, but please give me some advice, how to use my croatian locale in FontForge. I need to check my translations within the app. I've already read everything from issue "Interface language #2443", but it doesn't help me.
For all apps I did translation, I usually copy the .mo file into the appropriate places. 
What I have, is MacOSX 10.11.6, FontForge version 20190413
So for FontForge I placed it into:
`/Applications/FontForge.app/Contents/Resources/opt/local/share/locale/hr/LC_MESSAGES/FontForge.mo`
Still FontForge starts with english. All other apps start correctly. What am I missing? Please bear with me, I'm no programmer …

**Comment by jtanx** [comment]
Try doing

```sh
export LANGUAGE=hr
/Applications/FontForge.app/Contents/MacOS/FontForge #This is from memory, so this might be wrong, you need to invoke fontforge
``

The po files shouldn't be too out of date, they were fairly recently refreshed.

**Comment by ctrlcctrlv** [comment]
In re: translatewiki.net, I chatted with them a bit on IRC and all we'd need to do is give one of them push access. They'd handle everything else, including syncing translations. Seems like a pretty sweet deal to me, and we can just send @milotype there to do his translation.

@frank-trampe @jtanx will you support this? I vote yes

**Comment by milotype** [comment]
@jtanx Your suggestion doesn't work, or I (as a NON-PROGRAMMER) just don't know how to do such things. This is what I tried:

**1. try**. In terminal, paste everything in one line:
```
MacBookPro:~ milo$ export LANGUAGE=hr /Applications/FontForge.app/Contents/MacOS/FontForge
-bash: export: `/Applications/FontForge.app/Contents/MacOS/FontForge': not a valid identifier
```
Result: nothing happens.

**2. try**: In terminal, paste as you typed in your last message (in 2 lines):
```
MacBookPro:~ milo$ export LANGUAGE=hr
MacBookPro:~ milo$ /Applications/FontForge.app/Contents/MacOS/FontForge
PKGBASE: /Applications/FontForge.app
Copyright (c) 2000-2018 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 09:36 UTC 13-Apr-2019-ML-D.
 Based on source from git with hash: 7f6f1d021fdfea7789972f9534ba3241616d8dfc
```
Result: FontForge starts, but still in english.

**3. try**: In the folder /Applications/FontForge.app/Contents/MacOS, I manipulated the files "Attach-Debugger-to-running-FontForge" and "FontForge" by changing the line 62 with 
`export LANG=en_US.UTF-8` into `export LANG=hr.UTF-8`.
Double click FontForge, still english.

Help please!

**Comment by milotype** [comment]
BTW, I've also notice that there are 3 other issues about using locale setting (#2443 closed, #176 open, #2398 open). Any plans to resolve them? 
And how do users for other langauages get FontForge displayed in their langauges? I understand that there aren't many languages translated, but it's a pitty if even those ones don't work.

**Comment by JoesCat** [comment]
Hi @milotype - the .mo file is generated from the .po file, so if you cannot "make" fontforge, the .mo is the same as earlier, which in this case originally was english, therefore remains english.
We need to "make" your latest .po file

As you appear to be lacking make capability, and on top of this you're running MAC, it present a bit of a challenge here to help you. At the moment, I think the easiest path for all of us to take is for you to email me your latest .po file, I'll add it here, wait for the travis checks to say ok, then merge it in.
At this point, hr.po will then be in master, and from there you can do further updates and patches as it will then be in master.
My email is on my home page: https://github.com/JoesCat

**Comment by fitojb** [comment]
(Another open-source l10n platform is Weblate, if you want to consider it… Personally, I’m active in both Translatewiki and Weblate, and have stopped working in Transifex-hosted translations).

**Comment by ctrlcctrlv** [comment]
@fitojb Let's talk in #3814 so as not to further inconvenience milotype and Joe

**Comment by milotype** [comment]
@JoesCat So once you `make`, what will I have to do on my side. Will I need to wait for the next app-update or just change some files on my mac? BTW, I'll send you a simple `hr.po` file by mail as you suggested.

**Comment by JoesCat** [comment]
I was about to merge in the hr.mo file and then realized, the master doesn't hold mo files.
Sorry about my error.
hr.po file compiled fine - looks good to merge as soon as travis checks returns okay to merge.

**Comment by JoesCat** [comment]
Excellent!
Thanks Milo

**Comment by milotype** [comment]
@JoesCat So now a `hr.po` file is in "master". Good. But it still doesn't help me to test FontForge on my computer. Maybe in my messages I wasn't clear about the fact, that I'm not missing the `FontForge.mo` file. I generate it with Poedit (translation app) on my computer. And with other OpenSource programs I've translated, I simply copied that .mo file into the appropriate app-folder of my Mac.
(see https://github.com/fontforge/fontforge/pull/3808#issuecomment-513551492)

My problem is that FF doesn't start with other languages but english :-( Allthough I have my system setiings set in the order of Croatian, German, English.
Sorry for the inconvenience.

**Comment by JoesCat** [comment]
The compiled file would be hr.mo not fontforge.mo
Each language will have a separate file fr.mo for French, es.mo for Spanish, de.mo for German etc.

**Comment by milotype** [comment]
Hmmm ... that's probably on the repository, because the `.po` files are named that way. But on my Mac, in the locale folder of the FontForge app, the `.mo` files of **all** languages are named "FontForge.mo" ???

**Comment by milotype** [comment]
PLEEEASE!!!
Can anybody tell me how to make FotForge app use a different locale than english.
=> MacOSX 10.11.6, FontForge version 20190413
(please look at above comments, so I don't repeat myself too much)
Sorry I keep bothering, but I need a solution.
Help is much appreciated!

**Comment by jtanx** [comment]
No one actively develops on Mac, so support there is best-effort.

It turns out that the travis builds weren't detecting libintl properly, so translation support is actually not present in that version. I'm attempting a fix with #3821. Supposing that works, you will need to wait until it's merged into master.

Once it's merged, you'll have to wait for it to build again, and it should create a new bundle, which you can download from here: http://dl.bintray.com/fontforge/fontforge/

From there, using what you did here:

```sh
MacBookPro:~ milo$ export LANGUAGE=hr
MacBookPro:~ milo$ /Applications/FontForge.app/Contents/MacOS/FontForge
```

Should work (touch wood).

**Comment by milotype** [comment]
@jtanx Thank you for your effort! 
Why do I need to go through terminal, instead of just copying the `.mo` file in the appropriate app-folder? As said before, that's what I usually do with my translations for other (OpenSource) apps.
… I know, curiosity killed the cat, but … ;-)

**Comment by jtanx** [comment]
@milotype  it may in fact work as you have described without having to go through the terminal. If I want to see the translations, I always have to do that because my locale is always set to English.

Anyway, try downloading this: http://dl.bintray.com/fontforge/fontforge/FontForge-2019-07-25-d89acb7.app.dmg

And see if you have any better luck

**Comment by milotype** [comment]
@jtanx … bummer … the image `FontForge-2019-07-25-d89acb7.app.dmg` I can install FF, but during app startup it exits with an error, to send to Apple. (I haven't done that of course). Don't know if it helps in any way, so I've attached the report here.
I have also tried the other file `FontForge-2019-07-25-4990675.app.dmg`, it also doesn't work.
[FF-mac-error.txt](https://github.com/fontforge/fontforge/files/3430925/FF-mac-error.txt)

**Comment by jtanx** [comment]
Hmm, looks like it's because it was built for a newer version of MacOS than what you're running. I'll try tweaking the travis build to bump it back.

**Comment by milotype** [comment]
Thank you. Is FontFOrge not planning to support MacOS-X-10.11.6? It's not that old of a system ;-)

**Comment by jtanx** [comment]
It's dependent on whatever Travis and Homebrew supports. It's probably the recent switch to Python3 that's changed up some required system dependencies, so I just need to adjust the Travis build image back to something that builds on 10.11(#3824)

**Comment by jtanx** [comment]
Ok, this is  going to be painful, Homebrew apparently don't even provide precompiled binaries for el capitan any more...

**Comment by milotype** [comment]
Hmmm … and 10.11.6 is the last version my MacBook Pro supports …

**Comment by jtanx** [comment]
Yeah, that's a tough one. El Capitan is EOL/unsupported since last year, and Homebrew stopped providing binaries for it 2 years ago.

**Comment by ctrlcctrlv** [comment]
Time to install Linux on it :-)

**Comment by milotype** [comment]
So is there going to be a solution for my case?
As said before, I have no trouble with any other OpenSource apps I've been translating (Scribus, Inkscape, Gimp, Gramps, etc.). As I'm no programmer, I really don't know where the difference is.

**Comment by jtanx** [comment]
Sort of, but not really. Given what's available, the base version that FontForge would support is MacOS Sierra (>= 10.12).

I've switched to use Python 3 instead of 2, and I'm not planning on changing that. As a concession, I am contemplating building both a Python 2 and 3 version (#3825), but only the Python 3 release will be promoted; the Python 2 bundles will live only in the bintray repo.

The Python 2 bundle should work for you, merely because it doesn't require some newer dependencies that's not in El Capitan, but you're running on borrowed time. I wouldn't be surprised if it broke again in the future because of some new rebuild that now requires stuff not present in El Capitan.

It's likely that I will also stop doing this after this next release (somewhere around the 1st of August), as we have plans to drop Python 2 support altogether.

**Comment by milotype** [comment]
That would be great, and I can live with that. 
So the best thing would be if I sent my hr-translation through GitHug in the next couple of days, as I've translated about 70% already. I usually translate the essential UI strings first (commands, basic explanations, etc.), then I do the rest.

**Comment by JoesCat** [comment]
> So the best thing would be if I sent my hr-translation through GitHug in the next couple of days...

or just send in a pull request with your latest hr.po by end of month to catch the next release.
Your last hr.po had no issues.
Only thing missing is an actual check by yourself.

I found more info, not sure if this helps:
https://www.gnucash.org/docs/v3/C/gnucash-help/chang-lang.html
the wiki suggestion also says try --app, so the --app might probably be org.fontforge.FontForge
...but if 20190413 had the mac build was built incorrectly and always ran english, then it may probably still default to english

**Comment by milotype** [comment]
Yes, pull request is what I meant … and yes, I'll check afterwards in the next release.

> the Python 2 bundles will live only in the bintray repo.
Where will that be? Can you give me the link to the location please.

**Comment by jtanx** [comment]
Try this http://dl.bintray.com/fontforge/fontforge/:FontForge-2019-07-26-279e691-python2.7.app.dmg

**Comment by milotype** [comment]
Thank you. Thank you. Thank you. THIS WORKS!
After deinstalling the old and then installing the new FontForge, the app starts … as always in English. But, going through the terminal with what you've suggested in some earlier message, FontForge actually starts with Croatian.
So in Terminal, I did:
```
export LANGUAGE=hr
/Applications/FontForge.app/Contents/MacOS/FontForge
```
and FontForge started with Croatian GUI !!!

**Comment by milotype** [comment]
The only drawback is, FontForge **MUST** be run through Terminal for startup of the locale, every time. Quitting FontForge with Croatian locale, and double-clicking on the FF-icon, FontForge starts again in English!

So this might be something which could/should be worked on in the two **Open** issues (#2443, #2398).

**Comment by jtanx** [comment]
Well for now, you can just modify /Applications/FontForge.app/Contents/MacOS/FontForge to include that export if you want it permanently changed.

**Comment by milotype** [comment]
It was just what I was going to try next … I confirm, it works:
Modified
`export LANG=en_US.UTF-8`
to
`export LANG=hr.UTF-8`
After that, double-click on FF-icon, opens FontForge with Croatian GUI.

**Comment by jtanx** [comment]
🤦‍♂ 

Does it automatically open in Croatian if you just comment or remove that line?

**Comment by skef** [comment]
LSEnvironment would be another means: https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/LaunchServicesKeys.html#//apple_ref/doc/uid/20001431-106825

**Comment by milotype** [comment]
> Does it automatically open in Croatian if you just comment or remove that line?
No, neither one works. FontForge starts in English in both cases.

**Comment by milotype** [comment]
@jtanx My Croatain translation works fine in most cases. But, there are cases, where certain UI strings keep showing in English. As mentioned before in:
https://github.com/fontforge/fontforge/pull/3808#issuecomment-513548706

So I'd like to ask you or anybody who can, to generate and add the current `.pot` file in the po-folder of the master, so I could download the file and update my translation file.

I'm planning to send a merge request before 31st July, so the croatian translation (ca. 75% done) could be packed with the new release.

**Comment by jtanx** [comment]
I was going to make this into a pr, but there are some other issues which I can't be bothered fixing now. So I'll just provide the files here: 
[po.zip](https://github.com/fontforge/fontforge/files/3438773/po.zip)

Do you just need the pot file? I also ran msgmerge against hr.po, but I don't know if that's actually useful or not.

**Comment by milotype** [comment]
Thanks for the .pot file!
I also don't know about the exact dependancies, but having a current pot-file is always good to have and can't be wrong ;-)

**Pull request merged**
