### PR TITLE
Korean translation corrected

### LINKED ISSUE #4748: Ongoing of Korean Translation Issue
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [ ] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [x] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

I've tried to correct Korean Translation of /po/ko.po because its result was so rough and weird. Although some people are helped, a part of results have used a machine translation result from Japanese translation. It seems to be correctly as soon as possible, I forked fontforge git from master then it fixed to my github location. ([here](https://github.com/hurss/fontforge/blob/master/po/ko.po))
If you want to approve it, you may can this file push to fontforge master.

### PR DESCRIPTION
**Pull request by ctrlcctrlv**
Opened PR at the request of @hurss in #4748.

Closes #4748.

### Type of change

- **Translation update**

### CODE REVIEW

**Comment by jtanx** [comment]
The main source is on crowdin, so we'll need to find a way to sync it between here and there.

**Comment by ctrlcctrlv** [comment]
I don't speak Korean but checked a few of the new strings with a dictionary/machine translator and this change seems very positive to me. @hurss is Korean so I trust their overall judgment, if they say that someone cheated previously and tried to pass off machine translation from Japanese as human translation I believe them. It happens sometimes unfortunately because maintainers don't speak every language on Earth so must trust submitters to a degree, which cannot be helped.

**Comment by hurss** [comment]
Currently, I trying to correct Korean translation script of fontforge. When I have fixed it, I'll push it to my repository.

**Comment by jtanx** [comment]
These changes have been incorporated into #4928.

**Pull request closed without merging**
