### PR TITLE
Ui icons

### PR DESCRIPTION
**Pull request by larsenwork**
@frank-trampe 
Palette icon: 26x26
Palette small icon: 22x22

Unsure why GitHub thinks I've done a full rewrite of `images.c` - sourcetree only showed the relevant hunks when I pushed it. What's changed in that file is: 

Updated comments on line 12222, 12257, 12285-12286
Change ptinfo icons to palette icons on line 12287-12290

### CODE REVIEW

**Comment by frank-trampe** [comment]
You removed a lot of trailing spaces in images.c.

**Comment by frank-trampe** [comment]
I know it seems ridiculous to bring this up now, but I'm not sure that the meanings of the transform buttons are obvious without arrows.

**Comment by larsenwork** [comment]
trailing: ah, I've got I whitespace plugin in my editor so that's why - weird the difference didn't get detected in SourceTree when I pushed it. Should I revert or? 

arrows: I didn't do it because clutter
Scale + rotate + skew icons are so familiar they definitely don't need arrows
Flip is fucked because usually you have flip vertical and flip horizontal with the two triangles icon but in FF you flip vertically+horizontally with same tool.
3D rotate: Open to suggestions - I've yet to see a good+minimal 3D rotate icon. By adding axis arrows 
Perspective: No arrow(s) can explain what it does.

**Comment by frank-trampe** [comment]
Don't bother fixing the whitespace yet. We'll probably need to do another pull request once I implement the icon sizing anyway.

I don't have a strong opinion on the aesthetic, but I find the GIMP's transform icons very easy to understand.

**Comment by larsenwork** [comment]
ok.

GIMP: only share skew(shear), scale and rotate as far as I can tell and those are easily understood without arrows

**Comment by larsenwork** [comment]
The perspective tool in FF is not really perspective - more like 3d curl - so using a normal perspective icon would be misleading.

Just Googled and saw the "turn the page" icon is flip - thought it was some 3D/perspective thing from the icon:)

**Comment by davelab6** [comment]
Is anything blocking this?

**Comment by davelab6** [comment]
@larsenwork @frank-trampe anything more to do before merging this?

**Comment by frank-trampe** [comment]
I need to redo a few of the commits. The editor broke the whitespace and generated a huge diff. And I think that there was some other work, too. I'll check tomorrow.

**Comment by davelab6** [comment]
@frank-trampe I would love to get this into the next release :)

**Comment by frank-trampe** [comment]
Closed via #2720.

**Pull request closed without merging**
