### PR TITLE
msgstr formatting discrepancies

### PR DESCRIPTION
**Pull request by iorsh**
Fix formatting discrepancies between msgid and msgstr. Windows build fails because of them.

### CODE REVIEW

**Comment by muelli** [comment]
this looks like it could fix https://github.com/fontforge/fontforge/issues/5251

**Comment by skef** [comment]
I've never been much involved in this part of the project, but I believe FontForge uses CrowdIn for localization here: https://crowdin.com/project/fontforge , and then a script is run to pull any changes down prior to a release. If the strings aren't fixed there there will be an ongoing synchronization problem. Have you checked into that?

**Comment by iorsh** [comment]
> I've never been much involved in this part of the project, but I believe FontForge uses CrowdIn for localization here: https://crowdin.com/project/fontforge , and then a script is run to pull any changes down prior to a release. If the strings aren't fixed there there will be an ongoing synchronization problem. Have you checked into that?

Yes, Fredrick addresses it in https://github.com/fontforge/fontforge/pull/5257. I will kill this PR and see what can be done with CrowdIn.

**Comment by skef** [comment]
Looks like at least one message is fixed in Crowdin as of six months ago. It's likely they all are. Let me see about synching.

**Pull request closed without merging**
