### PR TITLE
sfd.c: perform better validation of some inputs

### PR DESCRIPTION
**Pull request by jtanx**
Fixes crash noted in #4524.

### Type of change

- **Bug fix**

### CODE REVIEW

**Review by skef — APPROVED** [review]
lgtm

**Comment by yg8ijvjvjv** [comment]
Does this also fix the glitching of cross-font references when copying bitmap references?

**Comment by ctrlcctrlv** [comment]
No, just the crash.

**Comment by yg8ijvjvjv** [comment]
But note that crashes are usually caused by glitchy state. Because the glitchy state of cross-font references is not fixes, there are still many crashes left. For instance, closing the font the references are pointing to causes a crash when FontForge tries to read the references by dereferencing their memory address and the only way to fix it is to fix bitmap reference clipboard.

**Pull request merged**
