### PR TITLE
Fix an error on mixing-up binary and hexadecimal

### PR DESCRIPTION
**Pull request by mandel59**

### CODE REVIEW

**Comment by jtanx** [comment]
Nice find! Introduced by a9c48a63. cc @adrientetar - is this a similar issue for [L3362](https://github.com/fontforge/fontforge/commit/a9c48a6314b93cdded1b2bfa1312c2bb150b240c#diff-9b22dffd5421ecff80de9af9e53a8b27R3362)?

**Comment by adrientetar** [comment]
Oops, thanks for the patch.

> cc @adrientetar - is this a similar issue for L3362?

Yes.

**Comment by adrientetar** [comment]
Merged and followup in 6eac581fc4d97c2ea2ff30e76d3b02e726be2eef.

**Comment by jtanx** [comment]
:thumbsup:

**Pull request merged**
