### PR TITLE
support reproducible builds

### LINKED ISSUE #2711: Please do not put timestamps in generated files
cc @frank-trampe 
### When you open an issue for a change/improvement/feature request:
- [x] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [x] (optional) Possible solution/fix/workaround

I'd like to propose to not put any timestamps in the generated .ttf (or any other) files. If this is not wanted generally, I'd like to propose an option which allows this.
### Reason:

The [Wine project](https://www.winehq.org/) uses a [forked fontforge](http://source.winehq.org/git/fontforge.git/) (this issue is about 1 of their 4 changes). The generated files are stored in a git repository. Recreating the files with an unpatched fontforge creates spurious diffs after every rebuild.
Generally this is related to reproducible builds (see below).
### Related things:

This has already been partly requested in issue #2389 (Generate: Don't include FFTM) by @davelab6, but afaik timestamps also land in the tables "head" (and "bhed"). I understand that while FFTM is fontforge specific, the latter two were [specified by Apple](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6head.html). I assume/hope this doesn't mean that timestamps are strictly required in order to not break 3rd party consumers.
But even in this case I can confirm that Wine works happily without timestamps.

This is also related to the **[reproducible builds effort](https://reproducible-builds.org/)**:
-  #2490 (propagate creation and modification times to TTF files, [Debian bug #774148](https://bugs.debian.org/774148)) is already fixed (95a470e941d9a20fbdaca51334e8b6b9d93cfae4).
- But there's still [Debian bug #774274](https://bugs.debian.org/774274) (fontforge: please use SOURCE_DATE_EPOCH for reproducible font modification time; was: please allow scripts to set the font modification time). This request would be obsolete if you dropped timestamps altogether.
  On the other side, [implementing SOURCE_DATE_EPOCH](https://reproducible-builds.org/specs/source-date-epoch/) would also solve the problem for Winehq maintainers if a sensible workflow is found. It's just not as trivial as for a Debian maintainer. If it helps I may file a separate issue about that. I have no patch to offer, but there are some instructions in the link.
### For reference:

We discussed the Winehq fork:
https://www.winehq.org/pipermail/wine-devel/2016-April/112893.html

The original Winehq hacks (based on 20081224):
http://source.winehq.org/git/fontforge.git/commitdiff/65974286fe1ae1700eb58e32000b13648455000f

The currently used form (rebased on v20120731-b):
https://github.com/jre-wine/fontforge/commit/23d13b4a5923745e586b0fd03f23ded6706230c3

My attempt to rebase it on 20160404 (doesn't seem to catch everything: the ttf's still differ, while they are identical with Winehq's fontforge):
https://github.com/jre-wine/fontforge/commit/c2d28ed828ab3c82ed028a22702bae056f174ba2
### Disclaimer:

I'm not using fontforge personally, neither am I a Wine developer. I'm only working on the Wine packaging in Debian. So although I really tried to get a good picture of what is still relevant, it may well be that I missed something.
Winehq and Debian are currently both using 20120731-b, but Debian is working on updating, and Winehq is willing to do the same. I tested my changes with 20160404 locally.

Thanks and greets
jre

### PR DESCRIPTION
**Pull request by volth**
Provide a general summary of your changes in the **Title** above.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### Motivation and Context
- [x] It blocks propagation of environment entropy (such as the current time or the Linux user name) to the produced fonts when it is not desirable. It is detected by presence ```$SOURCE_DATE_EPOCH``` in the environment which is set by Debian and NixOS build script when they want to do a reproducible build.
- [x] Closes #2711 #2389

### Types of changes
What types of changes does your code introduce? Check all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description
- [x] Describe your changes in detail.
if ```$SOURCE_DATE_EPOCH``` is detected then its value is used instead of system time or last modification time of the source files (which is often close to the current time if they were just patched or pre-processed). Also presence of ```$SOURCE_DATE_EPOCH``` blocks propagating of the current Linux user name to the ```author``` field of the fonts. It is often non-deterministic (like ```build-user-4```, etc)

It is not relevant to https://github.com/fontforge/fontforge/pull/2943, which is about ```$SOURCE_DATE_EPOCH``` when fontforge is being compiled from C sources, this fix about ```$SOURCE_DATE_EPOCH``` when fontforge compiles fonts.

### Final checklist
Go over all the following points and check all the boxes that apply. 
If you're unsure about any of these, don't hesitate to ask. We're here to help! Various areas of the codebase have been worked on by different people in recent years, so if you are unfamiliar with the general area you're working in, please feel free to chat with people who have experience in that area. See the list [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#people-to-ask).
- [ ] My code follows the code style of this project found [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#coding-style).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md) guidelines.

Your pull request will be tested via Travis CI to automatically indicate that your changes do not prevent compilation. FontForge is a big program, so Travis can easily take over 20 minutes to confirm your changes are buildable. Please be patient. More details about using Travis can be found [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#using-travis-ci).  
  
If it reports back that there are problems, you can log into the Travis system and check the log report for your pull request to see what the problem was. If no error is shown, just re-run the Travis test for your pull-request (that failed) to see a fresh report since the last report may be for someone else that did a later pull request, or for mainline code. If you add new code to fix your issue/problem, then take note that you need to check the next pull request in the Travis system. Travis issue numbers are different from GitHub issue numbers.

### CODE REVIEW

**Comment by jtanx** [comment]
This kind of feels like a hack... This is better done as one of:

* Check `SOURCE_DATE_EPOCH` once in one location and set some variable accordingly. Use said variable where needed
* As before, but take it as an input argument to fontforge instead of an environment variable
* As before, but as a user preference.

**Comment by gioele** [comment]
Hi @volth, thank you for the PR. As @jtanx said, the changes you are proposing are OK, but a bit too "verbose". Fontforge's code base is already _hackish_ enough. :)

I went ahead and created added two functions to `gutils.c` that wrap `time` and `st_mtime`. You can find the code in my branch [`reproducible-time-author`](https://github.com/gioele/fontforge/tree/reproducible-time-author).

Could you please update this commit to use these two functions?

**Comment by frank-trampe** [comment]
@volth, thanks for pushing this ahead by submitting the pull request. This has been on my list for a long time. @gioele, any chance you could just make a new superseding pull request with your modifications? I like the simple fix.

**Comment by gioele** [comment]
@frank-trampe: I'm afraid I don't understand what you are suggesting; the English parser in my brain gets clogged every now and then. ;)

Are you suggesting to merge @volth commit now and then clean up using my two functions? Or are you suggesting that I make another PR with just my changes, merge it and then ask @volth to reimplement the suggested changes on top of the new master? Or something else altogether?

**Comment by frank-trampe** [comment]
@giole, I was hoping that you might just be able to make one pull request that accomplishes what we need. It simplifies the merge logistics.

**Comment by JoesCat** [comment]
Can you review GetTime() found in [libspiro call-test.c](https://github.com/fontforge/libspiro/blob/master/tests/call-test.c)
This GetTime() version has already gone through edits to work with older operating systems (as old as DOS), and also works okay with current operating systems. Some patching was done to revert a fail for an older openBSD 7or8, but HEAD works okay with Mac, so I believe it's okay now too.
`SOURCE_DATE_EPOCH` is a recent variable that doesn't exist with older operating systems and I suspect it will be a problem for backwards compatibility.

**Comment by jtanx** [comment]
From what I can see, SOURCE_DATE_EPOCH  is an environment variable, so unless the os doesn't support that, I don't see why it wouldn't work.

**Comment by JoesCat** [comment]
On September 3, 2017 03:06:26 PM Jeremy Tan wrote:
> From what I can see, SOURCE_DATE_EPOCH  is an environment variable, so
> unless the os doesn't support that, I don't see why it wouldn't work.

Yes, you're right - my error.

The "} else {" section of the if is the part that should be modified to deal 
with recent and older operating systems.
When I upgraded libspiro, it definitely needed to use the older code style 
for older operating systems, and it needed the newer style for newer 
operating systems.

The earliest use of SOURCE_DATE_EPOCH appears to be about 2015-10-26
https://reproducible-builds.org/docs/timestamps/
It appears to be fairly linux/debian centered:
https://wiki.debian.org/ReproducibleBuilds/TimestampsProposal#Reading_the_variable

The suggestion I made works as far back as 1990, maybe even earlier, and is 
what I should have meant for the "} else {" section.

**Comment by frank-trampe** [comment]
@JoesCat, just to be clear, your wrapper only deals with fetching the actual time, not with parsing a string to an integer, right? If so, these two things (adding support for getting a timestamp from an environment variable and enhancing support for getting the current time) are entirely disjoint issues, such that we can handle them at separate times. It wouldn't hurt to work on our legacy support, but it's not clear to me that adding a smarter time wrapper would actually allow us to target older platforms. The gnulib switch essentially foreclosed on all of those possibilities, and it's tough to go back now.

**Comment by volth** [comment]
There are still reproducible problem: fonts compiled on MacOS differ from fonts compiled on Linux: (Travis CI failure in https://github.com/NixOS/nixpkgs/pull/28216).
I have no MacOS here so cannot investigate :(

**Comment by gioele** [comment]
hi @volth, could you please the Travis script of the [failing built](https://travis-ci.org/NixOS/nixpkgs/jobs/279055625) to store the generated font somewhere or to output it to the standard output? Something like the following would be enough.

```
- echo "Dump of the generated file" && hexdump < generated-font.ttf
```

That will give us a file to play with in order to discover the root cause of this.

**Comment by volth** [comment]
@gioele If I would know how to download from Travis CI, I could fix the issue. It is not mine Travis, it is the one affiliated with github which does build the pull requests

The script to build the font is
https://github.com/NixOS/nixpkgs/blob/master/pkgs/data/fonts/libertine/default.nix
The resulting sha256 is different on Linux and MacOS

**Comment by gioele** [comment]
@volth: you can change the Travis script without being the repo owner. It's quite easy. :) Just add

```
after_failure: echo "Dump of the generated file" && hexdump < GENERATED-FONT.ttf
```

to `.travis.yml` after the `script:` line in the `osx` stanza. Then make a commit in the branch linked to the PR and push it.

Travis will display the content of the font in the log and from that we can read it back.

**Comment by volth** [comment]
@gioele nice hint, thank you!

**Comment by volth** [comment]
There is something really weird on MacOS: not only the font files are different, but there are one font file missing (65 files produced on Linux and 64 on MacOS)

**Comment by volth** [comment]
Apart from Travis issues (with lost files), there are difference in order of same-name features in GSUB table (I built the same fonts on Hackintosh in VirtualBox):



I am not sure should the same-name features be ordered or merged or dropped.. Perhaps it is a topic for another issue.

**Comment by frank-trampe** [comment]
I can't look at this until later in the week. I'm not terribly concerned about Macintosh, though, as industrial workflows of the sort that require consistency probably run on Linux these days.

**Comment by volth** [comment]
This is likely gcc vs. clang issue than linux vs. macos

**Comment by gioele** [comment]
hi @volth, I have just pushed PR #3176 with full support for `SOURCE_DATE_EPOCH`.

Could you please close this PR and file a separate bug with all the information about the mismatch between Linux and MacOS fonts, possibly with attachments?

**Pull request closed without merging**
