### PR TITLE
Fix Coverity reports:

### PR DESCRIPTION
**Pull request by serval2412**
1082917
1082918
1082919
1082920
1082929

Provide a general summary of your changes in the **Title** above.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### Motivation and Context
- [ ] Why is this change required? What problem does it solve?
- [ ] If it fixes an open issue, include the text `Closes #1` (where 1 would be the issue number) to your commit message.

### Types of changes
What types of changes does your code introduce? Check all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description
- [ ] Describe your changes in detail.

### Final checklist
Go over all the following points and check all the boxes that apply. 
If you're unsure about any of these, don't hesitate to ask. We're here to help! Various areas of the codebase have been worked on by different people in recent years, so if you are unfamiliar with the general area you're working in, please feel free to chat with people who have experience in that area. See the list [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#people-to-ask).
- [ ] My code follows the code style of this project found [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#coding-style).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md) guidelines.

Your pull request will be tested via Travis CI to automatically indicate that your changes do not prevent compilation. FontForge is a big program, so Travis can easily take over 20 minutes to confirm your changes are buildable. Please be patient. More details about using Travis can be found [here](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#using-travis-ci).  
  
If it reports back that there are problems, you can log into the Travis system and check the log report for your pull request to see what the problem was. If no error is shown, just re-run the Travis test for your pull-request (that failed) to see a fresh report since the last report may be for someone else that did a later pull request, or for mainline code. If you add new code to fix your issue/problem, then take note that you need to check the next pull request in the Travis system. Travis issue numbers are different from GitHub issue numbers.

### CODE REVIEW

**Comment by serval2412** [comment]
@skef: thank you for your feedback.
I wonder if it doesn't lack a free(instrs) + return(NULL) here:
    377             if ( npos==0 )
    378                 IVError(iv,_("Expected a number for a push count"),pt-text);
or at least a comment which indicates that we don't return specifically here on purpose
What do you think?

**Comment by skef** [comment]
It's hard for me to say. I guess a comment would be appropriate but I don't know enough to add one.

**Comment by serval2412** [comment]
Ok so let's put this aside.

**Comment by ctrlcctrlv** [comment]
What is even the point of Coverity for this project?

Has Coverity ever seriously helped us fix a bug, crash, etc?

**Comment by skef** [comment]
For one thing, a volunteer is running Coverity, finding and fixing some memory leaks, and submitting push requests with those fixes. 

Is this likely to change the world? Probably not. But given all the gnashing of teeth about C in this project's I don't see it as bad. 

Is there any really point in trying to fix the docs? Does anything matter at all? Do we have to think about it?

**Comment by ctrlcctrlv** [comment]
OK I was just wondering, if it has actually fixed leaks and bugs let's use it. I probably fail to understand its purpose...

**Comment by skef** [comment]
It's primarily about leaks as it applies to fontforge. The significance of small leaks is controversial; most users won't run the software in a way that small leaks will wind up mattering. But the general goal is to line up `malloc`s with `free`s, and these push requests have furthered that goal.

**Comment by ctrlcctrlv** [comment]
Sorry for my ignorance, I thought it was just something like coveralls

**Comment by jtanx** [comment]
We're the ones running coverity, it runs whenever I push to the `coverity_scan` branch. You can view what it finds [here](https://scan.coverity.com/projects/792) but you have to request access

**Comment by skef** [comment]
@jtanx do you have an easily reached opinion on

>I wonder if it doesn't lack a free(instrs) + return(NULL) here:
377 if ( npos==0 )
378 IVError(iv,_("Expected a number for a push count"),pt-text);
or at least a comment which indicates that we don't return specifically here on purpose

? (Those are new rather than original line numbers)

**Comment by jtanx** [comment]
It's hard for me to say too, I'm not familiar enough with this area. https://github.com/fontforge/fontforge/pull/3591/files#diff-d0278bcb69d2e755e222fe81f685a45aL316 that's the original context fwiw

**Comment by skef** [comment]
Best to leave as-is then.

**Comment by JoesCat** [comment]
What is even the point of Coverity for this project? What is even the point of Coverity for this project?
Hi @ctrlcctrlv, sometimes the easiest way to explain this is to see what it is. I've sent you an invite so you can look at it. Just think of this as a spell-check or lint collector for programming.

**Pull request merged**
